// Articles de blog thématiques SEO. Même contrat que POSTS.
// Ajouter un objet ici alimente /blog/<slug>, /blog et le sitemap.

import type { Post } from "./posts";

export const POSTS_SEO: Post[] = [
  {
    slug: "comment-faire-audit-seo",
    title: "Comment faire un audit SEO complet (méthode et checklist 2026)",
    description:
      "Les étapes concrètes d'un audit SEO : technique, on-page, contenu, netlinking et Search Console. Les outils à utiliser et comment prioriser les corrections.",
    date: "2026-06-23",
    readingTime: "9 min",
    category: "SEO & Web",
    keywords: [
      "comment faire un audit SEO",
      "audit SEO gratuit",
      "checklist audit référencement",
      "analyser son SEO",
    ],
    related: [
      { href: "/services/seo", label: "SEO technique" },
      { href: "/blog/ameliorer-core-web-vitals-vitesse-site", label: "Améliorer la vitesse de son site" },
    ],
    content: [
      { type: "p", text: "Un audit SEO, ce n'est pas cliquer sur un outil qui affiche un « score sur 100 ». C'est un diagnostic méthodique qui identifie ce qui empêche votre site de se positionner, puis hiérarchise les corrections par impact. Un bon audit répond à une question simple : pourquoi ne suis-je pas mieux classé, et par quoi commencer ? Voici la méthode que nous suivons, découpée en cinq volets, avec les outils et l'ordre de priorité." },
      { type: "h2", text: "Volet 1 : l'audit technique" },
      { type: "p", text: "On commence par le technique, car un contenu excellent sur une page que Google ne peut pas explorer ou indexer ne servira à rien. L'objectif est de vérifier que les robots accèdent au site, le comprennent et l'indexent correctement." },
      { type: "ul", items: [
        "Indexation : combien de pages sont réellement indexées (rapport Pages de Search Console) par rapport au nombre de pages utiles ?",
        "Exploration : robots.txt, sitemap.xml, balises noindex involontaires, chaînes de redirections, erreurs 404 et 5xx.",
        "Canonisation : balises canonical cohérentes, contenu dupliqué, versions http/https et www/non-www unifiées.",
        "Vitesse et Core Web Vitals (LCP, INP, CLS), qui pèsent sur l'expérience et sur le classement mobile.",
        "Rendu : le contenu est-il bien présent dans le HTML servi, ou dépend-il d'un JavaScript que Google explore mal ?",
      ]},
      { type: "h2", text: "Volet 2 : l'audit on-page" },
      { type: "p", text: "On passe ensuite à ce que voit Google page par page. Chaque page importante doit répondre clairement à une intention de recherche et l'exprimer dans ses balises." },
      { type: "ul", items: [
        "Balises title uniques, descriptives, avec le mot-clé principal placé naturellement.",
        "Meta descriptions incitatives (elles n'influencent pas le classement mais bien le taux de clic).",
        "Structure des titres Hn : un seul H1 par page, une hiérarchie logique des H2 et H3.",
        "Balises alt des images, URLs propres et lisibles, maillage interne pertinent.",
        "Données structurées Schema.org quand elles sont justifiées (Article, FAQ, Breadcrumb).",
      ]},
      { type: "h2", text: "Volet 3 : l'audit de contenu" },
      { type: "p", text: "C'est souvent là que se cachent les plus gros gains. On regarde si le contenu couvre réellement l'intention de recherche, s'il est à jour, et s'il ne se cannibalise pas. Deux pages qui visent le même mot-clé se font concurrence entre elles et affaiblissent votre position : mieux vaut les fusionner. À l'inverse, un contenu mince qui n'apporte rien peut être enrichi ou élagué. On cartographie aussi les sujets manquants par rapport aux requêtes réellement tapées par vos clients." },
      { type: "h2", text: "Volet 4 : l'audit du netlinking" },
      { type: "p", text: "L'autorité d'un site dépend en partie des liens que d'autres sites font vers lui. On évalue le profil de liens entrants : leur nombre, leur qualité, la diversité des domaines référents, et surtout la présence éventuelle de liens toxiques (fermes de liens, annuaires douteux) qui peuvent pénaliser. Un profil sain est composé de liens naturels, provenant de sites thématiquement cohérents avec votre activité." },
      { type: "h2", text: "Volet 5 : les données Search Console" },
      { type: "p", text: "Google Search Console est la source de vérité gratuite et la plus fiable, car elle vient directement de Google. On y lit les requêtes sur lesquelles vous apparaissez, votre position moyenne, votre taux de clic, et les pages qui rament juste à la frontière de la première page. Repérer les mots-clés positionnés en bas de première page ou en haut de deuxième est un raccourci précieux : un petit effort peut y débloquer un trafic significatif." },
      { type: "cta", text: "Vous voulez un audit SEO clair, priorisé et actionnable pour votre site ?", href: "/services/seo", label: "Demander un audit SEO" },
      { type: "h2", text: "Quels outils utiliser ?" },
      { type: "p", text: "On peut mener un audit sérieux avec des outils gratuits : Google Search Console (indexation, requêtes, couverture), PageSpeed Insights et l'outil de test des résultats enrichis pour la partie technique, et un crawler pour parcourir le site. Les suites payantes comme Ahrefs ou Semrush ajoutent surtout la vision du netlinking et l'analyse concurrentielle. L'outil ne fait pas l'audit : c'est l'interprétation et la priorisation qui comptent." },
      { type: "h2", text: "Prioriser : la partie qui change tout" },
      { type: "p", text: "Un audit qui liste cent problèmes sans les hiérarchiser est inutilisable. On classe chaque point selon deux axes : l'impact SEO attendu et l'effort de correction. On traite d'abord ce qui bloque l'indexation (impact maximal, souvent effort faible), puis les gains rapides de contenu et de balisage, et enfin les chantiers de fond comme le netlinking. L'objectif final n'est pas un rapport, mais une feuille de route où chaque action est justifiée par sa valeur." },
    ],
    faq: [
      { q: "Peut-on faire un audit SEO gratuitement ?", a: "Oui, une bonne partie d'un audit se fait avec des outils gratuits : Google Search Console pour l'indexation et les requêtes, PageSpeed Insights pour la performance, et l'outil de test des résultats enrichis pour les données structurées. Les suites payantes apportent surtout l'analyse du netlinking et de la concurrence. La valeur d'un audit tient moins à l'outil qu'à l'interprétation et à la priorisation." },
      { q: "Combien de temps prend un audit SEO ?", a: "Cela dépend de la taille du site. Pour un site vitrine ou une petite boutique, un audit complet demande généralement quelques jours. Pour un gros e-commerce avec des milliers de pages, il faut davantage de temps pour l'exploration technique et l'analyse de contenu. L'important est de couvrir les cinq volets : technique, on-page, contenu, netlinking et Search Console." },
      { q: "Par quoi commencer après un audit SEO ?", a: "On commence par ce qui bloque l'indexation, car c'est ce qui a l'impact le plus fort pour l'effort le plus faible : balises noindex involontaires, erreurs d'exploration, pages importantes non indexées. Viennent ensuite les gains rapides sur les titres, le contenu et le maillage interne, puis les chantiers de fond comme le netlinking." },
      { q: "À quelle fréquence faut-il refaire un audit SEO ?", a: "Un audit complet une à deux fois par an suffit pour la plupart des sites, complété par un suivi régulier de Search Console. Un audit ponctuel s'impose aussi avant une refonte, après une migration, ou en cas de chute de trafic inexpliquée." },
      { q: "Un bon score sur un outil SEO garantit-il un bon classement ?", a: "Non. Les scores affichés par les outils sont des indicateurs internes à ces outils, pas des critères de Google. Un site peut afficher un score élevé et se positionner mal, ou l'inverse. Ce qui compte, ce sont l'indexation, la pertinence du contenu par rapport à l'intention de recherche, l'expérience utilisateur et l'autorité." },
    ],
  },
  {
    slug: "seo-local-attirer-clients-proximite",
    title: "SEO local : comment attirer des clients près de chez vous",
    description:
      "Les leviers du référencement local pour être visible sur Google Maps et dans le pack local : fiche Google Business Profile, NAP, avis, pages locales et citations.",
    date: "2026-06-22",
    readingTime: "8 min",
    category: "SEO & Web",
    keywords: [
      "SEO local",
      "référencement local",
      "attirer des clients près de chez soi",
      "être visible sur Google Maps",
    ],
    related: [
      { href: "/services/seo", label: "SEO technique" },
      { href: "/blog/optimiser-fiche-google-business-profile", label: "Optimiser sa fiche Google Business Profile" },
    ],
    content: [
      { type: "p", text: "Pour un artisan, un commerce, un cabinet ou un restaurant, le SEO local vaut souvent plus que le référencement national. Quand quelqu'un tape « plombier + votre ville » ou fait une recherche « près de moi », Google affiche d'abord une carte et trois établissements : le fameux pack local. Y figurer, c'est capter des clients à fort intérêt d'achat, au moment précis où ils cherchent. Voici les leviers qui font la différence." },
      { type: "h2", text: "La fiche Google Business Profile : votre pilier" },
      { type: "p", text: "C'est le point de départ du SEO local. Une fiche Google Business Profile complète, catégorisée avec précision et tenue à jour, est ce qui vous rend éligible au pack local et à Google Maps. On soigne la catégorie principale (elle pèse lourd), les horaires, la zone de service, les photos, et on publie régulièrement des actualités. Une fiche vide ou abandonnée ne se positionne pas, même avec un bon site." },
      { type: "h2", text: "La cohérence NAP" },
      { type: "p", text: "NAP signifie Name, Address, Phone : nom, adresse et téléphone. Google recoupe ces informations partout où votre établissement apparaît pour vérifier qu'il est réel et fiable. La règle est simple : ces trois données doivent être rigoureusement identiques partout, au caractère près." },
      { type: "ul", items: [
        "Même orthographe du nom commercial sur le site, la fiche, les annuaires et les réseaux.",
        "Même format d'adresse (abréviations, numéro, code postal) partout.",
        "Même numéro de téléphone, idéalement un numéro local.",
        "Attention aux anciennes fiches en double ou aux coordonnées obsolètes qui traînent en ligne.",
      ]},
      { type: "h2", text: "Les avis clients" },
      { type: "p", text: "Les avis sont un signal de confiance majeur du SEO local, à la fois pour Google et pour les internautes. Un flux régulier d'avis récents, une note solide et surtout des réponses de votre part à chaque avis (positif comme négatif) renforcent votre visibilité et votre taux de conversion. Le meilleur moment pour demander un avis est juste après une prestation réussie : mettez en place une routine simple pour le solliciter systématiquement, sans jamais acheter de faux avis, qui exposent à des sanctions." },
      { type: "h2", text: "Les pages locales sur votre site" },
      { type: "p", text: "Si vous intervenez sur plusieurs villes ou quartiers, créer une page dédiée par zone renforce nettement votre pertinence géographique. Attention toutefois : ces pages doivent apporter un contenu réellement différent et utile, pas de simples copies où seul le nom de la ville change. Google déclasse ce type de contenu dupliqué de faible valeur." },
      { type: "ul", items: [
        "Un contenu spécifique à chaque zone : réalisations locales, particularités, questions fréquentes du secteur.",
        "Le nom de la ville dans le title, le H1 et l'URL, sans sur-optimisation.",
        "Un maillage interne cohérent entre vos pages locales et vos pages de services.",
        "Des informations pratiques : zone d'intervention, délais, coordonnées.",
      ]},
      { type: "cta", text: "Vous voulez apparaître dans le pack local et sur Google Maps de votre secteur ?", href: "/services/seo", label: "Voir notre offre SEO local" },
      { type: "h2", text: "Les citations et annuaires" },
      { type: "p", text: "Les citations sont les mentions de votre établissement (avec son NAP) sur d'autres sites : annuaires professionnels, pages jaunes, plateformes sectorielles. Elles confortent Google dans la réalité et la cohérence de votre entreprise. On privilégie la qualité et la pertinence sectorielle à la quantité : quelques annuaires reconnus et thématiques valent mieux qu'une inscription massive sur des sites douteux, qui n'apportent rien, voire nuisent." },
      { type: "h2", text: "Comprendre les requêtes géolocalisées" },
      { type: "p", text: "Google interprète beaucoup de recherches comme locales même sans mention de ville : quand vous cherchez « coiffeur » ou « garage » sur mobile, il utilise votre position. C'est pourquoi la proximité entre l'internaute et votre établissement est un facteur de classement propre au local, en plus de la pertinence et de la notoriété. Vous ne le maîtrisez pas, mais vous pouvez agir sur tout le reste : une fiche impeccable, un NAP cohérent, des avis réguliers et des pages locales de qualité forment un ensemble qui vous fait remonter là où vos clients vous cherchent." },
    ],
    faq: [
      { q: "Qu'est-ce que le pack local sur Google ?", a: "Le pack local est le bloc qui s'affiche en haut des résultats pour une recherche à intention locale : une carte et généralement trois établissements avec leur note, leurs avis et leurs coordonnées. Y figurer capte une part importante des clics, car il apparaît avant les résultats classiques et concerne des internautes prêts à agir." },
      { q: "Faut-il un site web pour réussir en SEO local ?", a: "Une fiche Google Business Profile bien tenue permet déjà d'apparaître dans le pack local et sur Maps. Mais un site avec des pages locales de qualité renforce nettement la pertinence géographique et améliore la conversion. Fiche et site se complètent : la fiche capte la recherche, le site convainc et rassure." },
      { q: "Comment obtenir plus d'avis clients ?", a: "En les demandant systématiquement juste après une prestation réussie, via un lien direct vers votre fiche. Une routine simple et régulière est plus efficace qu'une campagne ponctuelle. Répondre à chaque avis renforce le signal. En revanche, il ne faut jamais acheter de faux avis, qui exposent à des sanctions et détruisent la confiance." },
      { q: "Qu'est-ce que la cohérence NAP et pourquoi est-elle importante ?", a: "NAP désigne le nom, l'adresse et le téléphone de l'établissement. Google recoupe ces informations partout où elles apparaissent pour vérifier que l'entreprise est réelle et fiable. Elles doivent être identiques au caractère près sur le site, la fiche, les annuaires et les réseaux, sous peine de brouiller le signal local." },
      { q: "Les pages par ville sont-elles utiles ou risquées ?", a: "Elles sont utiles si chaque page apporte un contenu réellement différent et pertinent pour la zone concernée. Elles deviennent risquées quand ce ne sont que des copies où seul le nom de la ville change : Google déclasse ce contenu dupliqué de faible valeur. La règle est donc la qualité et la spécificité, pas la multiplication mécanique." },
    ],
  },
  {
    slug: "netlinking-backlinks-strategie",
    title: "Netlinking et backlinks : bâtir une stratégie de liens qui tient",
    description:
      "Pourquoi les backlinks font l'autorité d'un site, comment obtenir des liens propres (contenu, relations presse, partenaires, annuaires) et éviter les liens toxiques.",
    date: "2026-06-21",
    readingTime: "8 min",
    category: "SEO & Web",
    keywords: [
      "netlinking",
      "stratégie backlinks",
      "obtenir des backlinks",
      "liens entrants SEO",
    ],
    related: [
      { href: "/services/seo", label: "SEO technique" },
      { href: "/services/marketing-digital", label: "Marketing digital" },
    ],
    content: [
      { type: "p", text: "Vous avez un site rapide, un contenu de qualité, des balises impeccables, et pourtant vous plafonnez sur les requêtes concurrentielles. Il manque souvent le dernier étage de la fusée : l'autorité, qui se construit largement grâce aux backlinks. Un backlink, c'est un lien qu'un autre site fait vers le vôtre. Google l'interprète comme un vote de confiance. Mais tous les votes ne se valent pas, et une mauvaise stratégie peut faire plus de mal que de bien. Voici comment aborder le netlinking proprement." },
      { type: "h2", text: "Pourquoi les backlinks font l'autorité" },
      { type: "p", text: "À l'origine, Google s'est imposé grâce à une idée simple : une page vers laquelle beaucoup de sites de confiance pointent est probablement importante. Ce principe reste central. Chaque lien transmet un peu de crédibilité, ce qu'on appelle parfois le « jus de lien ». Deux sites au contenu équivalent ne se départageront souvent que par leur profil de liens : celui qui est cité par des sources reconnues l'emporte." },
      { type: "h2", text: "Qualité plutôt que quantité" },
      { type: "p", text: "Un seul lien depuis un média reconnu et thématiquement proche vaut davantage que des dizaines de liens depuis des sites sans rapport ou de faible qualité. Ce qui compte, ce sont plusieurs critères combinés." },
      { type: "ul", items: [
        "L'autorité du site source : est-il lui-même reconnu et bien positionné ?",
        "La pertinence thématique : parle-t-il d'un sujet cohérent avec votre activité ?",
        "Le contexte du lien : est-il inséré naturellement dans un contenu éditorial, ou perdu dans un pied de page ?",
        "La diversité : recevoir des liens de nombreux domaines différents est plus sain qu'un grand nombre de liens d'un seul site.",
      ]},
      { type: "h2", text: "Obtenir des liens propres : le contenu qui attire" },
      { type: "p", text: "La façon la plus durable d'obtenir des liens est de produire un contenu qu'on a naturellement envie de citer : étude originale, données chiffrées de votre secteur, guide de référence, outil gratuit. On parle de « linkable assets », des contenus conçus pour susciter des liens. C'est un travail de fond, mais les liens ainsi obtenus sont gratuits, pérennes et parfaitement légitimes aux yeux de Google." },
      { type: "h2", text: "Les relations presse et partenaires" },
      { type: "p", text: "Au-delà du contenu, plusieurs leviers relationnels permettent d'obtenir des liens de qualité, à condition de rester dans une logique éditoriale sincère." },
      { type: "ul", items: [
        "Relations presse : un communiqué ou une actualité repris par un média sectoriel apporte un lien fort et de la notoriété.",
        "Partenaires et fournisseurs : pages « ils nous font confiance », études de cas croisées, témoignages échangés.",
        "Interviews et tribunes : intervenir en tant qu'expert sur un blog ou un média de votre domaine.",
        "Sponsoring et événements locaux, qui donnent souvent lieu à une mention en ligne légitime.",
      ]},
      { type: "h2", text: "Les annuaires : oui, mais avec discernement" },
      { type: "p", text: "Les annuaires ont mauvaise réputation à cause des abus passés, mais quelques annuaires reconnus et thématiques restent utiles, notamment pour le SEO local et la cohérence de votre présence. La règle est de privilégier les annuaires sérieux, sélectifs et pertinents pour votre secteur, et d'éviter les inscriptions massives et automatiques sur des répertoires sans valeur." },
      { type: "cta", text: "Vous voulez une stratégie de netlinking saine, sans risque de pénalité ?", href: "/services/seo", label: "Parler de votre stratégie de liens" },
      { type: "h2", text: "Éviter les liens toxiques" },
      { type: "p", text: "C'est le revers du netlinking. Acheter des liens en masse, s'inscrire dans des fermes de liens ou multiplier les échanges artificiels expose à un déclassement, car Google sait détecter ces schémas. Un profil de liens qui grossit trop vite, uniquement avec des ancres exactement optimisées, est un signal suspect. Mieux vaut une progression lente et naturelle, avec des ancres variées (nom de marque, URL, expressions naturelles). Si des liens toxiques préexistent et échappent à votre contrôle, l'outil de désaveu de Google permet, en dernier recours, de demander à les ignorer." },
      { type: "h2", text: "Une stratégie qui s'inscrit dans la durée" },
      { type: "p", text: "Le netlinking n'est pas une opération ponctuelle mais un travail continu, adossé à votre production de contenu et à votre présence dans votre secteur. L'objectif n'est pas d'accumuler des liens pour eux-mêmes, mais de devenir une référence que l'on cite naturellement. C'est ce qui donne une autorité solide et durable, celle que les concurrents ne rattrapent pas en quelques semaines." },
    ],
    faq: [
      { q: "Qu'est-ce qu'un backlink en SEO ?", a: "Un backlink est un lien entrant : un lien qu'un autre site fait vers une page du vôtre. Google l'interprète comme un vote de confiance qui contribue à votre autorité. La valeur d'un backlink dépend de l'autorité du site source, de sa pertinence thématique et du contexte naturel dans lequel le lien est inséré." },
      { q: "Faut-il acheter des backlinks ?", a: "L'achat massif de liens est risqué : Google détecte ces schémas et peut déclasser le site concerné. Il vaut bien mieux obtenir des liens de façon naturelle, via un contenu qu'on a envie de citer, des relations presse, des partenaires et quelques annuaires sérieux. Ces liens sont gratuits, durables et légitimes." },
      { q: "Combien de backlinks faut-il pour bien se positionner ?", a: "Il n'y a pas de nombre magique. Ce qui compte n'est pas la quantité mais la qualité et la diversité : quelques liens depuis des sites reconnus et thématiquement proches valent mieux que des centaines de liens sans valeur. Le bon repère est le profil de liens des concurrents qui vous devancent sur vos requêtes cibles." },
      { q: "Comment savoir si un lien est toxique ?", a: "Un lien est problématique quand il provient d'un site de faible qualité, sans rapport avec votre activité, appartenant à une ferme de liens, ou obtenu de façon artificielle avec une ancre sur-optimisée. Une croissance très rapide de liens de ce type est un signal d'alerte. En dernier recours, l'outil de désaveu de Google permet de demander à ignorer ces liens." },
      { q: "Combien de temps avant de voir l'effet des backlinks ?", a: "Les effets du netlinking sont progressifs. Google doit découvrir les nouveaux liens, les évaluer et réévaluer votre autorité, ce qui prend généralement plusieurs semaines à quelques mois. C'est un travail de fond qui se cumule dans le temps, pas un levier à résultat immédiat." },
    ],
  },
  {
    slug: "rediger-article-optimise-seo",
    title: "Comment rédiger un article optimisé SEO (sans écrire pour les robots)",
    description:
      "Intention de recherche, structure Hn, mots-clés et sémantique, maillage interne, FAQ, longueur et EEAT : la méthode pour un article qui plaît à Google et aux lecteurs.",
    date: "2026-06-20",
    readingTime: "8 min",
    category: "SEO & Web",
    keywords: [
      "rédiger un article SEO",
      "rédaction web SEO",
      "article optimisé Google",
      "écrire pour le référencement",
    ],
    related: [
      { href: "/services/seo", label: "SEO technique" },
      { href: "/services/marketing-digital", label: "Marketing digital" },
    ],
    content: [
      { type: "p", text: "Écrire un article optimisé SEO ne veut pas dire répéter un mot-clé jusqu'à l'écœurement. Cette époque est révolue : Google comprend désormais le sens, le contexte et la satisfaction du lecteur. Un bon article SEO est d'abord un bon article, structuré pour répondre précisément à ce que cherche l'internaute. Voici la méthode que nous appliquons, du choix du sujet jusqu'à la publication." },
      { type: "h2", text: "Partir de l'intention de recherche" },
      { type: "p", text: "Avant d'écrire une ligne, on se demande ce que veut vraiment la personne qui tape la requête. Cherche-t-elle à comprendre, à comparer, à acheter, ou à trouver un site précis ? On distingue généralement l'intention informationnelle, commerciale et transactionnelle. Un article qui répond à la mauvaise intention ne se positionnera pas, même parfaitement rédigé. Le meilleur indicateur reste d'observer les pages déjà classées sur la requête : elles révèlent le format que Google juge pertinent." },
      { type: "h2", text: "Structurer avec les balises Hn" },
      { type: "p", text: "La structure aide à la fois le lecteur et Google à comprendre le plan de l'article. Une hiérarchie de titres claire est un fondamental." },
      { type: "ul", items: [
        "Un seul H1, qui reprend le sujet principal et contient le mot-clé de façon naturelle.",
        "Des H2 qui découpent l'article en grandes sections logiques, chacune répondant à une sous-question.",
        "Des H3 pour les points de détail à l'intérieur d'une section.",
        "Des paragraphes courts, des listes quand c'est pertinent, une lecture aérée et scannable.",
      ]},
      { type: "h2", text: "Mots-clés et champ sémantique" },
      { type: "p", text: "Le mot-clé principal doit apparaître aux endroits stratégiques (title, H1, introduction, une ou deux fois dans le corps) mais sans forcer. Ce qui compte davantage aujourd'hui, c'est la richesse sémantique : couvrir le sujet avec le vocabulaire naturel qui l'entoure, les termes connexes, les questions liées. Google évalue si votre page traite le sujet en profondeur, pas si elle répète une expression. Écrire pour être exhaustif et clair fait remonter les bons mots-clés d'eux-mêmes." },
      { type: "h2", text: "Le maillage interne" },
      { type: "p", text: "Un article ne vit pas isolé. Le relier à vos autres contenus pertinents, avec des ancres descriptives, guide le lecteur, répartit l'autorité entre vos pages et aide Google à comprendre l'organisation thématique de votre site. On lie vers les pages complémentaires (un guide plus détaillé, une page de service liée) et on veille à ce que les articles importants reçoivent aussi des liens depuis d'autres pages." },
      { type: "h2", text: "Ajouter une FAQ" },
      { type: "p", text: "Terminer un article par quelques questions-réponses reprend les interrogations réelles des internautes, celles qu'on voit dans « Autres questions posées » sur Google. C'est utile pour le lecteur, cela renforce la couverture sémantique, et bien balisé (données structurées FAQ), cela peut donner droit à un affichage enrichi dans les résultats. On rédige des réponses complètes mais concises, une par question." },
      { type: "cta", text: "Vous voulez des articles SEO qui se positionnent et convertissent, sans y passer vos soirées ?", href: "/services/marketing-digital", label: "Confier votre rédaction SEO" },
      { type: "h2", text: "Quelle longueur pour un article ?" },
      { type: "p", text: "Il n'existe pas de longueur idéale universelle. La bonne longueur est celle qui traite le sujet complètement, sans délayer. Certaines requêtes appellent une réponse courte et directe, d'autres un guide approfondi. Vouloir « faire du volume » pour atteindre un nombre de mots produit du contenu creux, que Google identifie et déclasse. Le repère utile est encore la concurrence en tête de page : elle indique le niveau de profondeur attendu." },
      { type: "h2", text: "Soigner l'EEAT" },
      { type: "p", text: "Google valorise les contenus qui montrent de l'expérience, de l'expertise, de l'autorité et de la fiabilité, ce qu'on résume par l'acronyme EEAT. Concrètement : signer l'article par un auteur identifiable et compétent, s'appuyer sur des faits vérifiables, citer des sources fiables, dater et mettre à jour le contenu. Ces signaux comptent particulièrement sur les sujets sensibles, mais renforcent la crédibilité de tout site. Un article qui inspire confiance retient mieux le lecteur, et cette satisfaction se traduit à terme dans le classement." },
    ],
    faq: [
      { q: "Combien de fois placer le mot-clé dans un article ?", a: "Il n'y a pas de nombre à viser. Le mot-clé principal doit apparaître aux endroits stratégiques (title, H1, introduction) puis naturellement dans le corps du texte. Bourrer un article de mots-clés est contre-productif : Google évalue la richesse sémantique et la satisfaction du lecteur, pas la répétition d'une expression." },
      { q: "Quelle longueur idéale pour un article SEO ?", a: "Celle qui couvre le sujet complètement, sans remplissage. Certaines requêtes appellent une réponse courte, d'autres un guide approfondi. Chercher à atteindre un nombre de mots produit du contenu creux, pénalisé par Google. Le meilleur repère est le niveau de profondeur des pages déjà classées en tête sur la requête visée." },
      { q: "Qu'est-ce que l'intention de recherche ?", a: "C'est ce que l'internaute veut vraiment obtenir en tapant sa requête : comprendre, comparer, acheter ou trouver un site précis. Un article doit répondre à la bonne intention pour se positionner. Observer les pages déjà classées sur la requête révèle le format et l'intention que Google juge pertinents." },
      { q: "Qu'est-ce que l'EEAT en SEO ?", a: "EEAT résume quatre signaux valorisés par Google : Expérience, Expertise, Autorité et Fiabilité. On les renforce en signant l'article par un auteur compétent, en s'appuyant sur des faits vérifiables, en citant des sources fiables et en tenant le contenu à jour. Ces signaux comptent surtout sur les sujets sensibles mais crédibilisent tout contenu." },
      { q: "Faut-il ajouter une FAQ à ses articles ?", a: "C'est recommandé lorsque des questions récurrentes entourent le sujet. Une FAQ répond aux interrogations réelles des internautes, enrichit la couverture sémantique et, avec un balisage en données structurées, peut donner droit à un affichage enrichi dans les résultats. Les réponses doivent être complètes mais concises, une par question." },
    ],
  },
  {
    slug: "seo-e-commerce-fiches-produits",
    title: "SEO e-commerce : optimiser fiches produits et catégories",
    description:
      "Architecture des catégories, fiches produit uniques, Product schema, gestion des facettes et de la duplication, images et avis : le SEO d'une boutique en ligne.",
    date: "2026-06-19",
    readingTime: "9 min",
    category: "SEO & Web",
    keywords: [
      "SEO e-commerce",
      "optimiser fiches produits",
      "référencement boutique en ligne",
      "SEO catégories produits",
    ],
    related: [
      { href: "/services/seo", label: "SEO technique" },
      { href: "/services/creation-site-web", label: "Création de site web" },
    ],
    content: [
      { type: "p", text: "Le SEO d'une boutique en ligne a ses propres règles. Là où un site vitrine compte quelques dizaines de pages, un e-commerce en aligne des milliers : catégories, sous-catégories, fiches produit, filtres. Cette masse est une chance (beaucoup de portes d'entrée dans Google) et un piège (contenu dupliqué, pages inutiles qui gaspillent le budget d'exploration). Voici les leviers qui comptent vraiment pour une boutique." },
      { type: "h2", text: "L'architecture des catégories : la fondation" },
      { type: "p", text: "Sur un e-commerce, ce sont souvent les pages de catégories, pas les fiches produit, qui captent le plus de trafic. Elles ciblent des requêtes larges et récurrentes comme « chaussures de running homme ». Une arborescence logique, où chaque catégorie correspond à une intention d'achat réelle, est donc la fondation du SEO d'une boutique." },
      { type: "ul", items: [
        "Une structure claire et peu profonde : un produit accessible en peu de clics depuis l'accueil.",
        "Des URLs propres et stables, qui reflètent la hiérarchie des catégories.",
        "Un texte de catégorie unique et utile en haut ou en bas de page, qui aide au positionnement sans gêner l'accès aux produits.",
        "Un maillage interne cohérent entre catégories, sous-catégories et produits phares.",
      ]},
      { type: "h2", text: "Des fiches produit uniques" },
      { type: "p", text: "Le piège numéro un de l'e-commerce est la description produit copiée du fabricant, identique sur des dizaines de sites concurrents. Google n'a aucune raison de vous mettre en avant plutôt qu'un autre. Investir dans des descriptions originales et utiles fait une réelle différence, surtout sur vos produits stratégiques." },
      { type: "ul", items: [
        "Une description rédigée pour l'acheteur : bénéfices concrets, cas d'usage, réponses aux hésitations.",
        "Un title et un H1 uniques, intégrant la marque, le modèle et un attribut différenciant.",
        "Des caractéristiques structurées et complètes, qui répondent aux questions avant l'achat.",
        "Priorité aux produits à fort volume de recherche et à bonne marge, qu'on ne peut pas tous traiter d'un coup.",
      ]},
      { type: "h2", text: "Le Product schema" },
      { type: "p", text: "Les données structurées de type Product permettent d'afficher des résultats enrichis : prix, disponibilité, note et avis directement dans Google. Cela améliore la visibilité et le taux de clic. On balise chaque fiche avec les informations réelles et à jour (prix, stock, avis vérifiés), car un balisage trompeur ou incohérent avec le contenu visible peut entraîner une sanction plutôt qu'un bénéfice." },
      { type: "h2", text: "Facettes et contenu dupliqué : le vrai casse-tête" },
      { type: "p", text: "Les filtres de navigation (couleur, taille, prix, marque) génèrent d'innombrables combinaisons d'URLs, souvent avec un contenu quasi identique. Laissées libres, ces pages diluent le budget d'exploration de Google et créent de la duplication massive. C'est l'un des chantiers techniques les plus importants d'un e-commerce." },
      { type: "ul", items: [
        "Décider quelles pages de filtres méritent d'être indexées (celles qui correspondent à une vraie demande de recherche) et lesquelles non.",
        "Utiliser les balises canonical pour désigner la version de référence d'une page filtrée.",
        "Bloquer via robots.txt ou noindex les combinaisons sans valeur SEO (tri, pagination infinie de filtres cumulés).",
        "Traiter proprement la pagination des listes de produits pour éviter la duplication et les pages orphelines.",
      ]},
      { type: "cta", text: "Vous voulez une boutique en ligne pensée pour se positionner et convertir ?", href: "/services/creation-site-web", label: "Voir notre offre e-commerce" },
      { type: "h2", text: "Les images produit" },
      { type: "p", text: "Sur un e-commerce, les images sont à la fois un enjeu de conversion et un levier SEO. Bien optimisées, elles remontent dans Google Images et allègent le temps de chargement, qui pèse sur le classement et sur le taux d'abandon. On compresse les visuels sans dégrader la qualité perçue, on utilise des formats modernes, on renseigne des balises alt descriptives, et on donne aux fichiers des noms parlants plutôt que des références internes illisibles." },
      { type: "h2", text: "Les avis produit" },
      { type: "p", text: "Les avis clients enrichissent naturellement la fiche avec du contenu unique et le vocabulaire réel des acheteurs, tout en rassurant et en faisant grimper la conversion. Associés au balisage Product, ils peuvent afficher des étoiles dans les résultats. On collecte des avis authentiques et vérifiés après achat : les faux avis, en plus d'être interdits, se retournent contre la confiance et exposent à des sanctions." },
      { type: "h2", text: "Une démarche à prioriser" },
      { type: "p", text: "Sur une boutique de plusieurs milliers de références, on ne peut pas tout optimiser en même temps. On commence par régler les problèmes techniques transverses (facettes, duplication, exploration), puis on renforce les catégories et les fiches des produits les plus stratégiques. C'est cette combinaison de rigueur technique et de contenu ciblé qui fait décoller le trafic organique d'un e-commerce." },
    ],
    faq: [
      { q: "Faut-il réécrire toutes les fiches produit d'une boutique ?", a: "Idéalement oui, mais c'est rarement possible d'un coup sur des milliers de références. On commence par les produits stratégiques : ceux à fort volume de recherche et à bonne marge. Réécrire ces fiches avec des descriptions originales et utiles a bien plus d'impact que de traiter en masse des produits marginaux." },
      { q: "Pourquoi ma boutique génère-t-elle des milliers de pages inutiles ?", a: "Le plus souvent à cause des filtres de navigation (couleur, taille, prix) qui créent d'innombrables combinaisons d'URLs au contenu quasi identique. Laissées libres, ces pages diluent le budget d'exploration et créent de la duplication. On les maîtrise avec des balises canonical, des noindex ciblés et des règles dans le robots.txt." },
      { q: "Les catégories ou les fiches produit rapportent-elles plus de trafic ?", a: "Souvent les catégories, car elles ciblent des requêtes larges et récurrentes que beaucoup d'internautes tapent. Les fiches produit captent des requêtes plus précises et à forte intention d'achat. Les deux sont complémentaires, mais l'architecture des catégories est la fondation du SEO d'un e-commerce." },
      { q: "À quoi sert le Product schema ?", a: "Le balisage de données structurées Product permet à Google d'afficher des informations enrichies dans les résultats : prix, disponibilité, note et avis. Cela améliore la visibilité et le taux de clic. Les informations balisées doivent être réelles, à jour et cohérentes avec le contenu visible, sous peine de sanction." },
      { q: "Les avis produit aident-ils vraiment le SEO ?", a: "Oui : ils ajoutent du contenu unique et le vocabulaire réel des acheteurs sur chaque fiche, rassurent et améliorent la conversion. Associés au balisage Product, ils peuvent afficher des étoiles dans les résultats. À condition d'être authentiques et vérifiés : les faux avis sont interdits et se retournent contre la boutique." },
    ],
  },
  {
    slug: "donnees-structurees-schema-org-seo",
    title: "Données structurées et Schema.org : le guide pour les rich results",
    description:
      "Ce que sont les données structurées, les types utiles (FAQ, Product, Article, Breadcrumb, LocalBusiness), les rich results qu'elles débloquent et comment les tester.",
    date: "2026-06-18",
    readingTime: "8 min",
    category: "SEO & Web",
    keywords: [
      "données structurées SEO",
      "Schema.org",
      "rich results Google",
      "balisage JSON-LD",
    ],
    related: [
      { href: "/services/seo", label: "SEO technique" },
      { href: "/blog/comment-faire-audit-seo", label: "Comment faire un audit SEO" },
    ],
    content: [
      { type: "p", text: "Vous avez sûrement remarqué que certains résultats Google se démarquent : des étoiles d'avis, une FAQ dépliable, un prix, un fil d'ariane, une image de recette. Ce ne sont pas des privilèges accordés au hasard : ils reposent sur les données structurées. Bien utilisées, elles rendent vos pages plus visibles et plus cliquées, sans changer une ligne de votre contenu visible. Voici ce qu'il faut comprendre et comment les mettre en place proprement." },
      { type: "h2", text: "Qu'est-ce que les données structurées ?" },
      { type: "p", text: "Les données structurées sont un balisage ajouté au code de vos pages pour décrire leur contenu dans un langage que Google comprend sans ambiguïté. Elles s'appuient sur un vocabulaire standard, Schema.org, partagé par les grands moteurs. Là où un humain lit « 4,7 étoiles, 128 avis », le moteur, lui, a besoin qu'on lui dise explicitement : ceci est une note, voici sa valeur, voici le nombre d'avis. C'est exactement le rôle de ce balisage." },
      { type: "h2", text: "JSON-LD : le format recommandé" },
      { type: "p", text: "Il existe plusieurs façons d'implémenter Schema.org, mais Google recommande le format JSON-LD. Son avantage : c'est un bloc de code indépendant, inséré dans la page, qui n'interfère pas avec le HTML visible ni avec le design. On peut l'ajouter, le modifier ou le retirer sans toucher au contenu, ce qui le rend simple à maintenir, y compris généré dynamiquement à partir de vos données." },
      { type: "h2", text: "Les types de balisage les plus utiles" },
      { type: "p", text: "Schema.org propose des centaines de types, mais quelques-uns couvrent l'essentiel des besoins d'un site professionnel. On choisit le balisage en fonction de la nature réelle de la page." },
      { type: "ul", items: [
        "FAQ : pour une page ou un article comportant de vraies questions-réponses, susceptible d'afficher une FAQ dépliable.",
        "Product : pour une fiche produit, avec prix, disponibilité et avis, afin d'obtenir des résultats enrichis marchands.",
        "Article : pour un article de blog ou une actualité, avec auteur, date et image, utile notamment pour l'actualité.",
        "Breadcrumb : pour afficher un fil d'ariane clair dans les résultats, à la place de l'URL brute.",
        "LocalBusiness : pour un établissement local, avec adresse, horaires et coordonnées, en appui du SEO local.",
      ]},
      { type: "h2", text: "Ce que débloquent les rich results" },
      { type: "p", text: "Les rich results (ou résultats enrichis) sont l'affichage amélioré que Google peut accorder à une page correctement balisée : étoiles d'avis, prix, FAQ dépliable, fil d'ariane, image en vedette. L'intérêt est double : votre résultat occupe plus d'espace et attire davantage l'œil, ce qui augmente le taux de clic à position égale. Il faut toutefois garder une nuance importante en tête." },
      { type: "h2", text: "Une nuance : baliser n'améliore pas directement le classement" },
      { type: "p", text: "C'est une confusion fréquente. Les données structurées ne sont pas, en elles-mêmes, un facteur de classement direct : baliser une page ne la fait pas mécaniquement monter dans les résultats. Leur bénéfice est indirect mais réel : elles rendent la page éligible aux rich results, qui améliorent la visibilité et le taux de clic, lequel traduit une meilleure satisfaction. Autrement dit, on ne balise pas pour tromper Google, mais pour l'aider à présenter au mieux un contenu déjà pertinent." },
      { type: "cta", text: "Vous voulez déployer des données structurées propres et éligibles aux rich results ?", href: "/services/seo", label: "Voir notre offre SEO technique" },
      { type: "h2", text: "Les règles à respecter" },
      { type: "p", text: "Google fixe des consignes strictes, car les données structurées ont été détournées par le passé. Les enfreindre expose à perdre l'affichage enrichi, voire à une action manuelle." },
      { type: "ul", items: [
        "Le balisage doit décrire un contenu réellement présent et visible sur la page, pas des informations cachées à l'internaute.",
        "Les informations balisées doivent être exactes et à jour : un prix ou un stock erroné peut être sanctionné.",
        "On ne balise pas de faux avis ni des notes qui n'existent pas sur la page.",
        "Chaque type a ses propriétés obligatoires et recommandées : les respecter conditionne l'éligibilité au rich result.",
      ]},
      { type: "h2", text: "Tester et surveiller son balisage" },
      { type: "p", text: "Une fois le balisage en place, on le vérifie avant tout avec l'outil de test des résultats enrichis de Google, qui indique les erreurs et les avertissements type par type. Sur la durée, le rapport dédié dans Search Console signale les problèmes détectés en production et confirme les pages éligibles. Ce contrôle est indispensable : un balisage invalide ou incomplet ne produit tout simplement aucun rich result, et un balisage non conforme aux consignes peut être pénalisé. Testé et maintenu, en revanche, il donne à vos pages un avantage visible et durable dans les résultats." },
    ],
    faq: [
      { q: "Les données structurées améliorent-elles le classement Google ?", a: "Pas directement : baliser une page ne la fait pas mécaniquement monter dans les résultats. Leur bénéfice est indirect mais réel : elles rendent la page éligible aux rich results (étoiles, FAQ, prix), qui améliorent la visibilité et le taux de clic. On balise donc pour mieux présenter un contenu déjà pertinent, pas pour tromper le moteur." },
      { q: "Quel format utiliser pour Schema.org ?", a: "Google recommande le format JSON-LD. C'est un bloc de code indépendant inséré dans la page, qui n'interfère pas avec le HTML visible ni avec le design. On peut l'ajouter, le modifier ou le générer dynamiquement sans toucher au contenu, ce qui le rend simple à maintenir." },
      { q: "Quels types de données structurées sont les plus utiles ?", a: "Pour un site professionnel, les plus utiles sont FAQ (questions-réponses), Product (fiches produit avec prix et avis), Article (blog et actualités), Breadcrumb (fil d'ariane) et LocalBusiness (établissement local). On choisit le type selon la nature réelle de la page, et on respecte ses propriétés obligatoires." },
      { q: "Comment tester mes données structurées ?", a: "On utilise d'abord l'outil de test des résultats enrichis de Google, qui signale erreurs et avertissements pour chaque type. Ensuite, le rapport dédié dans Search Console remonte les problèmes détectés en production et confirme les pages éligibles. Ce contrôle est indispensable, car un balisage invalide ne produit aucun rich result." },
      { q: "Peut-on être pénalisé à cause des données structurées ?", a: "Oui, si le balisage ne respecte pas les consignes de Google : décrire un contenu absent ou caché, baliser de faux avis, ou afficher des informations inexactes comme un prix erroné. Ces manquements peuvent faire perdre l'affichage enrichi, voire déclencher une action manuelle. Un balisage honnête et à jour ne présente aucun risque." },
    ],
  },
];
