import type { Post } from "./posts";

// Cluster SEO « facturation électronique » — spokes gratuits (vague 1, quick wins).
// Voir docs/seo/cluster-facturation-electronique.md. Chaque article renvoie au
// pilier /guides/facturation-electronique-obligatoire et à l'offre de délégation.
// YMYL : dates/seuils vérifiés au 2026-09-02 — revérifier avant toute évolution.
export const POSTS_FACTURATION: Post[] = [
  {
    slug: "facturation-electronique-association",
    title: "Facturation électronique et associations : qui est concerné ? (2026)",
    description:
      "Les associations sont-elles concernées par la facturation électronique obligatoire ? Le point clair selon que votre association est assujettie ou non à la TVA, avec les dates.",
    date: "2026-09-02",
    readingTime: "7 min",
    category: "Facturation électronique",
    keywords: [
      "facturation électronique association",
      "facturation électronique association 1901",
      "facturation électronique pour les associations",
      "association assujettie TVA facture électronique",
    ],
    related: [
      { href: "/guides/facturation-electronique-obligatoire", label: "Le guide complet de la facturation électronique" },
      { href: "/services/automatisation", label: "Déléguer la mise en conformité" },
    ],
    content: [
      { type: "p", text: "« Est-ce que mon association est concernée par la facturation électronique ? » La réponse n'est ni un oui ni un non : elle dépend d'un seul critère, l'assujettissement à la TVA. Une association purement non lucrative et une association qui exerce une activité commerciale assujettie ne sont pas logées à la même enseigne. Voici comment savoir précisément où vous vous situez." },
      { type: "h2", text: "Le critère qui décide de tout : êtes-vous assujetti à la TVA ?" },
      { type: "p", text: "La réforme vise les opérations entre professionnels (B2B) assujettis à la TVA et établis en France. Le statut associatif (loi 1901) ne change rien en soi : ce qui compte, c'est la nature de votre activité. Une association qui facture des prestations ou des ventes soumises à la TVA est, pour ces opérations, un assujetti comme un autre — donc concernée. Une association strictement non lucrative, exonérée de TVA sur l'ensemble de ses activités, n'émet pas de factures B2B assujetties." },
      { type: "ul", items: [
        "Association avec activité commerciale assujettie à la TVA (billetterie taxée, prestations, ventes) : concernée par l'émission ET la réception de factures électroniques.",
        "Association non assujettie / exonérée (subventions, dons, cotisations) : pas d'émission de facture B2B assujettie, mais elle doit tout de même pouvoir recevoir une facture électronique de ses fournisseurs.",
        "Association « mixte » (secteur lucratif isolé) : concernée pour la partie assujettie. Le périmètre exact se cale avec votre expert-comptable.",
      ]},
      { type: "h2", text: "Les dates qui vous concernent" },
      { type: "p", text: "Il faut distinguer deux obligations qui n'ont pas la même date — c'est la confusion la plus fréquente." },
      { type: "ul", items: [
        "Réception des factures électroniques : obligatoire pour toutes les structures dès le 1er septembre 2026. Même une petite association doit être en capacité de recevoir une facture au format électronique.",
        "Émission des factures électroniques : selon la taille. Grandes entreprises et ETI depuis le 1er septembre 2026 ; PME, TPE et micro-structures (la très grande majorité des associations concernées) à partir du 1er septembre 2027.",
      ]},
      { type: "p", text: "Autrement dit : si votre association a une activité assujettie mais reste de petite taille, vous devez pouvoir recevoir dès 2026, et émettre en format électronique à partir de 2027." },
      { type: "h2", text: "Concrètement, que doit faire une association ?" },
      { type: "ul", items: [
        "Déterminer votre situation TVA activité par activité (le cœur du sujet).",
        "Choisir une Plateforme Agréée (PA) : les factures transiteront par elle, en format structuré (Factur-X, UBL).",
        "Vérifier vos mentions obligatoires, dont le numéro SIREN — une association qui facture doit être immatriculée (SIRET).",
        "Anticiper la réception dès 2026, même si vous n'émettez pas encore.",
      ]},
      { type: "cta", text: "Vous voulez savoir exactement si — et quand — votre association est concernée ?", href: "/guides/facturation-electronique-obligatoire", label: "Lire le guide complet de la facturation électronique" },
      { type: "p", text: "Le bon réflexe : ne pas raisonner « association / pas association », mais « assujetti à la TVA / pas assujetti ». C'est ce curseur qui décide de vos obligations, et il mérite d'être tranché noir sur blanc avec votre expert-comptable avant l'échéance." },
    ],
    faq: [
      { q: "Une association loi 1901 est-elle concernée par la facturation électronique ?", a: "Cela dépend de son assujettissement à la TVA. Une association qui exerce une activité commerciale assujettie est concernée (émission et réception) pour ces opérations. Une association non lucrative exonérée de TVA n'émet pas de facture B2B assujettie, mais doit tout de même pouvoir recevoir des factures électroniques de ses fournisseurs dès le 1er septembre 2026." },
      { q: "À partir de quand une association doit-elle émettre des factures électroniques ?", a: "Pour la grande majorité des associations concernées (petites structures), l'obligation d'émission arrive au 1er septembre 2027. L'obligation de réception, elle, s'applique à toutes dès le 1er septembre 2026." },
      { q: "Une association qui ne facture rien est-elle concernée ?", a: "Elle n'a pas de factures à émettre, mais elle reste tenue de pouvoir recevoir une facture électronique de ses fournisseurs assujettis. Une adresse et une plateforme de réception sont donc à prévoir." },
      { q: "Faut-il un logiciel payant pour une association ?", a: "Pas nécessairement : la facture doit transiter par une Plateforme Agréée, mais plusieurs offres existent, y compris à faible coût. Le choix dépend de votre volume et de vos outils actuels — c'est justement ce qu'on cadre en accompagnement." },
    ],
  },

  {
    slug: "facturation-electronique-calendrier-dates",
    title: "Facturation électronique : le calendrier des dates (2026-2027)",
    description:
      "Toutes les dates de la facturation électronique obligatoire : réception au 1er septembre 2026, émission en 2026 puis 2027 selon la taille. Le calendrier clair, à jour.",
    date: "2026-09-02",
    readingTime: "6 min",
    category: "Facturation électronique",
    keywords: [
      "facturation électronique calendrier",
      "facturation électronique date",
      "facturation électronique 2027",
      "facturation électronique à partir de quand",
      "facturation électronique septembre 2026",
    ],
    related: [
      { href: "/guides/facturation-electronique-obligatoire", label: "Le guide complet de la facturation électronique" },
      { href: "/services/automatisation", label: "Déléguer la mise en conformité" },
    ],
    content: [
      { type: "p", text: "Le calendrier de la facturation électronique a été plusieurs fois modifié, ce qui a semé la confusion. Voici les dates réellement en vigueur, et surtout la distinction qui change tout : recevoir une facture électronique et en émettre une ne tombent pas à la même date." },
      { type: "h2", text: "Les deux dates à retenir" },
      { type: "ul", items: [
        "1er septembre 2026 — Réception : toutes les entreprises et structures assujetties doivent être en capacité de recevoir des factures électroniques. Aucune exception de taille.",
        "1er septembre 2026 — Émission (grandes entreprises et ETI) : ces structures doivent aussi émettre au format électronique.",
        "1er septembre 2027 — Émission (PME, TPE, micro-entreprises, indépendants) : le reste des entreprises bascule à cette date pour l'émission.",
      ]},
      { type: "p", text: "En clair : au 1er septembre 2026, tout le monde doit pouvoir recevoir ; en 2026 les grandes entreprises et ETI émettent déjà, et en 2027 c'est au tour des plus petites structures d'émettre." },
      { type: "h2", text: "Pourquoi autant de confusion sur les dates ?" },
      { type: "p", text: "Le dispositif devait initialement démarrer en 2024, avant d'être reporté puis réaménagé. Beaucoup de contenus en ligne citent encore d'anciennes échéances (2024, 2025) qui ne sont plus d'actualité. D'où l'importance de vérifier la date de mise à jour d'un article — et de recouper avec la DGFiP, seule source officielle." },
      { type: "h2", text: "Quelle est MA date, concrètement ?" },
      { type: "p", text: "Posez-vous deux questions simples." },
      { type: "ul", items: [
        "Suis-je assujetti à la TVA et établi en France ? Si oui, je suis dans le périmètre.",
        "Quelle est ma taille ? Grande entreprise ou ETI → j'émets dès le 1er septembre 2026. PME, TPE, micro, indépendant → je reçois dès 2026 et j'émets à partir du 1er septembre 2027.",
      ]},
      { type: "cta", text: "Un doute sur votre échéance exacte ?", href: "/guides/facturation-electronique-obligatoire", label: "Voir le guide complet et déterminer votre date" },
      { type: "p", text: "Le piège à éviter : croire qu'on a « jusqu'en 2027 » et ne rien faire. La réception s'impose à tous dès 2026, et choisir sa plateforme, adapter ses mentions et tester ses formats prend du temps. Mieux vaut cadrer le chantier maintenant que dans l'urgence de l'échéance." },
    ],
    faq: [
      { q: "À partir de quand la facturation électronique est-elle obligatoire ?", a: "La réception de factures électroniques est obligatoire pour toutes les entreprises assujetties dès le 1er septembre 2026. L'émission est obligatoire au 1er septembre 2026 pour les grandes entreprises et ETI, et au 1er septembre 2027 pour les PME, TPE, micro-entreprises et indépendants." },
      { q: "La facturation électronique a-t-elle été reportée ?", a: "Le calendrier initial (2024) a été reporté et réaménagé. Les dates en vigueur sont désormais septembre 2026 (réception pour tous + émission grandes entreprises/ETI) et septembre 2027 (émission pour les PME et plus petites structures). Vérifiez toujours auprès de la DGFiP, car le dispositif peut encore évoluer." },
      { q: "Quelle différence entre l'obligation de réception et d'émission ?", a: "La réception (pouvoir recevoir une facture électronique d'un fournisseur) s'impose à toutes les entreprises dès le 1er septembre 2026. L'émission (produire et envoyer vos propres factures au format électronique) suit un calendrier par taille : 2026 pour les grandes entreprises et ETI, 2027 pour les autres." },
      { q: "Que se passe-t-il si je ne suis pas prêt à temps ?", a: "Au-delà de l'échéance, ne pas pouvoir recevoir ou émettre des factures conformes expose à des difficultés opérationnelles (factures rejetées) et à d'éventuelles sanctions. L'anticipation — choix de la plateforme et mise à jour des mentions — est le seul vrai moyen d'éviter l'urgence." },
    ],
  },

  {
    slug: "facturation-electronique-sci-lmnp",
    title: "Facturation électronique : SCI et LMNP sont-ils concernés ? (2026)",
    description:
      "SCI, LMNP, loueur en meublé : êtes-vous concerné par la facturation électronique obligatoire ? La règle dépend de la TVA. Le point clair selon votre situation.",
    date: "2026-09-02",
    readingTime: "7 min",
    category: "Facturation électronique",
    keywords: [
      "facturation électronique sci",
      "facturation électronique sci familiale",
      "facturation électronique lmnp",
      "facturation électronique location meublée",
      "facturation électronique bailleur",
    ],
    related: [
      { href: "/guides/facturation-electronique-obligatoire", label: "Le guide complet de la facturation électronique" },
      { href: "/services/automatisation", label: "Déléguer la mise en conformité" },
    ],
    content: [
      { type: "p", text: "SCI, LMNP, loueur en meublé : la question revient sans cesse, et la réponse tient à un seul critère — la TVA. Une location nue d'habitation et une location de locaux commerciaux avec TVA ne relèvent pas du même régime. Voici comment situer votre SCI ou votre activité de loueur." },
      { type: "h2", text: "La règle : concerné si vous êtes assujetti à la TVA" },
      { type: "p", text: "La réforme cible les opérations B2B entre assujettis à la TVA établis en France. Une grande partie des activités immobilières patrimoniales échappe donc à l'émission : les locations d'habitation nues sont exonérées de TVA. Mais dès qu'une TVA s'applique — sur option ou par nature — vous entrez dans le périmètre pour ces opérations." },
      { type: "ul", items: [
        "SCI à l'IR qui loue des logements nus (exonérés de TVA) : pas d'émission de facture B2B assujettie. Vous restez toutefois tenu de pouvoir recevoir une facture électronique de vos prestataires (syndic, travaux…).",
        "SCI louant des locaux professionnels/commerciaux avec TVA (de plein droit ou sur option) : concernée pour ces loyers.",
        "LMNP / loueur en meublé : la location meublée classique relève de règles TVA spécifiques (souvent exonérée) ; en revanche, une activité para-hôtelière (petit-déjeuner, ménage, accueil…) est assujettie à la TVA — donc concernée.",
      ]},
      { type: "p", text: "Le mot-clé, encore une fois, n'est pas « SCI » ou « LMNP » mais « assujetti à la TVA ». C'est ce point que votre comptable doit trancher pour votre cas précis." },
      { type: "h2", text: "Les dates selon votre situation" },
      { type: "ul", items: [
        "Réception : obligatoire pour toutes les structures assujetties dès le 1er septembre 2026.",
        "Émission : 1er septembre 2026 pour les grandes structures (rare en immobilier patrimonial), 1er septembre 2027 pour les PME, TPE et petites structures — le cas de la quasi-totalité des SCI et LMNP concernés.",
      ]},
      { type: "h2", text: "Que faire si votre SCI est concernée ?" },
      { type: "ul", items: [
        "Confirmer votre régime TVA activité par activité (le point décisif).",
        "Si assujetti : prévoir une Plateforme Agréée pour émettre en format structuré (Factur-X, UBL) à l'échéance.",
        "Vérifier vos mentions obligatoires, dont le SIREN de la SCI.",
        "Même non assujetti : organiser la réception des factures électroniques de vos fournisseurs dès 2026.",
      ]},
      { type: "cta", text: "SCI, LMNP : vérifiez précisément si vous êtes concerné et à quelle date.", href: "/guides/facturation-electronique-obligatoire", label: "Lire le guide complet de la facturation électronique" },
      { type: "p", text: "À retenir : beaucoup de SCI patrimoniales à l'IR ne seront pas tenues d'émettre, mais toutes doivent pouvoir recevoir. Ne partez pas du principe que « l'immobilier n'est pas concerné » : faites vérifier votre statut TVA, c'est lui qui décide." },
    ],
    faq: [
      { q: "Une SCI est-elle concernée par la facturation électronique ?", a: "Cela dépend de son assujettissement à la TVA. Une SCI qui loue des logements nus exonérés de TVA n'émet pas de facture B2B assujettie, mais doit pouvoir recevoir des factures électroniques dès le 1er septembre 2026. Une SCI qui loue des locaux professionnels avec TVA est concernée par l'émission (à partir de 2027 pour les petites structures)." },
      { q: "Un LMNP doit-il émettre des factures électroniques ?", a: "La location meublée classique relève de règles TVA spécifiques, souvent exonérées. En revanche, une activité para-hôtelière assujettie à la TVA entre dans le périmètre. C'est le régime TVA de votre activité, pas le statut LMNP en lui-même, qui détermine l'obligation." },
      { q: "Une SCI familiale à l'IR est-elle concernée ?", a: "Si elle loue uniquement des biens d'habitation nus, exonérés de TVA, elle n'a pas de factures B2B assujetties à émettre. Elle doit néanmoins être en mesure de recevoir des factures électroniques de ses prestataires à compter du 1er septembre 2026." },
      { q: "Comment savoir si ma SCI est assujettie à la TVA ?", a: "Cela dépend de la nature des biens loués et d'éventuelles options fiscales exercées. Les locaux commerciaux et professionnels peuvent être soumis à la TVA de plein droit ou sur option, contrairement aux logements nus. Le plus sûr est de faire confirmer votre situation par votre expert-comptable." },
    ],
  },

  {
    slug: "facturation-electronique-auto-entrepreneur",
    title: "Facturation électronique et auto-entrepreneurs : concerné même sans TVA (2026)",
    description:
      "Auto-entrepreneur en franchise de TVA : êtes-vous concerné par la facturation électronique obligatoire ? Oui — voici pourquoi, à quelle date, et ce qu'il faut faire.",
    date: "2026-09-02",
    readingTime: "7 min",
    category: "Facturation électronique",
    keywords: [
      "facturation électronique auto entrepreneur",
      "facturation électronique micro entrepreneur",
      "facturation électronique auto entrepreneur sans tva",
      "facturation électronique 2026 auto entrepreneur",
      "facturation électronique indépendant",
    ],
    related: [
      { href: "/guides/facturation-electronique-obligatoire", label: "Le guide complet de la facturation électronique" },
      { href: "/outils/facturation-electronique-simulateur", label: "Simulateur : suis-je concerné et à quelle date ?" },
    ],
    content: [
      { type: "p", text: "« Je suis en franchise de TVA, donc je ne suis pas concerné. » C'est la phrase qu'on entend le plus chez les auto-entrepreneurs — et c'est faux. La facturation électronique obligatoire s'applique bien aux micro-entreprises, y compris à celles qui ne facturent pas la TVA. Voici pourquoi, et surtout à partir de quand." },
      { type: "h2", text: "Franchise en base de TVA ≠ hors du dispositif" },
      { type: "p", text: "La confusion vient d'un raccourci : ne pas facturer la TVA ferait sortir du périmètre. En réalité, la réforme vise les assujettis à la TVA établis en France — et un auto-entrepreneur en franchise en base reste un assujetti, simplement non redevable de la taxe. Vos opérations avec d'autres professionnels (B2B) entrent donc dans le champ de la facture électronique." },
      { type: "ul", items: [
        "Auto-entrepreneur en franchise de TVA : concerné (réception, puis émission).",
        "Auto-entrepreneur qui facture la TVA (au-dessus des seuils) : concerné également.",
        "Le fait de ne pas mentionner de TVA sur vos factures ne vous exonère pas de l'obligation de format.",
      ]},
      { type: "h2", text: "Vos dates : recevoir en 2026, émettre en 2027" },
      { type: "ul", items: [
        "Réception : dès le 1er septembre 2026, vous devez être en capacité de recevoir une facture électronique (d'un fournisseur, d'un prestataire).",
        "Émission : en tant que micro-entreprise, vous devez émettre vos factures au format électronique à partir du 1er septembre 2027.",
      ]},
      { type: "p", text: "Autrement dit, vous avez un peu plus de temps pour l'émission, mais la réception vous concerne dès 2026 — et rien n'empêche de tout mettre en place d'un coup pour ne pas y revenir." },
      { type: "h2", text: "Ce qui change concrètement pour vous" },
      { type: "p", text: "Le PDF que vous envoyez aujourd'hui par e-mail (ou le document Word/Excel) ne suffira plus pour vos clients professionnels. La facture devra être produite dans un format structuré (Factur-X, par exemple) et transiter par une Plateforme Agréée. En pratique, cela passe par un outil de facturation ou une plateforme qui s'en charge pour vous." },
      { type: "cta", text: "Auto-entrepreneur : vérifiez votre date exacte en 30 secondes.", href: "/outils/facturation-electronique-simulateur", label: "Utiliser le simulateur" },
      { type: "h2", text: "Le cas des ventes aux particuliers" },
      { type: "p", text: "Si vous vendez surtout à des particuliers (B2C), ces ventes ne passent pas par la facture électronique mais par l'e-reporting : la transmission des données de transaction à l'administration. Beaucoup d'auto-entrepreneurs sont concernés par les deux volets selon leur clientèle. C'est un point à clarifier tôt pour choisir le bon outil." },
      { type: "p", text: "À retenir : ne partez pas du principe que la franchise de TVA vous protège. Anticipez la réception dès 2026, préparez l'émission pour 2027, et choisissez une solution qui gère à la fois la facture électronique B2B et l'e-reporting B2C si votre activité le demande." },
    ],
    faq: [
      { q: "Un auto-entrepreneur en franchise de TVA est-il concerné par la facturation électronique ?", a: "Oui. La franchise en base de TVA ne fait pas sortir du dispositif : un auto-entrepreneur reste un assujetti (non redevable), et ses opérations B2B entrent dans le champ de la facture électronique. Il doit pouvoir recevoir dès le 1er septembre 2026 et émettre au format électronique à partir du 1er septembre 2027." },
      { q: "À partir de quand un auto-entrepreneur doit-il émettre des factures électroniques ?", a: "À partir du 1er septembre 2027 pour l'émission (comme les autres TPE et micro-entreprises). L'obligation de réception, elle, s'applique dès le 1er septembre 2026." },
      { q: "Puis-je continuer à envoyer un simple PDF par e-mail ?", a: "Non, pas pour vos clients professionnels une fois l'obligation d'émission en vigueur. La facture devra être dans un format structuré (comme Factur-X) et transiter par une Plateforme Agréée, ce qu'un PDF envoyé manuellement par e-mail ne permet pas." },
      { q: "Et si je vends uniquement à des particuliers ?", a: "Les ventes aux particuliers (B2C) ne relèvent pas de la facture électronique mais de l'e-reporting : vous transmettez les données de vos transactions à l'administration. Selon votre clientèle, vous pouvez être concerné par la facture électronique B2B et par l'e-reporting B2C." },
    ],
  },

  {
    slug: "facturation-electronique-gratuite-logiciel",
    title: "Facturation électronique gratuite : quelles solutions en 2026 ?",
    description:
      "Peut-on faire sa facturation électronique gratuitement ? Ce qui est réellement gratuit, le mythe du portail public, et les pièges des offres « 0 € » à connaître.",
    date: "2026-09-02",
    readingTime: "6 min",
    category: "Facturation électronique",
    keywords: [
      "facturation électronique gratuite",
      "facturation électronique logiciel gratuit",
      "facturation électronique plateforme gratuite",
      "facturation électronique 2026 gratuit",
      "logiciel facturation électronique",
    ],
    related: [
      { href: "/guides/facturation-electronique-obligatoire", label: "Le guide complet de la facturation électronique" },
      { href: "/blog/plateforme-agreee-facturation-electronique", label: "Comment choisir sa plateforme agréée" },
    ],
    content: [
      { type: "p", text: "« Est-ce que je peux me mettre en conformité gratuitement ? » Oui, c'est possible pour beaucoup de petites structures — mais le mot « gratuit » cache plusieurs réalités qu'il vaut mieux connaître avant de s'engager. Faisons le tri." },
      { type: "h2", text: "Le mythe du portail public gratuit" },
      { type: "p", text: "Le projet initial prévoyait un service public de facturation gratuit (le PPF) permettant à toute entreprise d'émettre ses factures sans coût. Ce service d'émission gratuit a été abandonné dans la version réaménagée de la réforme : le PPF conserve un rôle d'annuaire et de concentrateur de données, mais n'est plus la plateforme gratuite d'émission attendue. Résultat : chaque entreprise doit choisir une Plateforme Agréée (PA), et c'est là que se pose la question du coût." },
      { type: "h2", text: "Où trouver du réellement gratuit" },
      { type: "ul", items: [
        "Les offres d'entrée de gamme de certaines Plateformes Agréées, avec un palier gratuit pour de faibles volumes.",
        "Des outils de facturation qui intègrent la conformité dans leur offre existante (parfois inclus dans un abonnement que vous payez déjà).",
        "Certaines banques et logiciels de comptabilité qui annoncent une prise en charge dans leur service.",
      ]},
      { type: "p", text: "Pour un auto-entrepreneur ou une petite association avec peu de factures, une offre gratuite ou à faible coût peut parfaitement suffire. Le gratuit n'est pas un piège en soi — encore faut-il lire ce qu'il y a derrière." },
      { type: "h2", text: "Les pièges des offres « 0 € »" },
      { type: "ul", items: [
        "Les limites de volume : gratuit jusqu'à X factures, puis facturation au-delà.",
        "Les fonctions bridées : émission oui, mais réception, e-reporting ou archivage en option payante.",
        "La dépendance : une solution gratuite mais fermée peut compliquer une migration future.",
        "Le vrai coût caché : le temps passé à paramétrer un outil inadapté vaut souvent plus cher que l'abonnement d'un outil qui vous correspond.",
      ]},
      { type: "cta", text: "Un doute sur ce qui est vraiment inclus dans une offre gratuite ?", href: "/guides/facturation-electronique-obligatoire", label: "Lire le guide complet de la facturation électronique" },
      { type: "h2", text: "Ce qu'il faut vérifier avant de choisir" },
      { type: "p", text: "Avant de retenir une solution « gratuite », posez quatre questions : couvre-t-elle l'émission ET la réception ? Gère-t-elle l'e-reporting si vous vendez aux particuliers ? Le format est-il conforme (Factur-X, UBL) ? Et jusqu'à quel volume reste-t-elle vraiment gratuite ? Si les réponses sont bonnes pour votre activité, foncez. Sinon, un petit budget bien placé vous évitera de tout refaire." },
    ],
    faq: [
      { q: "Peut-on faire sa facturation électronique gratuitement ?", a: "Oui pour de nombreuses petites structures : certaines Plateformes Agréées proposent un palier gratuit pour de faibles volumes, et des outils de facturation intègrent la conformité dans une offre existante. En revanche, le service public d'émission gratuit initialement prévu (PPF) a été abandonné dans la version réaménagée de la réforme." },
      { q: "Le portail public de facturation est-il gratuit ?", a: "Le Portail Public de Facturation (PPF) conserve un rôle d'annuaire et de concentrateur de données, mais il n'assure plus le service d'émission gratuit initialement annoncé. Pour émettre et recevoir, vous devez passer par une Plateforme Agréée, dont l'offre peut être gratuite ou payante selon le volume et les fonctions." },
      { q: "Un logiciel de facturation gratuit suffit-il pour être en conformité ?", a: "Il peut suffire pour une petite structure, à condition qu'il couvre l'émission et la réception au format structuré (Factur-X, UBL), qu'il transite par une Plateforme Agréée et qu'il gère l'e-reporting si vous vendez aux particuliers. Vérifiez les limites de volume et les fonctions incluses avant de vous engager." },
      { q: "Quels sont les pièges d'une offre gratuite ?", a: "Les limites de volume (gratuit jusqu'à un certain nombre de factures), les fonctions bridées (réception ou e-reporting en option payante), la dépendance à une solution fermée compliquant une migration, et le temps perdu à paramétrer un outil inadapté. Le gratuit n'est pas mauvais, mais il faut lire ce qu'il couvre réellement." },
    ],
  },

  {
    slug: "plateforme-agreee-facturation-electronique",
    title: "Plateforme Agréée (PA) : comment la choisir pour vos factures électroniques",
    description:
      "Qu'est-ce qu'une Plateforme Agréée (ex-PDP) ? À quoi sert le PPF ? Comment choisir la bonne plateforme de facturation électronique selon votre activité et vos outils.",
    date: "2026-09-02",
    readingTime: "7 min",
    category: "Facturation électronique",
    keywords: [
      "plateforme agréée facturation électronique",
      "facturation électronique pa",
      "quelle plateforme facturation électronique choisir",
      "liste plateformes facturation électronique",
      "facturation électronique annuaire",
    ],
    related: [
      { href: "/guides/facturation-electronique-obligatoire", label: "Le guide complet de la facturation électronique" },
      { href: "/outils/facturation-electronique-simulateur", label: "Simulateur : suis-je concerné et à quelle date ?" },
    ],
    content: [
      { type: "p", text: "Avec la réforme, vous ne pourrez plus envoyer une facture directement par e-mail à un client professionnel : elle devra passer par une Plateforme Agréée. Ce nouvel intermédiaire obligatoire déroute beaucoup d'entreprises. Voici ce que c'est, et comment choisir la vôtre sans se tromper." },
      { type: "h2", text: "Qu'est-ce qu'une Plateforme Agréée (PA) ?" },
      { type: "p", text: "Une Plateforme Agréée — anciennement appelée « PDP » (Plateforme de Dématérialisation Partenaire) — est un opérateur immatriculé par l'administration, autorisé à émettre, transmettre et recevoir les factures électroniques pour le compte des entreprises. Elle garantit l'acheminement au bon format (Factur-X, UBL, CII) et transmet les données requises à l'administration fiscale." },
      { type: "h2", text: "PA, PPF, annuaire : ne pas confondre" },
      { type: "ul", items: [
        "La Plateforme Agréée (PA) : c'est par elle que transitent vos factures. C'est le choix central à faire.",
        "Le Portail Public de Facturation (PPF) : il ne joue plus le rôle de plateforme d'émission gratuite prévu à l'origine. Il devient un annuaire (qui reçoit quelle facture, à quelle adresse) et un concentrateur de données pour l'administration.",
        "L'annuaire : il permet de router chaque facture vers la bonne plateforme du destinataire — d'où l'importance d'y être correctement référencé.",
      ]},
      { type: "h2", text: "Comment choisir la bonne plateforme" },
      { type: "ul", items: [
        "Compatibilité avec vos outils : idéalement, votre logiciel de facturation ou de comptabilité propose déjà (ou se connecte à) une Plateforme Agréée.",
        "Couverture fonctionnelle : émission, réception, e-reporting, archivage — vérifiez que tout ce dont vous avez besoin est couvert.",
        "Volume et tarif : un auto-entrepreneur et une PME n'ont pas les mêmes besoins ; comparez le coût à votre volume réel de factures.",
        "Pérennité : privilégiez une plateforme bien établie et réellement immatriculée, pour éviter une migration forcée plus tard.",
      ]},
      { type: "cta", text: "Avant de choisir : vérifiez d'abord si — et quand — vous êtes concerné.", href: "/outils/facturation-electronique-simulateur", label: "Utiliser le simulateur" },
      { type: "h2", text: "« Ma banque ou mon logiciel s'en charge-t-il ? »" },
      { type: "p", text: "C'est une question fréquente : beaucoup de banques en ligne, d'outils de facturation et de logiciels de comptabilité annoncent une prise en charge de la facturation électronique. Souvent, ils s'appuient sur une Plateforme Agréée partenaire ou passent eux-mêmes l'immatriculation. Le bon réflexe : demander explicitement à votre outil actuel s'il sera une Plateforme Agréée ou connecté à l'une d'elles — cela peut vous éviter d'ajouter un nouvel outil." },
      { type: "h2", text: "Où trouver la liste officielle" },
      { type: "p", text: "L'administration publie la liste des Plateformes Agréées immatriculées. C'est la référence pour vérifier qu'un prestataire est bien habilité avant de s'engager. Méfiez-vous des offres qui promettent la conformité sans figurer dans cette liste ou sans s'appuyer sur une plateforme qui y figure." },
    ],
    faq: [
      { q: "Qu'est-ce qu'une Plateforme Agréée pour la facturation électronique ?", a: "C'est un opérateur immatriculé par l'administration (anciennement appelé « PDP »), autorisé à émettre, transmettre et recevoir les factures électroniques pour le compte des entreprises, au bon format et en transmettant les données requises à l'administration fiscale. Toutes les factures B2B devront transiter par une telle plateforme." },
      { q: "Le portail public (PPF) peut-il servir de plateforme gratuite ?", a: "Non. Dans la version réaménagée de la réforme, le PPF ne joue plus le rôle de plateforme d'émission gratuite prévu à l'origine : il devient un annuaire et un concentrateur de données. Pour émettre et recevoir vos factures, vous devez passer par une Plateforme Agréée." },
      { q: "Comment choisir sa plateforme de facturation électronique ?", a: "Regardez la compatibilité avec vos outils actuels, la couverture fonctionnelle (émission, réception, e-reporting, archivage), le tarif rapporté à votre volume de factures, et la pérennité du prestataire. Souvent, votre logiciel de facturation ou votre expert-comptable propose déjà une solution, ce qui évite d'ajouter un outil." },
      { q: "Ma banque gère-t-elle la facturation électronique ?", a: "Plusieurs banques et outils de facturation annoncent une prise en charge, en s'appuyant sur une Plateforme Agréée partenaire ou en s'immatriculant eux-mêmes. Demandez explicitement à votre banque ou à votre logiciel s'ils seront une Plateforme Agréée ou connectés à l'une d'elles avant de compter dessus." },
    ],
  },

  {
    slug: "facturation-electronique-2026",
    title: "Facturation électronique 2026 : ce qui change au 1er septembre",
    description:
      "Facturation électronique 2026 : ce qui devient obligatoire au 1er septembre (réception pour tous, émission des grandes entreprises), et ce qui attend encore 2027.",
    date: "2026-09-02",
    readingTime: "6 min",
    category: "Facturation électronique",
    keywords: [
      "facturation électronique 2026",
      "facturation électronique 2026 c'est quoi",
      "facturation électronique france 2026",
      "facturation électronique 2026 pour qui",
      "facturation électronique 1er septembre 2026",
    ],
    related: [
      { href: "/guides/facturation-electronique-obligatoire", label: "Le guide complet de la facturation électronique" },
      { href: "/outils/facturation-electronique-simulateur", label: "Simulateur : suis-je concerné et à quelle date ?" },
    ],
    content: [
      { type: "p", text: "2026 est la première grande étape de la facturation électronique obligatoire en France. Mais tout ne bascule pas d'un coup : certaines obligations démarrent au 1er septembre 2026, d'autres attendent 2027. Voici précisément ce qui change cette année — et ce qui vous concerne." },
      { type: "h2", text: "Ce qui devient obligatoire au 1er septembre 2026" },
      { type: "ul", items: [
        "La réception pour toutes les entreprises assujetties : quelle que soit votre taille, vous devez être en capacité de recevoir une facture électronique.",
        "L'émission pour les grandes entreprises et les ETI : elles doivent émettre leurs factures au format électronique.",
      ]},
      { type: "p", text: "La conséquence est simple mais souvent négligée : même une TPE ou un auto-entrepreneur, qui n'a pas encore à émettre, doit dès 2026 pouvoir recevoir les factures électroniques de ses fournisseurs et grands donneurs d'ordre." },
      { type: "h2", text: "Ce qui NE change pas encore en 2026" },
      { type: "p", text: "Les PME, TPE, micro-entreprises et indépendants n'ont pas encore l'obligation d'émettre au format électronique en 2026 : cette bascule est fixée au 1er septembre 2027. Vous avez donc un délai supplémentaire pour l'émission — mais pas pour la réception." },
      { type: "h2", text: "Pourquoi 2026 vous concerne même si vous êtes une petite structure" },
      { type: "p", text: "C'est le contresens le plus fréquent : « je suis une petite entreprise, j'ai jusqu'en 2027, je verrai plus tard. » Faux, car l'obligation de réception s'impose à tous dès 2026. Si un fournisseur (souvent une grande entreprise déjà passée à l'émission) vous envoie une facture électronique, vous devez pouvoir la recevoir et la traiter via une Plateforme Agréée." },
      { type: "cta", text: "Grande, moyenne ou petite structure : quelle est VOTRE date exacte ?", href: "/outils/facturation-electronique-simulateur", label: "Utiliser le simulateur" },
      { type: "h2", text: "Ce qu'il faut avoir fait avant septembre 2026" },
      { type: "ul", items: [
        "Choisir une Plateforme Agréée pour, au minimum, recevoir vos factures.",
        "Vérifier que vos informations (SIREN, adresse électronique de réception) sont correctes dans l'annuaire.",
        "Faire le point avec votre expert-comptable sur votre situation TVA et votre calendrier d'émission.",
      ]},
      { type: "p", text: "2026 n'est pas l'année où « tout le monde émet » : c'est l'année où tout le monde doit pouvoir recevoir, et où les grandes structures ouvrent le bal de l'émission. Considérez-la comme votre fenêtre de préparation avant l'échéance d'émission de 2027." },
    ],
    faq: [
      { q: "Qu'est-ce qui change au 1er septembre 2026 pour la facturation électronique ?", a: "Deux choses : toutes les entreprises assujetties doivent être en capacité de recevoir des factures électroniques, et les grandes entreprises ainsi que les ETI doivent émettre leurs factures au format électronique. Les plus petites structures, elles, n'émettent obligatoirement qu'à partir de 2027." },
      { q: "Suis-je concerné par la facturation électronique en 2026 si je suis une TPE ?", a: "Oui, pour la réception : dès le 1er septembre 2026, même une TPE ou un auto-entrepreneur doit pouvoir recevoir une facture électronique. L'obligation d'émettre, en revanche, ne s'applique aux petites structures qu'à partir du 1er septembre 2027." },
      { q: "Les auto-entrepreneurs doivent-ils émettre des factures électroniques en 2026 ?", a: "Non. Les micro-entreprises et auto-entrepreneurs doivent pouvoir recevoir dès 2026, mais leur obligation d'émission au format électronique commence au 1er septembre 2027." },
      { q: "Que faut-il avoir fait avant septembre 2026 ?", a: "Au minimum : choisir une Plateforme Agréée pour recevoir vos factures, vérifier que votre SIREN et votre adresse de réception sont correctement référencés, et faire le point avec votre expert-comptable sur votre régime TVA et votre calendrier d'émission." },
    ],
  },

  {
    slug: "comparatif-plateformes-facturation-electronique",
    title: "Comparatif des plateformes de facturation électronique (2026)",
    description:
      "Pennylane, Sage, Odoo, Qonto, Indy, Dolibarr… Comment comparer les plateformes de facturation électronique et choisir la bonne selon votre profil, sans se tromper.",
    date: "2026-09-02",
    readingTime: "8 min",
    category: "Facturation électronique",
    keywords: [
      "comparatif plateformes facturation électronique",
      "quelle plateforme facturation électronique choisir",
      "facturation électronique pennylane",
      "facturation électronique sage",
      "facturation électronique odoo",
    ],
    related: [
      { href: "/guides/facturation-electronique-obligatoire", label: "Le guide complet de la facturation électronique" },
      { href: "/blog/plateforme-agreee-facturation-electronique", label: "Qu'est-ce qu'une Plateforme Agréée ?" },
    ],
    content: [
      { type: "p", text: "Pennylane, Sage, Odoo, Qonto, Indy, Tiime, Abby, Henrri, Dolibarr… Le marché des solutions de facturation électronique est déjà encombré, et chacune promet la conformité. Plutôt qu'un classement figé qui vieillira vite, voici une grille de lecture pour comparer sans se tromper — et choisir selon VOTRE profil." },
      { type: "h2", text: "Le vrai critère : est-ce une Plateforme Agréée (ou connectée à une) ?" },
      { type: "p", text: "Avant le prix ou les fonctions, une seule question compte : la solution est-elle une Plateforme Agréée immatriculée, ou s'appuie-t-elle sur l'une d'elles ? Une jolie interface qui ne transite pas par une plateforme agréée ne vous met pas en conformité. Exigez cette information noir sur blanc, et recoupez avec la liste officielle publiée par l'administration." },
      { type: "h2", text: "Comparer selon 5 critères, pas selon la marque" },
      { type: "ul", items: [
        "Périmètre : émission ET réception ? e-reporting B2C/international ? archivage à valeur probante ?",
        "Formats : Factur-X, UBL, CII pris en charge nativement.",
        "Intégration : la solution se connecte-t-elle à vos outils actuels (banque, compta, caisse, e-commerce) ?",
        "Tarif rapporté au volume : gratuit ou quelques euros pour un auto-entrepreneur, offre structurée pour une PME.",
        "Accompagnement : support, migration, aide de votre expert-comptable.",
      ]},
      { type: "h2", text: "Les grandes familles de solutions" },
      { type: "ul", items: [
        "Les compta / facturation tout-en-un (type Pennylane, Tiime) : intéressantes si vous voulez centraliser compta et facturation, souvent avec l'expert-comptable dans la boucle.",
        "Les ERP (type Odoo, Sage) : pertinents pour les structures qui ont déjà une gestion intégrée (stocks, achats, ventes).",
        "Les néobanques et outils pro (type Qonto) : pratiques si vous voulez rester dans l'outil qui gère déjà vos paiements.",
        "Les outils pour indépendants (type Indy, Abby, Henrri) : pensés pour les micro-entreprises, simples et peu coûteux.",
        "Les solutions open-source (type Dolibarr) : flexibles, mais demandent des compétences techniques ou un intégrateur.",
      ]},
      { type: "p", text: "Aucune de ces catégories n'est « la meilleure » dans l'absolu : la bonne dépend de votre taille, de vos outils existants et de votre budget. Le plus souvent, la solution la plus économique est celle qui s'intègre à ce que vous utilisez déjà." },
      { type: "cta", text: "Vous ne savez pas par quel bout prendre le choix ?", href: "/guides/facturation-electronique-obligatoire", label: "Lire le guide complet de la facturation électronique" },
      { type: "h2", text: "L'erreur à éviter : choisir avant de connaître son besoin" },
      { type: "p", text: "Beaucoup d'entreprises se précipitent sur la marque la plus connue ou la moins chère, puis découvrent qu'elle ne couvre pas la réception, ou pas l'e-reporting, ou qu'elle ne s'intègre pas à leur logiciel de caisse. Commencez par lister vos besoins (émission, réception, e-reporting, intégrations), puis confrontez chaque solution à cette liste. C'est l'inverse du réflexe habituel — et c'est ce qui évite de changer d'outil six mois plus tard." },
    ],
    faq: [
      { q: "Quelle est la meilleure plateforme de facturation électronique ?", a: "Il n'y a pas de meilleure plateforme dans l'absolu : cela dépend de votre taille, de vos outils existants et de votre budget. Le bon critère est de vérifier qu'elle est une Plateforme Agréée (ou connectée à l'une d'elles), qu'elle couvre l'émission, la réception et l'e-reporting si besoin, et qu'elle s'intègre à ce que vous utilisez déjà." },
      { q: "Pennylane, Sage ou Odoo : lequel choisir pour la facturation électronique ?", a: "Cela dépend de votre profil : une solution de compta/facturation tout-en-un (comme Pennylane ou Tiime) convient si vous voulez centraliser avec votre expert-comptable ; un ERP (comme Odoo ou Sage) est adapté aux structures qui ont déjà une gestion intégrée. Comparez le périmètre, les formats, l'intégration et le tarif rapporté à votre volume plutôt que la notoriété." },
      { q: "Un auto-entrepreneur a-t-il besoin d'une grosse plateforme ?", a: "Non. Pour un auto-entrepreneur, un outil simple pensé pour les indépendants (avec un palier gratuit ou à faible coût) suffit généralement, à condition qu'il soit une Plateforme Agréée ou connecté à l'une d'elles et qu'il couvre la réception dès 2026 et l'émission pour 2027." },
      { q: "Comment vérifier qu'une plateforme est bien conforme ?", a: "Vérifiez qu'elle figure dans la liste officielle des Plateformes Agréées immatriculées par l'administration, ou qu'elle s'appuie explicitement sur l'une d'elles. Une solution qui ne transite pas par une plateforme agréée ne vous met pas en conformité, quelle que soit la qualité de son interface." },
    ],
  },

  {
    slug: "facturation-electronique-tpe-pme",
    title: "Facturation électronique : ce que doivent faire les TPE et PME (2026-2027)",
    description:
      "TPE et PME face à la facturation électronique : dates, réception dès 2026, émission en 2027, choix de plateforme et étapes concrètes pour se mettre en conformité.",
    date: "2026-09-02",
    readingTime: "6 min",
    category: "Facturation électronique",
    keywords: [
      "facturation électronique tpe",
      "facturation électronique pme",
      "facturation électronique petite entreprise",
      "facturation électronique entreprise",
    ],
    related: [
      { href: "/guides/facturation-electronique-obligatoire", label: "Le guide complet de la facturation électronique" },
      { href: "/outils/facturation-electronique-simulateur", label: "Simulateur : suis-je concerné et à quelle date ?" },
    ],
    content: [
      { type: "p", text: "TPE et PME représentent l'essentiel du tissu économique concerné par la facturation électronique — et celles qui ont le plus à gagner à s'y prendre tôt. Voici vos dates, ce qui change, et la marche à suivre sans stress." },
      { type: "h2", text: "Vos dates selon votre taille" },
      { type: "ul", items: [
        "Réception : toutes les TPE et PME assujetties doivent pouvoir recevoir une facture électronique dès le 1er septembre 2026.",
        "Émission : pour les PME, TPE et micro-entreprises, l'obligation d'émettre au format électronique arrive au 1er septembre 2027.",
        "Rappel : les grandes entreprises et ETI, elles, émettent déjà dès 2026 — donc vos gros clients ou fournisseurs peuvent vous envoyer des factures électroniques avant même votre propre échéance d'émission.",
      ]},
      { type: "h2", text: "Ce qui change concrètement dans votre quotidien" },
      { type: "p", text: "Fini le PDF envoyé par e-mail ou la facture Word/Excel pour vos clients professionnels : la facture devra être structurée (Factur-X, UBL, CII) et passer par une Plateforme Agréée. En contrepartie, bien outillée, la réforme fait gagner du temps : saisie automatique, moins d'erreurs, relances facilitées, rapprochement comptable simplifié." },
      { type: "cta", text: "Quelle est votre date exacte selon votre taille ?", href: "/outils/facturation-electronique-simulateur", label: "Utiliser le simulateur" },
      { type: "h2", text: "La marche à suivre en 5 étapes" },
      { type: "ul", items: [
        "1. Confirmer votre situation TVA et votre calendrier avec votre expert-comptable.",
        "2. Choisir une Plateforme Agréée — souvent celle intégrée à votre logiciel actuel.",
        "3. Mettre à jour vos mentions obligatoires (dont le SIREN de vos clients pros).",
        "4. Organiser la réception dès 2026, même si vous n'émettez qu'en 2027.",
        "5. Tester un cycle complet (émission, réception) avant l'échéance, pas la veille.",
      ]},
      { type: "p", text: "Le piège classique de la TPE/PME : se dire « j'ai jusqu'en 2027 » et repousser. Or la réception s'impose dès 2026, et le paramétrage prend du temps. Traiter le sujet maintenant, à froid, coûte bien moins cher que dans l'urgence de l'échéance." },
    ],
    faq: [
      { q: "À partir de quand la facturation électronique est-elle obligatoire pour une PME ?", a: "Une PME doit pouvoir recevoir des factures électroniques dès le 1er septembre 2026, et émettre ses propres factures au format électronique à partir du 1er septembre 2027. Les grandes entreprises et ETI, elles, émettent dès 2026." },
      { q: "Une TPE est-elle concernée dès 2026 ?", a: "Oui, pour la réception : dès le 1er septembre 2026, une TPE assujettie doit être en capacité de recevoir une facture électronique. Son obligation d'émission commence au 1er septembre 2027." },
      { q: "Que doit faire concrètement une TPE ou PME pour se mettre en conformité ?", a: "Confirmer sa situation TVA avec son expert-comptable, choisir une Plateforme Agréée (souvent celle de son logiciel actuel), mettre à jour ses mentions obligatoires, organiser la réception dès 2026 et tester un cycle complet avant l'échéance d'émission de 2027." },
      { q: "La facturation électronique va-t-elle compliquer la gestion d'une petite entreprise ?", a: "À l'installation, elle demande un paramétrage. Ensuite, bien outillée, elle simplifie le quotidien : saisie automatique, moins d'erreurs, relances et rapprochement comptable facilités. L'enjeu est de choisir un outil adapté à sa taille et de s'y prendre à l'avance." },
    ],
  },

  {
    slug: "factur-x-ubl-formats-facture-electronique",
    title: "Factur-X, UBL, CII : comprendre les formats de facture électronique",
    description:
      "Factur-X, UBL, CII : quels sont les formats structurés de la facture électronique, pourquoi un simple PDF ne suffit plus, et lequel choisir. Explications claires.",
    date: "2026-09-02",
    readingTime: "6 min",
    category: "Facturation électronique",
    keywords: [
      "factur-x",
      "facturation électronique ubl",
      "facturation électronique format xml",
      "format facture électronique",
      "facturation électronique norme",
    ],
    related: [
      { href: "/guides/facturation-electronique-obligatoire", label: "Le guide complet de la facturation électronique" },
      { href: "/blog/plateforme-agreee-facturation-electronique", label: "Comment choisir sa plateforme agréée" },
    ],
    content: [
      { type: "p", text: "« Pourquoi mon PDF habituel ne suffit-il plus ? » Parce que la facture électronique doit être lisible par une machine, pas seulement par un humain. C'est tout l'objet des formats structurés — Factur-X, UBL, CII. Voici ce qu'ils sont, sans jargon." },
      { type: "h2", text: "Pourquoi un PDF classique ne suffit plus" },
      { type: "p", text: "Un PDF « imprimé » est une image de facture : un logiciel ne peut pas en extraire automatiquement le montant, la TVA ou le SIREN de façon fiable. La réforme impose des formats structurés, où chaque donnée est balisée et exploitable directement par les logiciels comptables et par l'administration. C'est ce qui permet l'automatisation et le contrôle de la TVA." },
      { type: "h2", text: "Les trois formats socles" },
      { type: "ul", items: [
        "Factur-X : un format hybride, très répandu en France. C'est un PDF (lisible par un humain) qui embarque un fichier XML de données (lisible par une machine). Le meilleur des deux mondes.",
        "UBL (Universal Business Language) : un format XML pur, standard international largement utilisé en Europe.",
        "CII (Cross Industry Invoice) : un autre format XML, également reconnu par la norme européenne.",
      ]},
      { type: "p", text: "Ces trois formats respectent la norme européenne de facturation électronique (EN 16931). En pratique, beaucoup d'entreprises françaises s'appuient sur Factur-X parce qu'il reste lisible comme un PDF tout en étant exploitable automatiquement." },
      { type: "cta", text: "Vous voulez savoir quel format votre outil doit produire ?", href: "/guides/facturation-electronique-obligatoire", label: "Lire le guide complet de la facturation électronique" },
      { type: "h2", text: "Bonne nouvelle : vous n'avez pas à gérer le format à la main" },
      { type: "p", text: "Vous n'aurez pas à écrire du XML : c'est votre logiciel de facturation ou votre Plateforme Agréée qui produit le format structuré à partir des informations que vous saisissez. Votre rôle est de choisir un outil qui gère nativement au moins l'un de ces formats et qui transite par une plateforme agréée. Le reste est automatique." },
    ],
    faq: [
      { q: "Qu'est-ce que le format Factur-X ?", a: "Factur-X est un format hybride de facture électronique, très répandu en France : c'est un PDF lisible par un humain qui embarque un fichier XML de données lisible par une machine. Il permet à la fois de consulter la facture normalement et de l'exploiter automatiquement par les logiciels et l'administration." },
      { q: "Quelle différence entre Factur-X, UBL et CII ?", a: "Factur-X est un format hybride (PDF + XML), tandis qu'UBL et CII sont des formats XML purs. Les trois respectent la norme européenne EN 16931. En France, Factur-X est particulièrement utilisé car il reste lisible comme un PDF tout en étant structuré." },
      { q: "Pourquoi un PDF classique ne suffit-il plus pour une facture ?", a: "Un PDF classique est une image de facture qu'un logiciel ne peut pas exploiter automatiquement de façon fiable. La réforme impose des formats structurés où chaque donnée (montant, TVA, SIREN) est balisée et directement lisible par les logiciels et l'administration, ce qui permet l'automatisation et le contrôle de la TVA." },
      { q: "Dois-je créer le fichier XML moi-même ?", a: "Non. C'est votre logiciel de facturation ou votre Plateforme Agréée qui génère le format structuré à partir des informations que vous saisissez. Vous devez seulement choisir un outil qui gère nativement l'un des formats admis (Factur-X, UBL ou CII) et qui transite par une plateforme agréée." },
    ],
  },

  {
    slug: "e-reporting-facturation-electronique",
    title: "E-reporting : ce que c'est et qui est concerné (2026-2027)",
    description:
      "L'e-reporting complète la facturation électronique : transmission des données de vos ventes aux particuliers et à l'international. Ce que c'est, qui est concerné, à quelles dates.",
    date: "2026-09-02",
    readingTime: "6 min",
    category: "Facturation électronique",
    keywords: [
      "e-reporting facturation électronique",
      "e-reporting c'est quoi",
      "e-reporting qui est concerné",
      "facturation électronique reporting",
      "e-reporting international",
    ],
    related: [
      { href: "/guides/facturation-electronique-obligatoire", label: "Le guide complet de la facturation électronique" },
      { href: "/blog/facturation-electronique-auto-entrepreneur", label: "Facturation électronique et auto-entrepreneurs" },
    ],
    content: [
      { type: "p", text: "On parle beaucoup de la facture électronique, moins de l'e-reporting — et pourtant, pour beaucoup d'entreprises (commerces, e-commerçants, prestataires vendant à des particuliers ou à l'étranger), c'est ce second volet qui les concerne. Voici ce que c'est, simplement." },
      { type: "h2", text: "E-invoicing vs e-reporting : deux volets complémentaires" },
      { type: "p", text: "La réforme repose sur deux mécanismes. La facture électronique (e-invoicing) concerne les opérations entre professionnels établis en France (B2B). L'e-reporting concerne les opérations qui échappent à ce circuit : les ventes aux particuliers (B2C) et les opérations avec l'étranger. Dans ces cas, il n'y a pas de facture électronique à transmettre à un client via une plateforme, mais des données de transaction à communiquer à l'administration." },
      { type: "h2", text: "Qui est concerné par l'e-reporting ?" },
      { type: "ul", items: [
        "Les entreprises qui vendent à des particuliers (commerces, restaurants, e-commerce, services aux particuliers).",
        "Les entreprises qui réalisent des opérations avec des clients ou fournisseurs étrangers.",
        "Beaucoup d'entreprises sont concernées par les DEUX : facture électronique pour leurs clients pros français, e-reporting pour leurs ventes aux particuliers ou à l'international.",
      ]},
      { type: "h2", text: "Concrètement, que faut-il transmettre ?" },
      { type: "p", text: "L'e-reporting consiste à transmettre à l'administration des données de transaction (montants, TVA…) et, pour les encaissements concernés, des données de paiement, selon une périodicité définie. Comme pour la facture électronique, cela passe par une Plateforme Agréée : vous ne remplissez pas un formulaire à la main, c'est votre outil qui transmet." },
      { type: "cta", text: "Vous vendez aux particuliers ? Vérifiez ce qui vous concerne.", href: "/guides/facturation-electronique-obligatoire", label: "Lire le guide complet de la facturation électronique" },
      { type: "h2", text: "Les dates" },
      { type: "p", text: "L'e-reporting suit une logique de calendrier proche de celle de l'émission de factures électroniques, avec une montée en charge selon la taille des entreprises (2026 pour les grandes structures, 2027 pour les plus petites). Le point important : ne l'oubliez pas dans le choix de votre outil, car une solution qui ne gère que la facture électronique B2B peut vous laisser à découvert sur vos ventes aux particuliers." },
    ],
    faq: [
      { q: "Qu'est-ce que l'e-reporting ?", a: "L'e-reporting est la transmission à l'administration fiscale des données de transaction (et de paiement pour certaines opérations) qui n'entrent pas dans le circuit de la facture électronique entre professionnels français : principalement les ventes aux particuliers (B2C) et les opérations avec l'étranger." },
      { q: "Quelle différence entre facture électronique et e-reporting ?", a: "La facture électronique (e-invoicing) concerne les opérations B2B entre professionnels établis en France : une facture structurée circule via une Plateforme Agréée. L'e-reporting concerne les ventes aux particuliers et les opérations internationales : il n'y a pas de facture à transmettre à un client, mais des données de transaction à communiquer à l'administration." },
      { q: "Qui est concerné par l'e-reporting ?", a: "Les entreprises qui vendent à des particuliers (commerces, restaurants, e-commerce, services) et celles qui réalisent des opérations avec l'étranger. Beaucoup d'entreprises sont concernées à la fois par la facture électronique (clients pros français) et par l'e-reporting (particuliers ou international)." },
      { q: "Dois-je faire l'e-reporting manuellement ?", a: "Non. Comme pour la facture électronique, l'e-reporting passe par une Plateforme Agréée qui transmet les données à l'administration selon la périodicité prévue. Il faut simplement veiller à choisir un outil qui gère l'e-reporting si vous vendez aux particuliers ou à l'international." },
    ],
  },

  {
    slug: "nouvelles-mentions-obligatoires-facture-electronique",
    title: "Facture électronique : les nouvelles mentions obligatoires (SIREN…)",
    description:
      "La facturation électronique ajoute de nouvelles mentions obligatoires sur les factures : SIREN du client, type d'opération, adresse de livraison, option de paiement de la TVA. Le point complet.",
    date: "2026-09-02",
    readingTime: "6 min",
    category: "Facturation électronique",
    keywords: [
      "facture électronique nouvelles mentions obligatoires",
      "facturation électronique siren ou siret",
      "mentions obligatoires facture électronique",
      "facturation électronique mentions",
    ],
    related: [
      { href: "/guides/facturation-electronique-obligatoire", label: "Le guide complet de la facturation électronique" },
      { href: "/blog/plateforme-agreee-facturation-electronique", label: "Comment choisir sa plateforme agréée" },
    ],
    content: [
      { type: "p", text: "La facturation électronique ne change pas seulement le format des factures : elle ajoute de nouvelles mentions obligatoires. Les oublier, c'est risquer des factures rejetées par la plateforme. Voici ce qui s'ajoute à vos mentions habituelles." },
      { type: "h2", text: "Les nouvelles mentions introduites par la réforme" },
      { type: "ul", items: [
        "Le numéro SIREN du client (en plus des mentions habituelles), pour identifier précisément le destinataire.",
        "Le type d'opération : livraison de biens, prestation de services, ou les deux.",
        "L'adresse de livraison des biens lorsqu'elle diffère de l'adresse de facturation.",
        "L'option pour le paiement de la TVA d'après les débits, le cas échéant.",
      ]},
      { type: "p", text: "Ces mentions s'ajoutent à celles déjà exigées aujourd'hui (identité des parties, numéro et date de facture, désignation, quantités, prix, TVA, conditions de paiement…). La plupart seront gérées par votre logiciel, à condition que votre base clients soit à jour." },
      { type: "h2", text: "SIREN ou SIRET : le point de vigilance" },
      { type: "p", text: "Le SIREN de l'émetteur est une donnée centrale et contrôlée : sans immatriculation valide, impossible d'émettre une facture électronique conforme. C'est un point crucial pour les structures en cours de création — mieux vaut anticiper l'obtention du SIREN avant l'échéance d'émission qui vous concerne. Pensez aussi à fiabiliser les SIREN de vos clients professionnels dans votre base, car ils devront figurer sur les factures." },
      { type: "cta", text: "Votre base clients et vos mentions sont-elles prêtes ?", href: "/guides/facturation-electronique-obligatoire", label: "Lire le guide complet de la facturation électronique" },
      { type: "h2", text: "Pourquoi ces mentions comptent vraiment" },
      { type: "p", text: "Dans le circuit électronique, une facture incomplète n'est pas seulement « moins propre » : elle peut être rejetée automatiquement par la plateforme, ce qui retarde votre paiement. Fiabiliser vos mentions et votre base clients en amont évite ces blocages le jour où l'obligation s'applique." },
    ],
    faq: [
      { q: "Quelles sont les nouvelles mentions obligatoires de la facture électronique ?", a: "La réforme ajoute notamment le numéro SIREN du client, le type d'opération (livraison de biens, prestation de services ou les deux), l'adresse de livraison lorsqu'elle diffère de l'adresse de facturation, et l'option pour le paiement de la TVA d'après les débits le cas échéant. Elles s'ajoutent aux mentions déjà exigées." },
      { q: "Faut-il indiquer le SIREN ou le SIRET sur une facture électronique ?", a: "Le numéro SIREN du client fait partie des nouvelles mentions à faire figurer. Côté émetteur, un SIREN valide est indispensable pour émettre une facture conforme : sans immatriculation, l'émission est impossible. Fiabilisez donc les SIREN de vos clients professionnels dans votre base." },
      { q: "Que se passe-t-il si une mention obligatoire manque ?", a: "Dans le circuit électronique, une facture incomplète peut être rejetée automatiquement par la plateforme, ce qui retarde votre paiement. C'est pourquoi il est important de fiabiliser ses mentions et sa base clients avant que l'obligation ne s'applique." },
      { q: "Mon logiciel gère-t-il ces mentions automatiquement ?", a: "En grande partie, oui, à condition que votre base clients soit à jour (notamment les SIREN de vos clients professionnels). Le logiciel ou la Plateforme Agréée compose la facture au bon format avec les mentions requises à partir des informations que vous avez saisies." },
    ],
  },

  {
    slug: "facturation-electronique-professions-liberales",
    title: "Facturation électronique et professions libérales de santé (2026)",
    description:
      "Médecin, infirmière, kiné, ostéo, orthophoniste : êtes-vous concerné par la facturation électronique ? La plupart des soins sont exonérés de TVA — voici ce que ça change.",
    date: "2026-09-02",
    readingTime: "7 min",
    category: "Facturation électronique",
    keywords: [
      "facturation électronique professions libérales",
      "facturation électronique médecin",
      "facturation électronique infirmière libérale",
      "facturation électronique kiné",
      "facturation électronique ostéopathe",
    ],
    related: [
      { href: "/guides/facturation-electronique-obligatoire", label: "Le guide complet de la facturation électronique" },
      { href: "/outils/facturation-electronique-simulateur", label: "Simulateur : suis-je concerné et à quelle date ?" },
    ],
    content: [
      { type: "p", text: "Médecin, infirmière libérale, kinésithérapeute, ostéopathe, orthophoniste : la facturation électronique vous concerne-t-elle ? Bonne nouvelle pour beaucoup de praticiens : les actes de soins sont souvent exonérés de TVA, ce qui change la donne. Mais « exonéré » ne veut pas dire « rien à faire ». Faisons le point." },
      { type: "h2", text: "La plupart des soins sont exonérés de TVA" },
      { type: "p", text: "Les actes de soins réalisés par les professions médicales et paramédicales réglementées bénéficient, en règle générale, d'une exonération de TVA. Or la facturation électronique vise les opérations B2B entre assujettis à la TVA. Résultat : pour votre activité de soins exonérée, vous n'êtes pas dans le champ de l'émission de factures électroniques B2B assujetties." },
      { type: "ul", items: [
        "Activité de soins exonérée de TVA : pas d'émission de facture électronique B2B assujettie.",
        "Vous devez néanmoins pouvoir recevoir une facture électronique de vos fournisseurs (matériel, prestataires) dès le 1er septembre 2026.",
        "Attention aux activités accessoires taxables (formation, expertise, ventes, activités non thérapeutiques) qui, elles, peuvent être assujetties à la TVA — et donc concernées.",
      ]},
      { type: "h2", text: "« Exonéré » ne veut pas dire « rien à prévoir »" },
      { type: "p", text: "Même sans obligation d'émettre, vous restez concerné par la réception. Concrètement, si un fournisseur assujetti vous envoie une facture électronique, vous devez pouvoir la recevoir et la traiter via une Plateforme Agréée. Il faut donc, au minimum, organiser cette réception." },
      { type: "cta", text: "Praticien libéral : vérifiez votre situation exacte en 30 secondes.", href: "/outils/facturation-electronique-simulateur", label: "Utiliser le simulateur" },
      { type: "h2", text: "Le cas des activités mixtes" },
      { type: "p", text: "Beaucoup de praticiens ont une activité principale de soins (exonérée) et des activités accessoires potentiellement taxables. C'est précisément là que le curseur bascule : pour la partie assujettie à la TVA, la facturation électronique s'applique. Le périmètre exact se cale avec votre expert-comptable, car il dépend de la nature de chaque activité." },
      { type: "p", text: "À retenir : ne concluez ni « je suis libéral donc concerné », ni « je fais du soin donc jamais concerné ». Le bon réflexe est de distinguer vos activités exonérées de vos activités taxables, et d'organiser au minimum la réception dès 2026." },
    ],
    faq: [
      { q: "Un médecin ou une infirmière libérale est-il concerné par la facturation électronique ?", a: "Pour son activité de soins, généralement exonérée de TVA, il n'y a pas d'obligation d'émettre des factures électroniques B2B assujetties. En revanche, l'obligation de réception s'applique dès le 1er septembre 2026 : le praticien doit pouvoir recevoir les factures électroniques de ses fournisseurs. Les activités accessoires taxables, elles, peuvent être concernées." },
      { q: "Les actes de soins sont-ils soumis à la facturation électronique ?", a: "Les actes de soins des professions médicales et paramédicales réglementées sont en principe exonérés de TVA, donc hors du champ de l'émission de factures électroniques B2B assujetties. La réception reste toutefois obligatoire, et les activités taxables accessoires peuvent entrer dans le dispositif." },
      { q: "Un ostéopathe ou un kiné doit-il émettre des factures électroniques ?", a: "Cela dépend de son assujettissement à la TVA. Les actes de soins réglementés sont souvent exonérés (pas d'émission B2B assujettie), mais certaines activités peuvent être taxables selon la situation. Le mieux est de faire confirmer votre régime TVA par votre expert-comptable, et d'organiser la réception dès 2026." },
      { q: "Une profession libérale de santé doit-elle quand même s'équiper ?", a: "Oui, au minimum pour la réception : dès le 1er septembre 2026, elle doit pouvoir recevoir une facture électronique de ses fournisseurs via une Plateforme Agréée. L'ampleur de l'équipement dépend ensuite de l'existence ou non d'activités taxables nécessitant l'émission." },
    ],
  },

  {
    slug: "facturation-electronique-avocats",
    title: "Facturation électronique pour les avocats : ce qu'il faut savoir (2026)",
    description:
      "Les avocats sont assujettis à la TVA : la facturation électronique s'applique à leur cabinet. Dates, obligations, plateformes et spécificités du barreau. Le point complet.",
    date: "2026-09-02",
    readingTime: "7 min",
    category: "Facturation électronique",
    keywords: [
      "facturation électronique avocats",
      "facturation électronique cabinet avocat",
      "facturation électronique barreau",
      "facturation électronique profession réglementée",
      "facturation électronique expert judiciaire",
    ],
    related: [
      { href: "/guides/facturation-electronique-obligatoire", label: "Le guide complet de la facturation électronique" },
      { href: "/outils/facturation-electronique-simulateur", label: "Simulateur : suis-je concerné et à quelle date ?" },
    ],
    content: [
      { type: "p", text: "Contrairement à beaucoup de professions de santé, les avocats sont assujettis à la TVA sur leurs prestations : la facturation électronique s'applique donc pleinement à leur cabinet. Voici ce que cela implique concrètement, et à quelle échéance." },
      { type: "h2", text: "Les avocats sont assujettis à la TVA" },
      { type: "p", text: "Les prestations juridiques d'un avocat sont, en principe, soumises à la TVA. Un cabinet est donc un assujetti au sens de la réforme, et ses honoraires facturés à des clients professionnels entrent dans le champ de la facture électronique. C'est une différence majeure avec les professions médicales, souvent exonérées." },
      { type: "h2", text: "Vos dates" },
      { type: "ul", items: [
        "Réception : dès le 1er septembre 2026, votre cabinet doit pouvoir recevoir une facture électronique.",
        "Émission : la plupart des cabinets étant des TPE/PME, l'obligation d'émettre au format électronique arrive au 1er septembre 2027.",
        "Clients particuliers : les honoraires facturés à des particuliers relèvent de l'e-reporting, pas de la facture électronique B2B.",
      ]},
      { type: "h2", text: "Les spécificités à anticiper pour un cabinet" },
      { type: "ul", items: [
        "Le secret professionnel : la facture transite au format structuré (montants, identités) via une Plateforme Agréée — anticipez le choix d'un outil sérieux et conforme.",
        "Les logiciels métier : de nombreux logiciels de gestion de cabinet intègrent (ou intègreront) la conformité ; vérifiez auprès de votre éditeur.",
        "La CARPA et les maniements de fonds : distincts de la facturation d'honoraires ; c'est bien la facture d'honoraires qui est visée.",
        "Clientèle mixte (professionnels et particuliers) : vous serez souvent concerné par la facture électronique ET par l'e-reporting.",
      ]},
      { type: "cta", text: "Cabinet d'avocats : vérifiez votre échéance exacte.", href: "/outils/facturation-electronique-simulateur", label: "Utiliser le simulateur" },
      { type: "h2", text: "Que faire dès maintenant" },
      { type: "p", text: "Interrogez d'abord votre logiciel de gestion de cabinet : sera-t-il une Plateforme Agréée ou connecté à l'une d'elles ? Fiabilisez ensuite votre base clients (SIREN des clients professionnels), organisez la réception dès 2026 et préparez l'émission pour 2027. Comme pour toute profession réglementée, mieux vaut cadrer le sujet à froid que dans l'urgence." },
    ],
    faq: [
      { q: "Les avocats sont-ils concernés par la facturation électronique ?", a: "Oui. Les prestations d'avocat sont assujetties à la TVA, donc le cabinet entre dans le champ de la réforme. Il doit pouvoir recevoir des factures électroniques dès le 1er septembre 2026 et émettre au format électronique à partir du 1er septembre 2027 (pour la plupart des cabinets, qui sont des TPE/PME)." },
      { q: "Un avocat qui facture des particuliers est-il concerné ?", a: "Les honoraires facturés à des particuliers relèvent de l'e-reporting (transmission des données à l'administration), et non de la facture électronique B2B. Un cabinet avec une clientèle mixte est donc souvent concerné par les deux volets à la fois." },
      { q: "À quelle date un cabinet d'avocats doit-il émettre des factures électroniques ?", a: "Pour la plupart des cabinets (TPE/PME), l'obligation d'émission arrive au 1er septembre 2027. L'obligation de réception, elle, s'applique dès le 1er septembre 2026." },
      { q: "Quel outil un avocat doit-il utiliser ?", a: "Idéalement, le logiciel de gestion de cabinet s'il est (ou sera) une Plateforme Agréée ou connecté à l'une d'elles. À défaut, une Plateforme Agréée couvrant émission, réception et e-reporting. Vérifiez la conformité auprès de votre éditeur et recoupez avec la liste officielle des plateformes." },
    ],
  },

  {
    slug: "chorus-pro-facturation-electronique",
    title: "Chorus Pro et facturation électronique : quelle différence ? (2026)",
    description:
      "Chorus Pro (factures au secteur public) existe déjà. En quoi diffère-t-il de la nouvelle facturation électronique B2B obligatoire en 2026-2027 ? Explications.",
    date: "2026-09-02",
    readingTime: "6 min",
    category: "Facturation électronique",
    keywords: [
      "chorus pro facturation électronique",
      "chorus pro",
      "facturation électronique secteur public",
      "facture électronique marchés publics",
      "facturation électronique b2g",
    ],
    related: [
      { href: "/guides/facturation-electronique-obligatoire", label: "Le guide complet de la facturation électronique" },
      { href: "/blog/plateforme-agreee-facturation-electronique", label: "Qu'est-ce qu'une Plateforme Agréée ?" },
    ],
    content: [
      { type: "p", text: "Si vous facturez déjà des administrations, vous connaissez Chorus Pro. Beaucoup se demandent alors : la nouvelle réforme, c'est la même chose ? Pas tout à fait. Chorus Pro concerne le secteur public (B2G) et existe depuis plusieurs années ; la réforme 2026-2027 étend l'obligation aux échanges entre entreprises (B2B). Démêlons les deux." },
      { type: "h2", text: "Chorus Pro : la facture électronique au secteur public (B2G)" },
      { type: "p", text: "Depuis plusieurs années, toute entreprise qui facture l'État, une collectivité ou un établissement public doit déjà transmettre ses factures au format électronique via Chorus Pro. C'est l'obligation B2G (Business to Government), déjà en vigueur et généralisée. Si vous travaillez avec des marchés publics, vous la pratiquez sans doute au quotidien." },
      { type: "h2", text: "La réforme 2026-2027 : la facture électronique entre entreprises (B2B)" },
      { type: "p", text: "La nouveauté, c'est l'extension de l'obligation aux échanges entre entreprises privées (B2B). C'est ce qui démarre au 1er septembre 2026 (réception pour tous, émission des grandes entreprises et ETI) puis au 1er septembre 2027 (émission des PME, TPE et micro-entreprises). Elle s'appuie sur les Plateformes Agréées, pas seulement sur Chorus Pro." },
      { type: "ul", items: [
        "Chorus Pro = factures vers le secteur public (B2G), déjà obligatoire.",
        "Réforme 2026-2027 = factures entre entreprises privées (B2B), via les Plateformes Agréées.",
        "Les ventes aux particuliers (B2C) relèvent, elles, de l'e-reporting.",
      ]},
      { type: "cta", text: "Vous facturez à la fois le public et le privé ?", href: "/guides/facturation-electronique-obligatoire", label: "Lire le guide complet de la facturation électronique" },
      { type: "h2", text: "Concrètement, si vous utilisez déjà Chorus Pro" },
      { type: "p", text: "Continuer d'utiliser Chorus Pro pour vos factures au secteur public reste la règle. Pour vos clients privés, vous devrez en plus passer par une Plateforme Agréée. L'enjeu est donc de choisir une solution qui couvre vos deux mondes (public et privé) sans multiplier les outils. Faire le point tôt évite de gérer deux circuits en parallèle dans la précipitation." },
    ],
    faq: [
      { q: "Chorus Pro et la nouvelle facturation électronique, est-ce la même chose ?", a: "Non. Chorus Pro concerne les factures adressées au secteur public (B2G) et est déjà obligatoire depuis plusieurs années. La réforme 2026-2027 étend l'obligation aux factures entre entreprises privées (B2B), via les Plateformes Agréées. Les deux coexistent." },
      { q: "Dois-je continuer à utiliser Chorus Pro ?", a: "Oui, pour vos factures adressées à l'État, aux collectivités et aux établissements publics : l'obligation B2G via Chorus Pro reste en vigueur. Pour vos clients privés, vous devrez en plus passer par une Plateforme Agréée dans le cadre de la réforme B2B." },
      { q: "Une seule solution peut-elle gérer le public et le privé ?", a: "C'est l'objectif à viser : choisir une Plateforme Agréée (ou un logiciel connecté) qui couvre à la fois vos factures au secteur public et vos factures entre entreprises, pour éviter de multiplier les outils. Vérifiez ce périmètre avant de choisir." },
      { q: "La réforme B2B remplace-t-elle Chorus Pro ?", a: "Non, elle le complète. Chorus Pro reste le canal des factures au secteur public. La réforme ajoute l'obligation pour les échanges entre entreprises privées, avec un calendrier propre (réception 2026, émission 2026 pour les grandes entreprises et 2027 pour les autres)." },
    ],
  },

  {
    slug: "facturation-electronique-sanctions-amende",
    title: "Facturation électronique : quelles sanctions en cas de non-conformité ?",
    description:
      "Amendes, factures rejetées, retards de paiement : ce que vous risquez à ne pas respecter la facturation électronique obligatoire, et comment éviter les sanctions.",
    date: "2026-09-02",
    readingTime: "6 min",
    category: "Facturation électronique",
    keywords: [
      "facturation électronique sanctions",
      "facturation électronique amende",
      "facturation électronique non conformité",
      "facturation électronique refus",
      "facturation électronique obligatoire risque",
    ],
    related: [
      { href: "/guides/facturation-electronique-obligatoire", label: "Le guide complet de la facturation électronique" },
      { href: "/outils/facturation-electronique-simulateur", label: "Simulateur : suis-je concerné et à quelle date ?" },
    ],
    content: [
      { type: "p", text: "Que risque-t-on vraiment à ne pas être prêt pour la facturation électronique ? Il y a deux types de conséquences : les sanctions financières prévues par la loi, et — souvent plus immédiat — les blocages opérationnels. Faisons le tour, sans dramatiser ni minimiser." },
      { type: "h2", text: "Les amendes prévues par la loi" },
      { type: "p", text: "Le dispositif prévoit des amendes forfaitaires en cas de manquement, plafonnées à l'année. À titre indicatif, les montants souvent cités sont de l'ordre de quelques euros par facture non conforme pour l'e-invoicing et d'un montant par transmission manquante pour l'e-reporting, chacun plafonné annuellement. Ces montants et modalités pouvant évoluer, vérifiez toujours le régime en vigueur auprès de la DGFiP." },
      { type: "ul", items: [
        "E-invoicing : amende forfaitaire par facture non émise au format électronique, dans la limite d'un plafond annuel.",
        "E-reporting : amende forfaitaire par transmission de données manquante, également plafonnée à l'année.",
        "Ces sanctions visent le manquement à l'obligation, pas une simple erreur ponctuelle corrigée de bonne foi.",
      ]},
      { type: "h2", text: "Le risque le plus immédiat : la facture rejetée" },
      { type: "p", text: "Avant même toute amende, le vrai risque quotidien est opérationnel. Dans le circuit électronique, une facture non conforme (mauvais format, mention obligatoire manquante, SIREN erroné) peut être rejetée automatiquement par la plateforme. Résultat : elle n'est pas considérée comme émise, et votre paiement prend du retard. Multiplié sur plusieurs clients, cela pèse directement sur votre trésorerie." },
      { type: "h2", text: "Ne pas pouvoir recevoir, c'est aussi un problème" },
      { type: "p", text: "L'obligation de réception s'impose à tous dès 2026. Si un client ou un fournisseur passe à l'émission électronique et que vous n'êtes pas en capacité de recevoir, vous vous retrouvez bloqué dans vos échanges — sans même parler de sanction. C'est l'échéance la plus souvent négligée, et pourtant la première dans le calendrier." },
      { type: "cta", text: "Assurez-vous d'être prêt à la bonne date.", href: "/outils/facturation-electronique-simulateur", label: "Vérifier ma date avec le simulateur" },
      { type: "h2", text: "Comment éviter les sanctions" },
      { type: "p", text: "La parade est simple : anticiper. Choisir sa Plateforme Agréée, fiabiliser sa base clients (SIREN, mentions), organiser la réception dès 2026 et tester un cycle complet avant l'échéance élimine l'essentiel du risque. La plupart des sanctions et blocages viennent d'un défaut de préparation, pas d'une volonté de fraude — et se préviennent en traitant le sujet à froid." },
    ],
    faq: [
      { q: "Quelles sont les sanctions en cas de non-respect de la facturation électronique ?", a: "La loi prévoit des amendes forfaitaires en cas de manquement, plafonnées à l'année, distinctes pour l'e-invoicing (par facture non conforme) et l'e-reporting (par transmission manquante). Les montants et modalités pouvant évoluer, vérifiez le régime en vigueur auprès de la DGFiP. Au-delà des amendes, le risque le plus immédiat est le rejet de factures et le retard de paiement." },
      { q: "Que se passe-t-il si ma facture électronique est rejetée ?", a: "Une facture non conforme (format incorrect, mention obligatoire manquante, SIREN erroné) peut être rejetée automatiquement par la plateforme. Elle n'est alors pas considérée comme émise, ce qui retarde votre paiement. Fiabiliser ses mentions et sa base clients en amont évite ces blocages." },
      { q: "Est-ce que je risque une amende si je ne peux pas recevoir les factures électroniques ?", a: "L'obligation de réception s'applique à toutes les entreprises assujetties dès le 1er septembre 2026. Au-delà de la question des sanctions, ne pas pouvoir recevoir vous bloque dans vos échanges avec les clients et fournisseurs déjà passés à l'émission. C'est pourquoi la réception est la première étape à traiter." },
      { q: "Comment éviter les sanctions liées à la facturation électronique ?", a: "En anticipant : choisir sa Plateforme Agréée, fiabiliser sa base clients (SIREN, mentions obligatoires), organiser la réception dès 2026 et tester un cycle complet d'émission et de réception avant l'échéance. La plupart des sanctions viennent d'un défaut de préparation, pas d'une fraude." },
    ],
  },
];
