// Articles de blog du theme Securite Web. Ajouter un objet ici cree
// automatiquement la page /blog/<slug>, l'entree dans /blog et le sitemap.

import type { Post } from "./posts";

export const POSTS_SECURITE: Post[] = [
  {
    slug: "proteger-site-web-piratage",
    title: "Protéger son site web du piratage : le guide 2026",
    description:
      "Les menaces les plus courantes (brute force, injection SQL, XSS), les mesures de protection de base et la marche à suivre si votre site est piraté.",
    date: "2026-07-07",
    readingTime: "9 min",
    category: "Sécurité Web",
    keywords: [
      "protéger son site du piratage",
      "sécuriser site web",
      "site web piraté que faire",
      "cybersécurité PME site",
    ],
    related: [
      { href: "/services/securite-web", label: "Sécurité web" },
      { href: "/blog/securiser-application-nextjs-checklist", label: "Sécuriser une application Next.js" },
    ],
    content: [
      { type: "p", text: "Un site web n'est jamais trop petit pour être piraté. La plupart des attaques ne visent personne en particulier : ce sont des robots qui scannent des millions d'adresses à la recherche d'une faille connue. Une PME, un site vitrine ou une boutique en ligne sont donc des cibles au même titre qu'un grand groupe. Voici les menaces à connaître, les protections à mettre en place et la conduite à tenir si le pire arrive." },
      { type: "h2", text: "Les menaces les plus courantes" },
      { type: "p", text: "La quasi-totalité des piratages exploitent une poignée de techniques bien rodées. Les comprendre permet de comprendre les protections associées." },
      { type: "ul", items: [
        "Le brute force : le robot teste des milliers de couples identifiant / mot de passe sur votre page de connexion jusqu'à en trouver un valide.",
        "L'injection SQL : une donnée malveillante glissée dans un formulaire manipule votre base de données pour en extraire ou en détruire le contenu.",
        "Le XSS (cross-site scripting) : un script injecté s'exécute dans le navigateur de vos visiteurs pour voler leurs sessions ou leurs données.",
        "Les failles de plugins et de dépendances non mises à jour, qui représentent la première porte d'entrée réelle sur le terrain.",
        "Le phishing ciblant vos administrateurs pour récupérer directement leurs accès.",
      ]},
      { type: "h2", text: "Les mesures de protection de base" },
      { type: "p", text: "La sécurité n'est pas une option coûteuse réservée aux grandes entreprises. Quelques mesures fondamentales bloquent l'immense majorité des attaques automatisées, sans budget démesuré." },
      { type: "ul", items: [
        "Des mots de passe longs et uniques, associés à l'authentification à deux facteurs (MFA) sur tous les comptes d'administration.",
        "La mise à jour systématique du CMS, des extensions, des thèmes et des dépendances : une faille corrigée mais non déployée reste exploitable.",
        "Le HTTPS partout, pour chiffrer les échanges entre le navigateur et le serveur.",
        "Un pare-feu applicatif (WAF) qui filtre le trafic malveillant avant qu'il n'atteigne le site.",
        "La limitation des tentatives de connexion pour neutraliser le brute force.",
        "Des sauvegardes régulières et testées, seule véritable assurance en cas de compromission.",
      ]},
      { type: "h2", text: "Le principe du moindre privilège" },
      { type: "p", text: "Beaucoup de dégâts viennent de comptes qui disposent de bien plus de droits que nécessaire. Un rédacteur n'a pas besoin d'accéder aux réglages serveur, et une clé d'API dédiée à l'envoi d'e-mails n'a rien à faire dans la gestion des paiements. Attribuez à chaque compte, chaque service et chaque clé le strict minimum de permissions dont ils ont besoin. Le jour où l'un d'eux est compromis, l'attaquant reste cantonné à un périmètre réduit." },
      { type: "cta", text: "Vous voulez un site protégé sans devenir expert en cybersécurité ?", href: "/services/securite-web", label: "Découvrir notre offre Sécurité web" },
      { type: "h2", text: "Que faire si votre site est piraté ?" },
      { type: "p", text: "La panique est mauvaise conseillère. Un piratage se gère par étapes, dans l'ordre, pour reprendre le contrôle sans détruire les preuves ni aggraver la situation." },
      { type: "ul", items: [
        "Isoler : mettez le site en maintenance ou hors ligne pour stopper la propagation et protéger les visiteurs.",
        "Changer tous les mots de passe et clés d'API, en partant du principe qu'ils sont compromis.",
        "Identifier le point d'entrée à partir des journaux (logs) avant toute restauration, sinon la faille sera réexploitée.",
        "Restaurer depuis une sauvegarde saine antérieure à l'intrusion, puis appliquer immédiatement les correctifs manquants.",
        "Notifier : si des données personnelles ont fuité, le RGPD impose de prévenir la CNIL sous 72 heures.",
      ]},
      { type: "h2", text: "La sécurité est un processus, pas un produit" },
      { type: "p", text: "On ne sécurise pas un site une fois pour toutes. Les menaces évoluent, de nouvelles failles apparaissent chaque semaine et vos dépendances vieillissent. La vraie protection tient à une hygiène régulière : surveiller, mettre à jour, sauvegarder et tester. C'est cette discipline, bien plus qu'un outil miracle, qui distingue un site solide d'une cible facile." },
    ],
    faq: [
      { q: "Mon petit site vitrine risque-t-il vraiment d'être piraté ?", a: "Oui. La majorité des attaques sont automatisées et ne visent personne en particulier : des robots scannent le web à la recherche de failles connues. Un site vitrine sans données sensibles peut être détourné pour héberger du spam, du phishing ou miner de la cryptomonnaie, ce qui pénalise aussi votre référencement." },
      { q: "L'authentification à deux facteurs suffit-elle à protéger mon site ?", a: "Elle bloque l'essentiel des attaques sur les accès administrateur, mais ne protège pas contre les failles applicatives comme l'injection SQL ou le XSS. La sécurité repose sur plusieurs couches complémentaires : mots de passe forts et MFA, mises à jour, pare-feu applicatif et sauvegardes." },
      { q: "Combien coûte la sécurisation d'un site web ?", a: "Les mesures de base (MFA, mises à jour, HTTPS, limitation des connexions) ne coûtent presque rien à part du temps. Un pare-feu applicatif et une supervision managée représentent quelques dizaines d'euros par mois. À comparer au coût réel d'un piratage : perte de données, indisponibilité, atteinte à la réputation et sanctions." },
      { q: "Combien de temps faut-il pour remettre en ligne un site piraté ?", a: "Avec une sauvegarde saine et récente, la restauration prend quelques heures. Sans sauvegarde, il faut nettoyer le site manuellement, ce qui peut prendre plusieurs jours sans garantie d'éliminer entièrement l'intrusion. La sauvegarde est ce qui fait toute la différence." },
      { q: "Comment savoir si mon site a été piraté ?", a: "Les signaux classiques : alerte de Google Search Console, redirections inattendues, ralentissement, apparition de pages ou de fichiers inconnus, e-mails de spam envoyés depuis votre serveur, ou un avertissement de sécurité affiché aux visiteurs. Un scan de sécurité permet de confirmer et de localiser l'infection." },
    ],
  },
  {
    slug: "certificat-ssl-https-guide",
    title: "Certificat SSL et HTTPS : le guide complet 2026",
    description:
      "À quoi servent SSL et HTTPS, leur impact sur le SEO et la confiance, comment obtenir et renouveler un certificat, et pourquoi activer HSTS.",
    date: "2026-07-06",
    readingTime: "8 min",
    category: "Sécurité Web",
    keywords: [
      "certificat SSL",
      "HTTPS site web",
      "passer en HTTPS",
      "SSL gratuit Let's Encrypt",
    ],
    related: [
      { href: "/services/securite-web", label: "Sécurité web" },
      { href: "/services/seo", label: "SEO technique" },
    ],
    content: [
      { type: "p", text: "Le petit cadenas dans la barre d'adresse est devenu un réflexe de confiance pour les internautes. Derrière lui se cache un certificat SSL qui chiffre les échanges entre le navigateur et votre serveur. Aujourd'hui, un site sans HTTPS est marqué comme non sécurisé par les navigateurs et pénalisé par Google. Voici tout ce qu'il faut comprendre pour être en règle." },
      { type: "h2", text: "SSL, TLS, HTTPS : de quoi parle-t-on ?" },
      { type: "p", text: "Ces termes sont souvent confondus. SSL est l'ancien protocole de chiffrement, aujourd'hui remplacé par TLS, plus sûr, mais l'usage a conservé le nom SSL. HTTPS désigne simplement le protocole web HTTP protégé par ce chiffrement. Concrètement, un certificat SSL/TLS permet de chiffrer les données en transit et d'authentifier votre serveur auprès du navigateur." },
      { type: "h2", text: "À quoi sert vraiment le HTTPS" },
      { type: "p", text: "Le chiffrement ne protège pas votre site des piratages, mais il protège les données qui circulent entre vos visiteurs et vous. Sans lui, tout ce qui transite peut être intercepté et lu en clair, notamment sur les réseaux Wi-Fi publics." },
      { type: "ul", items: [
        "Confidentialité : mots de passe, coordonnées et paiements sont illisibles pour un tiers qui intercepterait le trafic.",
        "Intégrité : personne ne peut modifier le contenu de la page en cours de route (injection de publicités, altération de formulaires).",
        "Authenticité : le certificat garantit à l'internaute qu'il parle bien à votre serveur et non à un imposteur.",
      ]},
      { type: "h2", text: "Impact sur le SEO et la confiance" },
      { type: "p", text: "Google considère le HTTPS comme un signal de classement depuis des années : à contenu équivalent, un site sécurisé est favorisé. Surtout, l'absence de HTTPS déclenche l'affichage d'un avertissement non sécurisé qui fait fuir les visiteurs avant même qu'ils ne lisent votre page. Sur un site marchand, c'est une hémorragie directe de conversions. Le HTTPS n'est donc pas qu'une affaire technique : c'est un enjeu de crédibilité et de chiffre d'affaires." },
      { type: "h2", text: "Obtenir un certificat, gratuit ou payant" },
      { type: "p", text: "Pour l'immense majorité des sites, un certificat gratuit suffit. Le choix dépend surtout de votre niveau de vérification souhaité." },
      { type: "ul", items: [
        "Let's Encrypt : gratuit, automatisé, renouvelé tous les 90 jours, parfaitement adapté aux sites vitrines et boutiques.",
        "Certificats DV (Domain Validation) : ils vérifient uniquement que vous contrôlez le domaine, suffisant dans la plupart des cas.",
        "Certificats OV/EV (Organisation / Extended Validation) : payants, ils vérifient l'identité juridique de l'entreprise, utiles pour des banques ou institutions.",
        "Chez la plupart des hébergeurs modernes, le certificat est fourni et renouvelé automatiquement, sans manipulation de votre part.",
      ]},
      { type: "cta", text: "Vous voulez un site en HTTPS, sans erreur de configuration ?", href: "/services/securite-web", label: "Découvrir notre offre Sécurité web" },
      { type: "h2", text: "Renouvellement et pièges à éviter" },
      { type: "p", text: "La plupart des incidents HTTPS ne viennent pas du certificat lui-même mais de sa configuration. Un certificat expiré affiche une page d'erreur alarmante qui bloque totalement l'accès au site." },
      { type: "ul", items: [
        "Automatisez le renouvellement : un certificat oublié qui expire un dimanche soir peut couper votre site pour tout le week-end.",
        "Corrigez le contenu mixte : une image ou un script chargé en HTTP sur une page HTTPS casse le cadenas et affiche un avertissement.",
        "Mettez en place des redirections 301 de HTTP vers HTTPS pour n'exposer qu'une seule version au référencement.",
        "Vérifiez que le certificat couvre bien toutes vos variantes de domaine (avec et sans www, sous-domaines).",
      ]},
      { type: "h2", text: "Aller plus loin avec HSTS" },
      { type: "p", text: "Une fois le HTTPS en place, l'en-tête HSTS (HTTP Strict Transport Security) indique au navigateur de toujours se connecter en HTTPS, même si l'utilisateur tape l'adresse en HTTP. Cela ferme une fenêtre d'attaque subtile où un pirate tenterait de rétrograder la connexion vers du non chiffré. Bien configuré, HSTS est la touche finale d'un déploiement HTTPS sérieux." },
    ],
    faq: [
      { q: "Un certificat SSL gratuit vaut-il un certificat payant ?", a: "Sur le plan du chiffrement, oui : un certificat Let's Encrypt gratuit offre exactement le même niveau de sécurité qu'un certificat DV payant. La différence porte uniquement sur la vérification d'identité et la garantie commerciale. Pour un site vitrine ou une boutique, le gratuit est parfaitement adapté." },
      { q: "Le passage en HTTPS peut-il faire chuter mon référencement ?", a: "Non, à condition de le faire proprement : redirections 301 de chaque URL HTTP vers son équivalent HTTPS, mise à jour du sitemap et déclaration de la nouvelle version dans Search Console. Une migration bâclée, avec du contenu mixte ou des redirections manquantes, peut en revanche nuire temporairement au SEO." },
      { q: "Que se passe-t-il quand un certificat SSL expire ?", a: "Le navigateur affiche une page d'avertissement plein écran qui empêche l'accès normal au site, faisant fuir la quasi-totalité des visiteurs. C'est pourquoi le renouvellement automatique est essentiel : un certificat oublié coûte cher en trafic et en réputation." },
      { q: "Le HTTPS protège-t-il mon site contre le piratage ?", a: "Non, et c'est une confusion fréquente. Le HTTPS chiffre les données en transit entre le visiteur et le serveur, mais ne protège pas contre les injections, le brute force ou les failles de plugins. C'est une brique indispensable de la sécurité, pas une protection globale." },
      { q: "Faut-il activer HSTS sur tous les sites ?", a: "C'est recommandé dès que le HTTPS est stable sur l'ensemble du site. HSTS force le navigateur à utiliser HTTPS en permanence et bloque les tentatives de rétrogradation. Il faut simplement s'assurer, avant de l'activer, que tout le site fonctionne sans erreur en HTTPS, car HSTS est difficile à annuler côté navigateur." },
    ],
  },
  {
    slug: "sauvegarde-site-web-strategie",
    title: "Sauvegarde de site web : la stratégie qui vous sauve",
    description:
      "La règle 3-2-1, la bonne fréquence de sauvegarde, l'importance de tester la restauration, le plan de reprise et le coût réel d'une perte de données.",
    date: "2026-07-05",
    readingTime: "8 min",
    category: "Sécurité Web",
    keywords: [
      "sauvegarde site web",
      "backup site internet",
      "stratégie de sauvegarde",
      "restaurer un site",
    ],
    related: [
      { href: "/services/securite-web", label: "Sécurité web" },
      { href: "/services/creation-site-web", label: "Création de site web" },
    ],
    content: [
      { type: "p", text: "La sauvegarde est la mesure de sécurité la plus sous-estimée et pourtant la plus décisive. Quand un site est piraté, corrompu par une mise à jour ratée ou supprimé par erreur, seule une sauvegarde saine permet de repartir. Le problème, c'est qu'une sauvegarde qu'on n'a jamais testée n'en est pas vraiment une. Voici comment bâtir une stratégie qui tient réellement." },
      { type: "h2", text: "La règle 3-2-1, référence universelle" },
      { type: "p", text: "C'est le standard reconnu de la sauvegarde, simple à retenir et redoutablement efficace. Elle protège contre presque tous les scénarios de perte." },
      { type: "ul", items: [
        "3 copies de vos données : l'original et deux sauvegardes.",
        "2 supports différents : par exemple un stockage cloud et un disque local, pour ne pas dépendre d'une seule technologie.",
        "1 copie hors site : dans un lieu ou un service distinct, à l'abri d'un incendie, d'un vol ou d'un ransomware qui chiffrerait tout au même endroit.",
      ]},
      { type: "h2", text: "Ce qu'il faut réellement sauvegarder" },
      { type: "p", text: "Un site n'est pas qu'un ensemble de fichiers. Une sauvegarde incomplète donne une fausse impression de sécurité jusqu'au jour de la restauration, où l'on découvre qu'il manque l'essentiel." },
      { type: "ul", items: [
        "La base de données : contenus, commandes, comptes utilisateurs, réglages. C'est souvent le plus critique et le plus difficile à reconstituer.",
        "Les fichiers du site : code, thèmes, extensions et surtout les médias téléversés (images, documents).",
        "Les fichiers de configuration et les variables d'environnement, sans lesquels le site ne redémarre pas correctement.",
        "Les certificats et paramètres serveur, pour une remise en ligne rapide sur une nouvelle infrastructure si besoin.",
      ]},
      { type: "h2", text: "À quelle fréquence sauvegarder ?" },
      { type: "p", text: "La bonne fréquence dépend de la vitesse à laquelle vos données changent. La question à se poser est simple : combien de données puis-je me permettre de perdre ? Un site vitrine modifié une fois par mois se contente d'une sauvegarde hebdomadaire. Une boutique en ligne qui enregistre des commandes en continu a besoin de sauvegardes quotidiennes, voire de plusieurs sauvegardes par jour aux heures de forte activité. Perdre une journée de commandes n'a pas le même impact selon l'activité." },
      { type: "cta", text: "Vous voulez des sauvegardes automatiques et testées, sans y penser ?", href: "/services/securite-web", label: "Découvrir notre offre Sécurité web" },
      { type: "h2", text: "Le piège : ne jamais tester la restauration" },
      { type: "p", text: "C'est l'erreur qui coûte le plus cher. Beaucoup d'entreprises sauvegardent religieusement pendant des années, puis découvrent le jour de l'incident que les archives sont corrompues, incomplètes ou impossibles à restaurer. Une sauvegarde n'existe vraiment que le jour où vous avez prouvé qu'elle se restaure. Testez la procédure régulièrement, sur un environnement de test, pour valider à la fois l'intégrité des données et le temps nécessaire à la remise en ligne." },
      { type: "h2", text: "Du backup au plan de reprise (PRA)" },
      { type: "p", text: "La sauvegarde répond à la question quoi restaurer ; le plan de reprise d'activité (PRA) répond à comment et en combien de temps. Un PRA définit deux objectifs clés : le RPO (quantité maximale de données que l'on accepte de perdre) et le RTO (durée maximale d'indisponibilité tolérée). Ces deux chiffres, décidés en fonction de votre activité, dictent votre fréquence de sauvegarde et votre organisation de secours. Sans eux, on improvise dans l'urgence, au pire moment." },
      { type: "h2", text: "Le coût réel d'une perte de données" },
      { type: "p", text: "On perçoit souvent la sauvegarde comme une dépense superflue, jusqu'à l'incident. Le coût d'une perte de données ne se limite pas à la reconstruction technique : il inclut le chiffre d'affaires perdu pendant l'indisponibilité, la reconstitution manuelle des contenus, la perte de commandes et de comptes clients, et l'atteinte à la réputation. Face à cela, le coût d'une stratégie de sauvegarde automatisée est dérisoire. C'est l'assurance la moins chère et la plus rentable de tout votre dispositif de sécurité." },
    ],
    faq: [
      { q: "Que signifie concrètement la règle 3-2-1 ?", a: "Elle recommande de conserver 3 copies de vos données, sur 2 types de supports différents, dont 1 copie stockée hors site. Cette redondance protège contre la panne d'un support, l'erreur humaine et les sinistres comme un incendie ou un ransomware qui chiffrerait tout au même endroit." },
      { q: "À quelle fréquence dois-je sauvegarder mon site ?", a: "Cela dépend du rythme de changement de vos données. Un site vitrine peu modifié se contente d'une sauvegarde hebdomadaire, tandis qu'une boutique en ligne avec des commandes quotidiennes a besoin d'au moins une sauvegarde par jour. La bonne question est : combien de données puis-je accepter de perdre ?" },
      { q: "Pourquoi tester la restauration de mes sauvegardes ?", a: "Parce qu'une sauvegarde jamais testée peut être corrompue, incomplète ou impossible à restaurer, et on ne le découvre alors qu'au pire moment. Tester régulièrement la restauration sur un environnement de test valide l'intégrité des données et vous donne une estimation fiable du temps de remise en ligne." },
      { q: "Quelle différence entre une sauvegarde et un plan de reprise (PRA) ?", a: "La sauvegarde est une copie de vos données. Le plan de reprise d'activité organise la remise en service : il fixe la quantité de données que l'on accepte de perdre (RPO) et la durée maximale d'indisponibilité tolérée (RTO), et décrit la procédure complète pour redémarrer rapidement après un incident." },
      { q: "Les sauvegardes de mon hébergeur suffisent-elles ?", a: "Elles constituent un bon filet de sécurité, mais dépendre uniquement d'elles est risqué : elles sont stockées au même endroit que votre site et peuvent être limitées en fréquence ou en durée de conservation. Une copie indépendante et hors site, conforme à la règle 3-2-1, reste indispensable." },
    ],
  },
  {
    slug: "securiser-wordpress-checklist",
    title: "Sécuriser WordPress : la checklist complète 2026",
    description:
      "Pourquoi WordPress est autant ciblé, la checklist de sécurité indispensable (mises à jour, MFA, limitation des connexions, WAF, sauvegardes) et quand envisager une migration.",
    date: "2026-07-04",
    readingTime: "9 min",
    category: "Sécurité Web",
    keywords: [
      "sécuriser WordPress",
      "checklist sécurité WordPress",
      "WordPress piraté",
      "plugins sécurité WordPress",
    ],
    related: [
      { href: "/services/securite-web", label: "Sécurité web" },
      { href: "/blog/nextjs-ou-wordpress-que-choisir", label: "Next.js ou WordPress" },
    ],
    content: [
      { type: "p", text: "WordPress fait tourner une grande partie du web, ce qui en fait la cible favorite des pirates : trouver une faille sur WordPress, c'est pouvoir l'exploiter sur des millions de sites d'un coup. La bonne nouvelle, c'est qu'un WordPress correctement configuré et entretenu est parfaitement sûr. Le danger vient presque toujours de la négligence, pas du logiciel lui-même. Voici la checklist qui fait la différence." },
      { type: "h2", text: "Pourquoi WordPress est autant ciblé" },
      { type: "p", text: "La popularité de WordPress est à la fois sa force et son talon d'Achille. Comprendre d'où viennent réellement les attaques aide à concentrer les efforts au bon endroit." },
      { type: "ul", items: [
        "Sa part de marché énorme rend chaque faille exploitable à grande échelle, ce qui motive les attaquants.",
        "L'écosystème de plugins et de thèmes tiers est la première source de failles réelles, notamment les extensions abandonnées.",
        "Les installations mal entretenues (jamais mises à jour) laissent des vulnérabilités connues ouvertes pendant des mois.",
        "Les mots de passe faibles sur des comptes admin nommés admin restent une porte d'entrée classique pour le brute force.",
      ]},
      { type: "h2", text: "La checklist de sécurité essentielle" },
      { type: "p", text: "La grande majorité des piratages WordPress auraient été évités par ces quelques mesures. Aucune n'est complexe, mais toutes doivent être appliquées et maintenues dans la durée." },
      { type: "ul", items: [
        "Mettre à jour sans délai le cœur de WordPress, les thèmes et les plugins ; supprimer tout ce qui est inutilisé.",
        "Activer l'authentification à deux facteurs (MFA) sur tous les comptes disposant de droits d'édition ou d'administration.",
        "Limiter les tentatives de connexion et masquer ou renommer la page de connexion pour freiner le brute force.",
        "Utiliser des mots de passe forts et bannir le compte admin par défaut au profit d'un identifiant unique.",
        "Installer un pare-feu applicatif (WAF) et un plugin de sécurité reconnu pour filtrer le trafic malveillant.",
        "Mettre en place des sauvegardes automatiques, externalisées et régulièrement testées.",
        "Retirer les droits d'écriture superflus sur les fichiers et désactiver l'éditeur de code intégré à l'administration.",
      ]},
      { type: "h2", text: "Les plugins de sécurité : utiles mais pas magiques" },
      { type: "p", text: "Un plugin de sécurité apporte une couche de protection appréciable : pare-feu, détection de malware, journalisation des connexions, limitation du brute force. Mais il ne remplace ni les mises à jour, ni les sauvegardes, ni une bonne hygiène des comptes. Multiplier les plugins de sécurité est même contre-productif : ils se marchent dessus, alourdissent le site et créent de nouvelles surfaces d'attaque. Un plugin sérieux, bien configuré, vaut mieux que trois installés à moitié." },
      { type: "cta", text: "Vous voulez un WordPress verrouillé et surveillé en continu ?", href: "/services/securite-web", label: "Découvrir notre offre Sécurité web" },
      { type: "h2", text: "Que faire si votre WordPress est piraté ?" },
      { type: "p", text: "Un WordPress compromis se reconnaît vite : redirections étranges, fichiers inconnus, spam envoyé depuis le serveur, alerte de Google. La marche à suivre reste la même que pour tout site : isoler, changer tous les accès, identifier la faille à partir des journaux, restaurer une sauvegarde saine puis appliquer les correctifs. Le point crucial est de ne pas se contenter de nettoyer les symptômes visibles : si la porte d'entrée n'est pas colmatée, la réinfection est quasi certaine dans les jours qui suivent." },
      { type: "h2", text: "Quand faut-il envisager une migration ?" },
      { type: "p", text: "WordPress reste un excellent choix pour beaucoup de projets. Mais si votre site accumule les plugins, subit des piratages à répétition ou souffre d'une maintenance lourde, une alternative moderne comme un site en Next.js peut réduire drastiquement la surface d'attaque : pas de base de données exposée en permanence, pas d'écosystème de plugins tiers à surveiller, un rendu statique difficile à pirater. La migration se justifie quand le coût de sécurisation et de maintenance de WordPress dépasse celui d'une refonte." },
    ],
    faq: [
      { q: "WordPress est-il moins sûr que les autres solutions ?", a: "Pas intrinsèquement. WordPress est surtout beaucoup plus ciblé en raison de sa popularité, et la majorité des piratages viennent de plugins non mis à jour ou de mots de passe faibles, pas du cœur du logiciel. Un WordPress bien entretenu et configuré est parfaitement sûr." },
      { q: "Quel plugin de sécurité choisir pour WordPress ?", a: "Un plugin reconnu offrant pare-feu, détection de malware et limitation des connexions couvre l'essentiel. Le plus important est de n'en installer qu'un seul, bien configuré : cumuler plusieurs plugins de sécurité crée des conflits, alourdit le site et augmente la surface d'attaque au lieu de la réduire." },
      { q: "Comment protéger la page de connexion de WordPress ?", a: "Activez l'authentification à deux facteurs, limitez le nombre de tentatives de connexion, utilisez des mots de passe forts et bannissez l'identifiant admin par défaut. Renommer ou masquer l'URL de connexion réduit aussi fortement le volume d'attaques automatisées par brute force." },
      { q: "Mon WordPress est piraté, dois-je tout supprimer et repartir de zéro ?", a: "Pas nécessairement. Si vous disposez d'une sauvegarde saine antérieure à l'intrusion, la restauration est plus rapide et plus fiable qu'un nettoyage manuel. L'essentiel est d'identifier et de colmater la faille d'origine avant de remettre en ligne, sinon la réinfection est quasi certaine." },
      { q: "Faut-il migrer de WordPress vers une autre technologie ?", a: "Cela se justifie quand le site cumule les plugins, subit des piratages répétés ou coûte cher à maintenir. Une solution moderne comme Next.js réduit fortement la surface d'attaque grâce à un rendu statique et à l'absence d'écosystème de plugins tiers. Mais pour beaucoup de projets, un WordPress bien tenu reste tout à fait adapté." },
    ],
  },
  {
    slug: "rgpd-securite-donnees-obligations",
    title: "RGPD et sécurité des données : vos obligations en 2026",
    description:
      "Les obligations de sécurité imposées par l'article 32 du RGPD, le rôle du chiffrement, la notification de violation sous 72 heures et les sanctions encourues.",
    date: "2026-07-03",
    readingTime: "9 min",
    category: "Sécurité Web",
    keywords: [
      "sécurité des données RGPD",
      "obligations sécurité RGPD",
      "protéger les données clients",
      "violation de données RGPD",
    ],
    related: [
      { href: "/services/securite-web", label: "Sécurité web" },
      { href: "/services/tracking-conformite", label: "Tracking & Conformité" },
    ],
    content: [
      { type: "p", text: "Beaucoup d'entreprises voient le RGPD comme une affaire de bandeaux cookies et de mentions légales. C'est une vision incomplète et dangereuse. Le RGPD impose aussi et surtout des obligations de sécurité : protéger les données personnelles que vous collectez est une exigence légale, pas une bonne pratique optionnelle. Un manquement peut coûter très cher, bien au-delà de la simple amende." },
      { type: "h2", text: "L'article 32, pierre angulaire de la sécurité RGPD" },
      { type: "p", text: "C'est l'article central en matière de sécurité. Il impose de mettre en œuvre des mesures techniques et organisationnelles appropriées pour garantir un niveau de sécurité adapté au risque. Le texte ne dicte pas une liste figée de mesures : il vous rend responsable de choisir celles qui conviennent à la sensibilité de vos données et aux menaces réelles. Cette approche par le risque signifie qu'un site collectant des données de santé n'a pas les mêmes exigences qu'un simple formulaire de contact." },
      { type: "h2", text: "Les mesures de sécurité attendues" },
      { type: "p", text: "L'article 32 cite explicitement plusieurs types de garanties. Elles constituent le socle attendu de tout responsable de traitement." },
      { type: "ul", items: [
        "Le chiffrement des données personnelles, en transit (HTTPS) comme au repos (base de données, sauvegardes).",
        "La pseudonymisation, qui limite la casse en cas de fuite en dissociant les données de l'identité directe.",
        "La garantie de confidentialité, d'intégrité et de disponibilité des systèmes dans la durée.",
        "La capacité à rétablir l'accès aux données après un incident, ce qui rejoint directement la stratégie de sauvegarde.",
        "Des procédures de test et d'évaluation régulières de l'efficacité des mesures mises en place.",
      ]},
      { type: "h2", text: "Le chiffrement, mesure phare" },
      { type: "p", text: "Le chiffrement occupe une place particulière dans le dispositif. Non seulement il protège les données, mais il atténue aussi vos obligations en cas de fuite : si des données volées sont chiffrées de façon robuste, elles restent illisibles pour l'attaquant, ce qui peut vous dispenser d'informer les personnes concernées. Chiffrer les données sensibles au repos, sécuriser les échanges en HTTPS et hasher les mots de passe ne sont donc pas de simples options techniques : ce sont des leviers de conformité directs." },
      { type: "cta", text: "Vous voulez une collecte de données conforme et sécurisée ?", href: "/services/securite-web", label: "Découvrir notre offre Sécurité web" },
      { type: "h2", text: "La notification de violation sous 72 heures" },
      { type: "p", text: "C'est l'obligation la plus mal connue et la plus risquée. En cas de violation de données personnelles, le RGPD impose un calendrier strict qu'il faut anticiper avant l'incident, car il est impossible de s'organiser dans l'urgence." },
      { type: "ul", items: [
        "Notifier la CNIL dans les 72 heures après avoir eu connaissance de la violation, sauf si celle-ci est peu susceptible d'engendrer un risque.",
        "Informer les personnes concernées sans délai lorsque la violation présente un risque élevé pour leurs droits et libertés.",
        "Documenter chaque violation dans un registre interne, même celles qui ne sont pas notifiées, pour prouver votre diligence.",
        "Tenir prête une procédure de réponse à incident, car le délai de 72 heures se compte en heures, pas en jours ouvrés.",
      ]},
      { type: "h2", text: "Les sanctions encourues" },
      { type: "p", text: "Le RGPD prévoit des amendes pouvant atteindre 20 millions d'euros ou 4 % du chiffre d'affaires annuel mondial, le montant le plus élevé étant retenu. Un manquement à la sécurité, comme une fuite de données due à une négligence, figure parmi les motifs les plus fréquemment sanctionnés par la CNIL. Mais l'amende n'est que la partie visible : une violation entraîne aussi une perte de confiance, une couverture médiatique défavorable et parfois des actions en justice de la part des personnes lésées. Investir dans la sécurité coûte toujours moins cher que réparer une fuite." },
      { type: "h2", text: "Sécurité et conformité, deux faces d'une même exigence" },
      { type: "p", text: "On ne peut pas être conforme au RGPD sans être sécurisé, ni durablement sécurisé sans documenter sa conformité. Les deux se renforcent : chiffrement, sauvegardes testées, gestion fine des accès et procédure de réponse à incident servent à la fois votre sécurité technique et votre obligation légale. Aborder le RGPD par la sécurité, plutôt que par les seules mentions juridiques, est la façon la plus solide de protéger votre entreprise et vos clients." },
    ],
    faq: [
      { q: "Le RGPD impose-t-il des mesures de sécurité précises ?", a: "L'article 32 impose des mesures techniques et organisationnelles appropriées au risque, sans dicter une liste figée. Il cite toutefois explicitement le chiffrement, la pseudonymisation, la garantie de confidentialité et d'intégrité, ainsi que la capacité à restaurer les données après incident. C'est à vous d'adapter ces mesures à la sensibilité de vos données." },
      { q: "Le chiffrement est-il obligatoire selon le RGPD ?", a: "Il n'est pas formellement obligatoire dans tous les cas, mais il est explicitement recommandé par l'article 32 et fortement attendu pour les données sensibles. Il présente un avantage majeur : des données chiffrées volées restent illisibles, ce qui peut vous dispenser d'informer les personnes concernées en cas de fuite." },
      { q: "Que faire en cas de violation de données personnelles ?", a: "Vous devez notifier la CNIL dans les 72 heures suivant la prise de connaissance de la violation, sauf si elle présente peu de risques, et informer les personnes concernées lorsque le risque est élevé. Chaque violation doit aussi être consignée dans un registre interne, même celles qui ne sont pas notifiées." },
      { q: "Quelles sanctions en cas de manquement à la sécurité ?", a: "Les amendes peuvent atteindre 20 millions d'euros ou 4 % du chiffre d'affaires annuel mondial, selon le montant le plus élevé. Au-delà de l'amende, une fuite entraîne une perte de confiance, une exposition médiatique et parfois des actions en justice. Les manquements à la sécurité figurent parmi les plus sanctionnés par la CNIL." },
      { q: "Le RGPD, c'est seulement les cookies et les mentions légales ?", a: "Non, c'est une vision réductrice et risquée. Le RGPD impose aussi de sécuriser concrètement les données collectées : chiffrement, contrôle des accès, sauvegardes, capacité de restauration et procédure de réponse à incident. La sécurité technique est une composante centrale de la conformité, pas un accessoire." },
    ],
  },
  {
    slug: "audit-securite-site-web",
    title: "Audit de sécurité d'un site web : ce qu'il couvre vraiment",
    description:
      "Ce que couvre un audit de sécurité, les outils utilisés, les en-têtes de sécurité (CSP, HSTS), le contrôle des dépendances et la fréquence recommandée.",
    date: "2026-07-02",
    readingTime: "8 min",
    category: "Sécurité Web",
    keywords: [
      "audit sécurité site web",
      "test de sécurité site",
      "pentest site internet",
      "vérifier la sécurité de son site",
    ],
    related: [
      { href: "/services/securite-web", label: "Sécurité web" },
      { href: "/services/seo", label: "SEO technique" },
    ],
    content: [
      { type: "p", text: "On ne peut pas protéger ce qu'on ne mesure pas. Un audit de sécurité fait l'état des lieux objectif de votre site : où sont les failles, quelles données sont exposées, quelles portes restent ouvertes. C'est l'étape qui transforme une sécurité approximative en une démarche pilotée. Voici ce qu'un audit sérieux couvre réellement, avec quels outils et à quelle fréquence." },
      { type: "h2", text: "Ce que couvre un audit de sécurité" },
      { type: "p", text: "Un bon audit ne se limite pas à lancer un scanner automatique. Il examine plusieurs couches, du serveur jusqu'au code applicatif, pour dresser une cartographie complète des risques." },
      { type: "ul", items: [
        "La surface d'attaque : ports ouverts, services exposés, pages d'administration accessibles, sous-domaines oubliés.",
        "Les vulnérabilités applicatives : injection SQL, XSS, failles d'authentification et de gestion des sessions.",
        "La configuration serveur et les en-têtes de sécurité HTTP.",
        "L'état des dépendances et des composants tiers (CMS, plugins, bibliothèques) au regard des failles connues.",
        "La gestion des accès et des secrets : mots de passe, clés d'API, permissions excessives.",
        "La conformité du HTTPS et des certificats.",
      ]},
      { type: "h2", text: "Les en-têtes de sécurité HTTP" },
      { type: "p", text: "Souvent négligés, les en-têtes de sécurité sont pourtant un moyen simple et gratuit de fermer plusieurs vecteurs d'attaque. Un audit vérifie systématiquement leur présence et leur configuration." },
      { type: "ul", items: [
        "Content-Security-Policy (CSP) : contrôle les sources de scripts autorisées et bloque l'exécution de code injecté (XSS).",
        "Strict-Transport-Security (HSTS) : force les connexions en HTTPS et empêche la rétrogradation vers du non chiffré.",
        "X-Content-Type-Options et X-Frame-Options : neutralisent le détournement de type de contenu et le clickjacking.",
        "Referrer-Policy et Permissions-Policy : limitent les fuites d'informations et l'accès aux API sensibles du navigateur.",
      ]},
      { type: "h2", text: "Audit automatisé, pentest, revue de code" },
      { type: "p", text: "Tous les audits ne se valent pas, et le bon niveau dépend de vos enjeux. Un scan automatisé détecte rapidement les vulnérabilités connues et les erreurs de configuration : c'est le point de départ accessible à tous. Un pentest (test d'intrusion) va plus loin : un expert tente activement de pénétrer le site comme le ferait un attaquant, révélant des failles logiques qu'aucun outil ne détecte. Enfin, la revue de code inspecte directement le code source pour repérer les vulnérabilités à la racine. Plus vos données sont sensibles, plus vous montez dans cette échelle." },
      { type: "cta", text: "Vous voulez savoir précisément où en est la sécurité de votre site ?", href: "/services/securite-web", label: "Demander un audit de sécurité" },
      { type: "h2", text: "Le maillon faible : les dépendances" },
      { type: "p", text: "La majorité des sites modernes reposent sur des dizaines, voire des centaines de bibliothèques tierces. Chacune peut contenir une faille, et une faille dans une dépendance devient une faille dans votre site. Un audit vérifie l'inventaire complet de ces composants et les confronte aux bases de vulnérabilités connues. Cette analyse doit être continue, pas ponctuelle : une bibliothèque sûre aujourd'hui peut voir une faille critique publiée demain. L'automatisation de cette surveillance est l'une des mesures au meilleur rapport effort / bénéfice." },
      { type: "h2", text: "À quelle fréquence auditer son site ?" },
      { type: "p", text: "Un audit n'est pas un examen qu'on passe une fois. La règle générale : un audit complet au moins une fois par an, et systématiquement après un changement majeur (refonte, migration, ajout d'une fonctionnalité sensible comme le paiement). La surveillance des dépendances et des en-têtes, elle, doit être continue et automatisée. Entre deux audits approfondis, cette veille permanente évite qu'une faille connue ne reste ouverte pendant des mois. C'est la combinaison des deux, ponctuel et continu, qui maintient un site réellement sûr dans la durée." },
    ],
    faq: [
      { q: "Quelle différence entre un scan automatisé et un pentest ?", a: "Un scan automatisé détecte rapidement les vulnérabilités connues et les erreurs de configuration à l'aide d'outils. Un pentest, ou test d'intrusion, va beaucoup plus loin : un expert tente activement de pénétrer le site comme le ferait un attaquant, ce qui révèle des failles logiques que les outils ne détectent pas. Le pentest se justifie quand vos données sont sensibles." },
      { q: "Que sont les en-têtes de sécurité HTTP ?", a: "Ce sont des instructions envoyées par le serveur au navigateur pour renforcer la sécurité. Les principaux sont la Content-Security-Policy (CSP) contre les injections de scripts, le HSTS pour forcer le HTTPS, ainsi que X-Frame-Options et X-Content-Type-Options contre le clickjacking et le détournement de contenu. Ils sont gratuits et très efficaces." },
      { q: "À quelle fréquence faut-il auditer la sécurité d'un site ?", a: "Un audit complet est recommandé au moins une fois par an, et systématiquement après un changement majeur comme une refonte, une migration ou l'ajout d'un module de paiement. La surveillance des dépendances et des en-têtes doit, elle, être continue et automatisée entre deux audits approfondis." },
      { q: "Pourquoi les dépendances tierces sont-elles un risque ?", a: "Un site moderne repose sur de nombreuses bibliothèques tierces, dont chacune peut contenir une faille. Une vulnérabilité dans une dépendance devient une vulnérabilité de votre site. Comme de nouvelles failles sont publiées en permanence, une bibliothèque sûre aujourd'hui peut devenir dangereuse demain, d'où l'importance d'une surveillance continue." },
      { q: "Un audit de sécurité a-t-il un intérêt pour le SEO ?", a: "Oui, indirectement mais réellement. Un site compromis peut être marqué comme dangereux par Google et déclassé, tandis que le HTTPS et une bonne configuration sont des signaux positifs. Sécuriser son site protège donc aussi sa visibilité, et un audit permet de corriger les points qui pénalisent à la fois la sécurité et le référencement." },
    ],
  },
];
