// Articles du theme Tracking & conformite. Meme structure que POSTS.
// Ajouter un objet ici cree /blog/<slug>, l'entree /blog et le sitemap.

import type { Post } from "./posts";

export const POSTS_TRACKING: Post[] = [
  {
    slug: "installer-google-analytics-4-rgpd",
    title: "Installer Google Analytics 4 en conformite RGPD (guide 2026)",
    description:
      "Comment installer GA4 proprement et conforme a la CNIL : consentement prealable, anonymisation, parametrage, et alternatives quand GA4 pose probleme.",
    date: "2026-07-13",
    readingTime: "9 min",
    category: "Tracking & conformité",
    keywords: [
      "installer GA4",
      "Google Analytics 4 RGPD",
      "GA4 conforme CNIL",
      "configurer GA4",
    ],
    related: [
      { href: "/services/tracking-conformite", label: "Tracking & Conformité" },
      { href: "/blog/consent-mode-v2-rgpd-cnil", label: "Consent Mode v2 RGPD/CNIL" },
    ],
    content: [
      { type: "p", text: "Google Analytics 4 a remplace Universal Analytics, et beaucoup d'installations reprises a la va-vite sont aujourd'hui non conformes. Le sujet est sensible : la CNIL a deja sanctionne des sites pour un usage d'Analytics juge illegal au regard du RGPD. Bonne nouvelle, GA4 peut s'installer proprement et rester exploitable, a condition de respecter quelques regles precises. Voici la methode qu'on applique, du consentement au parametrage." },
      { type: "h2", text: "Pourquoi GA4 pose un probleme de conformite" },
      { type: "p", text: "Le point de friction n'est pas GA4 en soi, mais le transfert de donnees personnelles vers les serveurs de Google, dont une partie peut etre traitee hors de l'Union europeenne. Le RGPD encadre strictement ce transfert, et la CNIL considere qu'un traitement de mesure d'audience a des fins marketing releve du consentement. Autrement dit : sans accord prealable de l'internaute, aucune donnee ne doit partir vers GA4." },
      { type: "ul", items: [
        "L'adresse IP et les identifiants de navigation sont des donnees personnelles au sens du RGPD.",
        "GA4 anonymise l'IP par defaut, mais cela ne suffit pas a lui seul a rendre l'outil conforme.",
        "La mesure d'audience deposant des cookies necessite le consentement, sauf exemption stricte de la CNIL.",
      ]},
      { type: "h2", text: "Regle n°1 : le consentement AVANT le tag" },
      { type: "p", text: "L'erreur la plus repandue consiste a charger le tag GA4 des l'arrivee sur la page, puis a afficher un bandeau cookies. C'est trop tard : les donnees sont deja parties. La bonne architecture bloque tout depot et tout envoi tant que l'internaute n'a pas donne son accord, via un bandeau de consentement (CMP) couple au Consent Mode de Google." },
      { type: "ul", items: [
        "Le tag GA4 ne se declenche qu'apres un accord explicite (aucune case pre-cochee).",
        "Refuser doit etre aussi simple qu'accepter : c'est une exigence formelle de la CNIL.",
        "Le Consent Mode permet a Google de modeliser une partie des donnees manquantes sans cookie, dans le respect du choix.",
        "Le choix de l'internaute est conserve et rejouable a chaque visite.",
      ]},
      { type: "h2", text: "Regle n°2 : un parametrage propre" },
      { type: "p", text: "Une fois le consentement gere, encore faut-il que GA4 soit configure correctement pour limiter la collecte au strict necessaire et rendre la mesure fiable. C'est la partie technique, souvent negligee, qui distingue une installation exploitable d'un empilement de tags." },
      { type: "ul", items: [
        "Desactiver les signaux Google (Google Signals) si vous n'en maitrisez pas les implications RGPD.",
        "Limiter la duree de conservation des donnees au minimum utile.",
        "Filtrer le trafic interne et les bots pour ne pas fausser les statistiques.",
        "Definir des conversions et des evenements cles clairs plutot qu'une collecte tous azimuts.",
      ]},
      { type: "h2", text: "Regle n°3 : documenter et informer" },
      { type: "p", text: "La conformite ne se limite pas au code. Il faut aussi une politique de confidentialite a jour qui mentionne GA4, sa finalite, la duree de conservation et les droits de l'internaute. En cas de controle, cette documentation fait la difference entre un site en regle et un site expose a une sanction." },
      { type: "cta", text: "Vous voulez un GA4 fiable ET conforme, installe proprement du premier coup ?", href: "/services/tracking-conformite", label: "Voir notre offre Tracking & Conformité" },
      { type: "h2", text: "Et si GA4 ne convient pas ? Les alternatives" },
      { type: "p", text: "Pour certains sites, notamment publics ou tres exposes, une alternative respectueuse de la vie privee peut etre preferable. Des outils de mesure d'audience sans cookie et heberges en Europe existent, et certains sont meme exemptes de consentement par la CNIL sous conditions strictes." },
      { type: "ul", items: [
        "Matomo (auto-heberge) offre un controle total sur les donnees, avec une configuration exemptable de consentement.",
        "Des solutions europeennes sans cookie (Plausible, Piano Analytics) simplifient la conformite.",
        "Le server-side tagging permet de garder GA4 tout en maitrisant ce qui est reellement envoye a Google.",
      ]},
      { type: "p", text: "En resume : GA4 n'est pas interdit, il est encadre. Une installation conforme repose sur trois piliers — consentement prealable, parametrage sobre, documentation a jour. Faites l'impasse sur l'un d'eux et vous exposez votre site a une sanction et a des donnees juridiquement fragiles. Faites-les bien, et vous obtenez une mesure d'audience exploitable et sereine." },
    ],
    faq: [
      { q: "GA4 est-il conforme au RGPD par defaut ?", a: "Non. GA4 anonymise l'IP par defaut, mais cela ne suffit pas. La conformite depend surtout de votre installation : consentement prealable via un bandeau, blocage du tag tant que l'internaute n'a pas accepte, parametrage sobre et politique de confidentialite a jour. Sans ces elements, l'usage de GA4 peut etre juge non conforme par la CNIL." },
      { q: "Faut-il le consentement pour installer Google Analytics 4 ?", a: "Oui, dans la quasi-totalite des cas. GA4 depose des cookies et transfere des donnees personnelles a des fins de mesure d'audience marketing, ce qui releve du consentement selon la CNIL. Le tag ne doit se declencher qu'apres un accord explicite, et refuser doit etre aussi simple qu'accepter." },
      { q: "Comment rendre GA4 conforme a la CNIL ?", a: "Bloquez le tag tant que le consentement n'est pas donne, couplez GA4 a une CMP et au Consent Mode, limitez la duree de conservation, filtrez le trafic interne, et documentez le traitement dans votre politique de confidentialite. Pour certains sites, une alternative sans cookie comme Matomo peut simplifier la conformite." },
      { q: "Quelle est la difference entre anonymisation IP et conformite RGPD ?", a: "L'anonymisation de l'IP reduit une donnee personnelle, mais la conformite RGPD couvre un perimetre bien plus large : base legale (consentement), information de l'internaute, duree de conservation, transferts hors UE. GA4 anonymise l'IP par defaut, ce qui est necessaire mais loin d'etre suffisant pour etre en regle." },
      { q: "Quelles alternatives a GA4 pour eviter les problemes RGPD ?", a: "Matomo auto-heberge donne un controle total et peut etre configure pour etre exempte de consentement. Des solutions europeennes sans cookie comme Plausible ou Piano Analytics simplifient aussi la conformite. Enfin, le server-side tagging permet de conserver GA4 tout en maitrisant precisement les donnees envoyees a Google." },
    ],
  },
  {
    slug: "bandeau-cookies-conforme-cnil",
    title: "Bandeau cookies conforme CNIL : les regles a respecter en 2026",
    description:
      "Refuser aussi simple qu'accepter, pas de depot avant consentement, CMP bien configuree : les regles CNIL d'un bandeau cookies conforme et les erreurs sanctionnees.",
    date: "2026-07-12",
    readingTime: "8 min",
    category: "Tracking & conformité",
    keywords: [
      "bandeau cookies CNIL",
      "CMP conforme",
      "consentement cookies RGPD",
      "cookie banner",
    ],
    related: [
      { href: "/services/tracking-conformite", label: "Tracking & Conformité" },
      { href: "/services/securite-web", label: "Sécurité web" },
    ],
    content: [
      { type: "p", text: "Le bandeau cookies est devenu un incontournable, mais beaucoup sont non conformes — et la CNIL sanctionne regulierement des sites, y compris de grands acteurs, pour des bandeaux trompeurs. Le probleme n'est presque jamais l'absence de bandeau : c'est un bandeau mal concu qui piege l'internaute au lieu de recueillir un vrai consentement. Voici les regles precises a respecter, et les pieges qui coutent cher." },
      { type: "h2", text: "La regle cardinale : refuser aussi simple qu'accepter" },
      { type: "p", text: "C'est le point que la CNIL verifie en premier, et celui qui declenche le plus de sanctions. Si accepter tous les cookies se fait en un clic, alors refuser doit aussi se faire en un clic, au meme niveau et avec la meme visibilite. Un bouton « Tout accepter » bien visible face a un « Refuser » cache derriere plusieurs menus n'est pas conforme : c'est un consentement extorque, pas libre." },
      { type: "ul", items: [
        "Un bouton « Tout refuser » aussi accessible et visible que « Tout accepter », des le premier ecran.",
        "Pas de design trompeur (dark pattern) qui rend le refus penible ou peu lisible.",
        "Continuer la navigation ne vaut PAS consentement : le silence ne peut pas etre interprete comme un accord.",
      ]},
      { type: "h2", text: "Aucun depot avant le choix" },
      { type: "p", text: "Tant que l'internaute n'a pas donne son accord, aucun cookie non essentiel ne doit etre depose, et aucun tag de mesure ou de publicite ne doit se declencher. C'est la faute technique la plus frequente : le bandeau s'affiche joliment, mais en coulisses GA4, le Pixel Meta et d'autres scripts se sont deja executes. Le bandeau devient alors un simple decor sans effet reel." },
      { type: "ul", items: [
        "Seuls les cookies strictement necessaires au fonctionnement du site sont autorises sans consentement.",
        "Les tags analytics, publicitaires et de reseaux sociaux restent bloques tant qu'il n'y a pas d'accord.",
        "Le blocage doit etre reel cote code, pas seulement visuel dans le bandeau.",
      ]},
      { type: "h2", text: "Un consentement libre, eclaire et granulaire" },
      { type: "p", text: "Le consentement doit etre une action positive et informee. L'internaute doit comprendre a quoi il consent et pouvoir choisir finalite par finalite, sans etre force d'accepter en bloc pour acceder au site." },
      { type: "ul", items: [
        "Aucune case pre-cochee : l'inaction ne vaut pas acceptation.",
        "Un choix par finalite (mesure d'audience, publicite, reseaux sociaux) et pas seulement un « tout ou rien ».",
        "Une information claire et accessible sur chaque categorie de cookies et leur duree.",
        "La possibilite de retirer son consentement aussi facilement qu'il a ete donne.",
      ]},
      { type: "h2", text: "La CMP : indispensable mais a bien configurer" },
      { type: "p", text: "Une CMP (Consent Management Platform) comme Axeptio, Didomi ou une solution equivalente gere l'affichage du bandeau, le recueil et la conservation des choix. Mais installer une CMP ne rend pas automatiquement conforme : mal configuree, elle laisse passer des tags avant consentement ou masque le bouton de refus. L'outil ne remplace pas un parametrage rigoureux." },
      { type: "cta", text: "Vous voulez un bandeau cookies reellement conforme, sans risque de sanction ?", href: "/services/tracking-conformite", label: "Voir notre offre Tracking & Conformité" },
      { type: "h2", text: "Les erreurs qui font sanctionner" },
      { type: "ul", items: [
        "« Tout accepter » en un clic mais « Refuser » cache en plusieurs etapes : la sanction la plus frequente.",
        "Des tags qui se declenchent avant que l'internaute ait fait son choix.",
        "Des cases pre-cochees ou un bandeau qui interprete la poursuite de navigation comme un accord.",
        "Une CMP installee mais mal configuree, qui donne une fausse impression de conformite.",
        "Aucune trace conservee des consentements, impossible a prouver en cas de controle.",
      ]},
      { type: "p", text: "Un bandeau cookies conforme n'est pas un obstacle a la mesure : bien concu, avec un Consent Mode et un parametrage propre, il permet de continuer a piloter son marketing tout en respectant la loi. Le vrai risque n'est pas de perdre quelques donnees, c'est la sanction et la perte de confiance qu'entraine un bandeau trompeur." },
    ],
    faq: [
      { q: "Un bandeau cookies suffit-il a etre conforme a la CNIL ?", a: "Non. La conformite depend de la maniere dont le bandeau est concu et configure : refuser doit etre aussi simple qu'accepter, aucun tag ne doit se declencher avant le consentement, aucune case ne doit etre pre-cochee, et les choix doivent etre conserves. Un bandeau present mais trompeur ou inefficace cote code reste non conforme." },
      { q: "Le bouton refuser doit-il etre aussi visible que accepter ?", a: "Oui, c'est une exigence centrale de la CNIL. Si accepter tous les cookies se fait en un clic des le premier ecran, refuser doit se faire dans les memes conditions, au meme niveau de visibilite. Un « Refuser » cache derriere plusieurs menus est l'une des causes les plus frequentes de sanction." },
      { q: "Peut-on deposer des cookies avant le consentement ?", a: "Uniquement les cookies strictement necessaires au fonctionnement du site. Tous les cookies de mesure d'audience, de publicite ou de reseaux sociaux doivent rester bloques tant que l'internaute n'a pas donne son accord. Le blocage doit etre reel dans le code, pas seulement visuel." },
      { q: "La poursuite de la navigation vaut-elle consentement ?", a: "Non. La CNIL est claire : continuer a naviguer ne peut pas etre interprete comme un accord. Le consentement doit resulter d'une action positive et explicite. Un bandeau qui considere le silence ou la poursuite de navigation comme une acceptation est non conforme." },
      { q: "Installer une CMP comme Axeptio ou Didomi rend-il conforme ?", a: "Pas automatiquement. Une CMP gere l'affichage, le recueil et la conservation des choix, mais une mauvaise configuration peut laisser passer des tags avant consentement ou masquer le refus. L'outil est indispensable, mais c'est son parametrage rigoureux qui rend le site reellement conforme." },
    ],
  },
  {
    slug: "server-side-tagging-gtm-guide",
    title: "Server-side tagging avec GTM : pourquoi, quand et combien ca coute",
    description:
      "Le tagging cote serveur avec GTM server améliore la fiabilité de la mesure et la conformité. Pourquoi l'adopter, quand il devient pertinent, et ce qu'il coute vraiment.",
    date: "2026-07-11",
    readingTime: "9 min",
    category: "Tracking & conformité",
    keywords: [
      "server-side tagging",
      "GTM server side",
      "tag serveur Google",
      "tracking côté serveur",
    ],
    related: [
      { href: "/services/tracking-conformite", label: "Tracking & Conformité" },
      { href: "/blog/deduplication-evenements-pixel-capi", label: "Déduplication Pixel / CAPI" },
    ],
    content: [
      { type: "p", text: "Le server-side tagging n'est plus une technique de niche reservee aux grands comptes. Avec la disparition progressive des cookies tiers, les bloqueurs de publicite et les limitations des navigateurs, le tagging cote client perd chaque annee une part croissante des donnees. Le tagging cote serveur, notamment via GTM server, restaure une mesure fiable — tout en donnant plus de controle sur la conformite. Voici comment il fonctionne, quand il devient pertinent, et ce qu'il coute reellement." },
      { type: "h2", text: "Client-side vs server-side : la difference concrete" },
      { type: "p", text: "Dans un tagging classique (cote client), les tags — GA4, Pixel Meta, Google Ads — s'executent directement dans le navigateur de l'internaute. Ils envoient les donnees vers les plateformes depuis le poste de l'utilisateur. Dans un tagging cote serveur, le navigateur envoie d'abord les donnees a VOTRE serveur (un conteneur GTM server), qui les redistribue ensuite aux plateformes. Cette etape intermediaire change tout." },
      { type: "ul", items: [
        "Client-side : les tags s'executent dans le navigateur, exposes aux bloqueurs et aux limitations ITP de Safari.",
        "Server-side : le navigateur parle a votre serveur, qui parle aux plateformes — vous reprenez la main sur le flux.",
        "GTM server est un conteneur Google Tag Manager qui tourne sur votre propre infrastructure cloud.",
      ]},
      { type: "h2", text: "Benefice n°1 : la fiabilite de la mesure" },
      { type: "p", text: "C'est la premiere raison d'adopter le server-side. En passant par votre serveur, les evenements echappent en grande partie aux bloqueurs de publicite et aux restrictions des navigateurs qui coupent le tagging cote client. Vous recuperez ainsi des conversions autrement perdues, et l'optimisation des plateformes publicitaires s'ameliore, faute de quoi elle cible sur des donnees incompletes." },
      { type: "ul", items: [
        "Moins de pertes dues aux bloqueurs et aux navigateurs stricts (Safari, Firefox).",
        "Des cookies first-party a duree de vie prolongee, la ou Safari limite fortement les cookies poses cote client.",
        "Une mesure plus stable, donc des budgets publicitaires pilotes sur des chiffres justes.",
      ]},
      { type: "h2", text: "Benefice n°2 : la conformite et la maitrise des donnees" },
      { type: "p", text: "Le server-side donne un point de controle unique sur ce qui sort de votre site. Avant qu'une donnee ne parte vers Google ou Meta, elle transite par votre serveur, ou vous pouvez la filtrer, l'anonymiser ou la bloquer. C'est un atout majeur pour le RGPD : vous decidez precisement quelles donnees sont transmises, a qui, et vous evitez de charger dans le navigateur des scripts tiers opaques." },
      { type: "ul", items: [
        "Filtrage des donnees sensibles avant transmission aux plateformes.",
        "Reduction du nombre de scripts tiers charges dans le navigateur (meilleure performance et surface d'attaque reduite).",
        "Un point unique pour appliquer le consentement de maniere coherente sur tous les tags.",
        "Attention : le server-side ne dispense JAMAIS du consentement — il le rend plus facile a maitriser, pas optionnel.",
      ]},
      { type: "h2", text: "Quand le server-side devient pertinent" },
      { type: "p", text: "Le server-side a un cout et une complexite qui ne se justifient pas pour tous les sites. Il devient reellement rentable au-dela d'un certain volume ou d'une certaine dependance a la publicite payante." },
      { type: "ul", items: [
        "Vous investissez de maniere significative en Google Ads ou Meta Ads et la perte de conversions vous coute cher.",
        "Vous constatez un ecart important entre les ventes reelles et les conversions remontees dans vos plateformes.",
        "Vous avez des exigences fortes de conformite (secteur regule, DPO exigeant, gros trafic europeen).",
        "A l'inverse, pour un petit site vitrine sans budget pub, le tagging cote client bien configure suffit.",
      ]},
      { type: "cta", text: "Vous voulez un server-side tagging fiable, sans usine a gaz ni surcout inutile ?", href: "/services/tracking-conformite", label: "Voir notre offre Tracking & Conformité" },
      { type: "h2", text: "Combien ca coute reellement ?" },
      { type: "p", text: "Deux postes sont a distinguer. D'abord l'infrastructure : GTM server tourne sur un serveur cloud (Google Cloud ou un equivalent), dont le cout depend du trafic — souvent quelques dizaines d'euros par mois pour une PME, davantage sur des sites a fort volume. Ensuite la mise en place : la configuration du conteneur serveur, la migration des tags et la deduplication demandent une expertise, avec un cout d'installation unique. Ce n'est pas un abonnement a vie : une fois en place, seul l'hebergement court." },
      { type: "p", text: "Le server-side tagging est un investissement, pas un gadget. Il se justifie des lors que la perte de conversions cote client vous coute plus que le cout de sa mise en place — ce qui arrive vite pour un annonceur actif. Mal configure, il ajoute de la complexite sans benefice ; bien pense, il restaure une mesure fiable et vous rend maitre de vos donnees." },
    ],
    faq: [
      { q: "Qu'est-ce que le server-side tagging ?", a: "C'est une methode ou les tags de mesure (GA4, Pixel Meta, Google Ads) ne s'executent plus directement dans le navigateur, mais transitent d'abord par votre propre serveur — un conteneur GTM server — qui redistribue ensuite les donnees aux plateformes. Cela restaure une mesure plus fiable et donne le controle sur les donnees transmises." },
      { q: "Le server-side tagging ameliore-t-il vraiment la fiabilite ?", a: "Oui. En passant par votre serveur, les evenements echappent en grande partie aux bloqueurs de publicite et aux restrictions des navigateurs comme Safari qui coupent le tagging cote client. Vous recuperez des conversions autrement perdues et les plateformes publicitaires optimisent sur des donnees plus completes." },
      { q: "Le tagging cote serveur dispense-t-il du consentement RGPD ?", a: "Non, jamais. Le fait que les donnees partent du serveur ne supprime pas l'obligation de consentement pour un traitement a des fins de mesure ou de publicite. Le server-side facilite au contraire l'application coherente du consentement, mais il ne le rend en aucun cas optionnel." },
      { q: "Quand faut-il passer au server-side tagging ?", a: "Il devient pertinent quand vous investissez significativement en publicite payante, quand vous constatez un ecart important entre ventes reelles et conversions remontees, ou quand vous avez de fortes exigences de conformite. Pour un petit site vitrine sans budget pub, un tagging cote client bien configure reste suffisant." },
      { q: "Combien coute un server-side tagging avec GTM server ?", a: "Il y a deux postes : l'infrastructure cloud (souvent quelques dizaines d'euros par mois pour une PME, selon le trafic) et la mise en place (un cout d'installation unique pour configurer le conteneur, migrer les tags et gerer la deduplication). Ce n'est pas un abonnement a vie : une fois en place, seul l'hebergement court." },
    ],
  },
  {
    slug: "mesurer-conversions-sans-cookies-tiers",
    title: "Mesurer ses conversions sans cookies tiers : preparer l'apres-cookie",
    description:
      "Les cookies tiers disparaissent. Comment continuer a mesurer ses conversions grace au first-party, au server-side et a la modélisation, et preparer l'avenir sereinement.",
    date: "2026-07-10",
    readingTime: "8 min",
    category: "Tracking & conformité",
    keywords: [
      "mesurer conversions sans cookies",
      "fin cookies tiers",
      "first-party data",
      "tracking sans cookies",
    ],
    related: [
      { href: "/services/tracking-conformite", label: "Tracking & Conformité" },
      { href: "/blog/tracking-conversions-ios-att", label: "Tracking iOS & ATT" },
    ],
    content: [
      { type: "p", text: "La fin des cookies tiers n'est plus une menace lointaine : elle est deja largement engagee. Safari et Firefox les bloquent depuis des annees, et l'ecosysteme publicitaire tout entier se reorganise autour de la donnee first-party. Pour beaucoup d'annonceurs, cela signifie une chose : les methodes de mesure d'hier ne fonctionnent plus, et il faut reconstruire un suivi de conversions fiable sur de nouvelles bases. Voici comment mesurer sans cookies tiers et preparer l'avenir." },
      { type: "h2", text: "Cookie tiers vs first-party : ne pas confondre" },
      { type: "p", text: "La confusion est frequente, et pourtant tout se joue la. Un cookie tiers est depose par un domaine different de celui du site visite (une regie publicitaire, par exemple) et sert a suivre l'utilisateur d'un site a l'autre. C'est lui qui disparait. Un cookie first-party, lui, est depose par le site que vous visitez et reste parfaitement utilisable — c'est sur lui qu'il faut desormais s'appuyer." },
      { type: "ul", items: [
        "Cookie tiers : depose par un domaine externe, sert au suivi cross-site — en voie de disparition.",
        "Cookie first-party : depose par votre propre site, toujours valide et central pour la mesure.",
        "La bascule vers le first-party n'est pas optionnelle : c'est le socle de toute mesure post-cookie.",
      ]},
      { type: "h2", text: "Pilier n°1 : la donnee first-party" },
      { type: "p", text: "La donnee first-party, ce sont les informations que vos utilisateurs vous confient directement : email a l'inscription, achat, compte client, formulaire. C'est la matiere premiere la plus fiable et la plus perenne, car elle ne depend d'aucun cookie tiers. La collecter proprement, avec consentement, devient un avantage concurrentiel majeur." },
      { type: "ul", items: [
        "Collecter emails et donnees de compte avec consentement, dans une logique de valeur (newsletter, avantages).",
        "Structurer un CRM propre qui centralise ces donnees exploitables durablement.",
        "Transmettre ces signaux aux plateformes de maniere hashee et conforme (Advanced Matching, Customer Match).",
      ]},
      { type: "h2", text: "Pilier n°2 : le server-side et la CAPI" },
      { type: "p", text: "Une fois la donnee first-party collectee, il faut la remonter aux plateformes sans dependre du navigateur. C'est le role du tagging cote serveur et des API de conversions comme la CAPI de Meta ou l'API de Google Ads. Elles envoient les evenements directement depuis votre serveur, avec des cookies first-party a duree prolongee, ce qui restaure une grande partie de la mesure perdue." },
      { type: "ul", items: [
        "Le server-side tagging fait transiter les evenements par votre serveur, a l'abri des bloqueurs.",
        "Les API de conversions (Meta CAPI, Google Ads API) transmettent les achats et leads cote serveur.",
        "La deduplication reste indispensable pour ne pas compter deux fois un evenement envoye par deux canaux.",
      ]},
      { type: "h2", text: "Pilier n°3 : la modélisation et les conversions augmentees" },
      { type: "p", text: "Meme avec du first-party et du server-side, une part de la mesure reste manquante — les utilisateurs qui refusent le consentement, notamment. Les plateformes comblent ce trou par la modélisation : a partir des donnees observees et du Consent Mode, elles estiment statistiquement les conversions non mesurees. Ce n'est pas de la magie, mais un complement precieux quand il est bien alimente." },
      { type: "ul", items: [
        "Le Consent Mode de Google alimente la modélisation avec des signaux anonymises quand l'utilisateur refuse.",
        "Les conversions augmentees (Enhanced Conversions) enrichissent la mesure avec des donnees first-party hashees.",
        "Plus vos signaux consentis sont nombreux et propres, plus la modélisation est fiable.",
      ]},
      { type: "cta", text: "Vous voulez preparer votre mesure a l'apres-cookie sans perdre en fiabilite ?", href: "/services/tracking-conformite", label: "Voir notre offre Tracking & Conformité" },
      { type: "h2", text: "Preparer l'avenir des maintenant" },
      { type: "p", text: "L'erreur serait d'attendre la disparition totale des cookies tiers pour reagir. Les annonceurs qui prennent de l'avance construisent des maintenant leur socle first-party, migrent vers le server-side et activent la modélisation — pendant que les cookies tiers survivants leur permettent encore de calibrer et comparer. Ceux qui attendent decouvriront un jour une mesure effondree, sans base de repli." },
      { type: "p", text: "Mesurer ses conversions sans cookies tiers n'est pas une regression, c'est une remise a plat qui rend la mesure plus solide et plus respectueuse. First-party, server-side et modélisation forment un trepied : chacun compense les limites des autres. Bien orchestre, cet ensemble redonne une vision fiable des conversions, durable et conforme, la ou l'ancien modele s'effrite." },
    ],
    faq: [
      { q: "Peut-on encore mesurer ses conversions sans cookies tiers ?", a: "Oui, et souvent plus fiablement qu'avant. La mesure post-cookie repose sur trois piliers : la donnee first-party (collectee directement aupres de vos utilisateurs), le server-side tagging et les API de conversions, et la modélisation par les plateformes. Ensemble, ils compensent largement la disparition des cookies tiers." },
      { q: "Quelle difference entre cookie tiers et cookie first-party ?", a: "Un cookie tiers est depose par un domaine externe au site visite (une regie publicitaire) pour suivre l'utilisateur d'un site a l'autre — c'est lui qui disparait. Un cookie first-party est depose par le site que vous visitez, reste parfaitement valide, et devient le socle de la mesure post-cookie." },
      { q: "Qu'est-ce que la donnee first-party et pourquoi est-elle cruciale ?", a: "C'est l'ensemble des informations que vos utilisateurs vous confient directement : email, achat, compte, formulaire. Contrairement aux cookies tiers, elle ne disparait pas et vous appartient. Bien collectee avec consentement et structuree dans un CRM, elle devient la matiere premiere la plus perenne pour mesurer et cibler." },
      { q: "La modélisation des conversions est-elle fiable ?", a: "Elle est un complement utile, pas une source unique. Les plateformes estiment statistiquement les conversions non mesurees, notamment celles des utilisateurs ayant refuse le consentement, a partir du Consent Mode et des donnees observees. Sa fiabilite depend directement de la quantite et de la qualite des signaux consentis que vous lui fournissez." },
      { q: "Faut-il attendre la fin des cookies tiers pour agir ?", a: "Non, c'est meme risque. Les cookies tiers sont deja bloques par Safari et Firefox, et leur disparition est engagee. Construire des maintenant son socle first-party, migrer vers le server-side et activer la modélisation permet de calibrer pendant qu'il est encore temps, plutot que de decouvrir un jour une mesure effondree sans repli." },
    ],
  },
  {
    slug: "mise-en-conformite-rgpd-site-web",
    title: "Mise en conformite RGPD d'un site web : la checklist complete 2026",
    description:
      "Registre, mentions legales, cookies, sécurité, sous-traitants : la checklist RGPD concrète pour mettre un site web en conformité et eviter les sanctions de la CNIL.",
    date: "2026-07-09",
    readingTime: "9 min",
    category: "Tracking & conformité",
    keywords: [
      "mise en conformité RGPD site web",
      "checklist RGPD",
      "RGPD site internet",
      "conformité CNIL site",
    ],
    related: [
      { href: "/services/tracking-conformite", label: "Tracking & Conformité" },
      { href: "/services/securite-web", label: "Sécurité web" },
    ],
    content: [
      { type: "p", text: "La conformite RGPD d'un site web est trop souvent reduite a un bandeau cookies. En realite, le RGPD couvre l'ensemble de votre traitement de donnees personnelles : ce que vous collectez, pourquoi, comment vous le securisez, avec qui vous le partagez et ce que vous en dites a vos utilisateurs. La CNIL peut controler et sanctionner sur chacun de ces points. Voici une checklist concrete, poste par poste, pour mettre un site reellement en conformite." },
      { type: "h2", text: "1. Le registre des traitements" },
      { type: "p", text: "C'est le document de base, obligatoire pour la quasi-totalite des organisations. Il recense tous les traitements de donnees personnelles que vous operez via le site : formulaire de contact, newsletter, comptes clients, mesure d'audience. Sans lui, impossible de savoir ce que vous traitez, et son absence est une faute en soi lors d'un controle." },
      { type: "ul", items: [
        "Lister chaque traitement : finalite, categories de donnees, base legale, duree de conservation.",
        "Identifier qui accede aux donnees en interne et quels sous-traitants sont impliques.",
        "Tenir ce registre a jour a chaque nouveau formulaire ou outil ajoute au site.",
      ]},
      { type: "h2", text: "2. L'information et les mentions legales" },
      { type: "p", text: "Vos utilisateurs ont le droit de savoir ce que vous faites de leurs donnees. Cela passe par une politique de confidentialite claire et des mentions legales completes, accessibles depuis chaque page. C'est aussi la que vous informez sur les droits RGPD et la maniere de les exercer." },
      { type: "ul", items: [
        "Une politique de confidentialite qui detaille finalites, bases legales, durees et destinataires.",
        "Les droits de l'internaute (acces, rectification, effacement, opposition) et le moyen concret de les exercer.",
        "Des mentions legales completes (editeur, hebergeur, contact) accessibles en pied de page.",
        "Le contact du DPO si vous en avez designe un.",
      ]},
      { type: "h2", text: "3. Les cookies et le consentement" },
      { type: "p", text: "C'est la partie la plus visible, et celle que la CNIL controle le plus. Le principe : aucun cookie non essentiel, aucun tag de mesure ou de publicite avant le consentement, avec un refus aussi simple que l'acceptation. Un bandeau trompeur est l'une des premieres causes de sanction." },
      { type: "ul", items: [
        "Bandeau cookies conforme : refuser aussi simple qu'accepter, pas de case pre-cochee.",
        "Blocage reel des tags (GA4, Pixel Meta) tant que le consentement n'est pas donne.",
        "Conservation de la preuve des consentements recueillis.",
        "Consentement rejouable et retirable a tout moment.",
      ]},
      { type: "h2", text: "4. La sécurité des donnees" },
      { type: "p", text: "Le RGPD impose une obligation de securite : proteger les donnees contre les acces non autorises, les fuites et les pertes. Un site non securise qui laisse fuir des donnees personnelles engage la responsabilite de son editeur, meme sans intention malveillante. La securite technique fait partie integrante de la conformite." },
      { type: "ul", items: [
        "HTTPS obligatoire sur tout le site, avec des en-tetes de securite (HSTS, CSP).",
        "Protection des formulaires et des espaces d'authentification (mots de passe robustes, limitation des tentatives).",
        "Chiffrement des donnees sensibles et acces restreint aux seules personnes habilitees.",
        "Une procedure prete en cas de violation de donnees (notification a la CNIL sous 72h si necessaire).",
      ]},
      { type: "h2", text: "5. Les sous-traitants et transferts" },
      { type: "p", text: "Votre site s'appuie sur des prestataires qui traitent des donnees pour vous : hebergeur, outil d'emailing, plateforme analytics, service de paiement. Chacun est un sous-traitant au sens du RGPD, et vous devez encadrer cette relation. Les transferts hors de l'Union europeenne demandent une vigilance particuliere." },
      { type: "ul", items: [
        "Recenser tous les sous-traitants et signer un contrat de sous-traitance conforme avec chacun.",
        "Verifier ou sont hebergees les donnees et si elles quittent l'Union europeenne.",
        "Encadrer les transferts hors UE par des garanties appropriees (clauses contractuelles types).",
        "Privilegier, quand c'est possible, des prestataires europeens pour simplifier la conformite.",
      ]},
      { type: "cta", text: "Vous voulez un site reellement conforme RGPD, sans zone d'ombre juridique ?", href: "/services/tracking-conformite", label: "Voir notre offre Tracking & Conformité" },
      { type: "h2", text: "Ce que risque un site non conforme" },
      { type: "p", text: "Les sanctions ne sont pas theoriques. La CNIL peut prononcer des mises en demeure, puis des amendes pouvant atteindre 4 % du chiffre d'affaires annuel mondial ou 20 millions d'euros pour les manquements les plus graves. Au-dela de l'amende, il y a le risque reputationnel : une sanction publique ou une fuite de donnees entame durablement la confiance des clients." },
      { type: "p", text: "La conformite RGPD n'est pas un projet ponctuel qu'on coche une fois, c'est un etat a maintenir. Registre, information, cookies, securite, sous-traitants : chaque brique compte, et c'est leur absence cumulee qui expose au risque. Bien menee, la mise en conformite est aussi l'occasion d'assainir ses pratiques de donnees — un gage de serieux que vos clients percoivent." },
    ],
    faq: [
      { q: "Qu'implique la mise en conformite RGPD d'un site web ?", a: "Elle va bien au-dela du bandeau cookies. Il faut tenir un registre des traitements, informer clairement les utilisateurs (politique de confidentialite, mentions legales), gerer le consentement aux cookies, securiser les donnees (HTTPS, en-tetes, protection des acces) et encadrer les sous-traitants et transferts hors UE. Chacun de ces points peut etre controle par la CNIL." },
      { q: "Le registre des traitements est-il obligatoire ?", a: "Oui, pour la quasi-totalite des organisations. Il recense chaque traitement de donnees personnelles opere via le site — formulaire de contact, newsletter, comptes clients, mesure d'audience — avec sa finalite, sa base legale et sa duree de conservation. Son absence est une faute en soi lors d'un controle." },
      { q: "Un site sans bandeau cookies conforme peut-il etre sanctionne ?", a: "Oui, c'est meme l'une des premieres causes de sanction. Le site doit bloquer reellement les tags de mesure et de publicite tant que le consentement n'est pas donne, proposer un refus aussi simple que l'acceptation, ne pas utiliser de cases pre-cochees et conserver la preuve des consentements." },
      { q: "La securite fait-elle partie de la conformite RGPD ?", a: "Oui. Le RGPD impose une obligation de securite : HTTPS sur tout le site, en-tetes de securite, protection des formulaires et des acces, chiffrement des donnees sensibles et procedure en cas de violation. Un site qui laisse fuir des donnees personnelles engage la responsabilite de son editeur, meme sans intention malveillante." },
      { q: "Quelles sanctions en cas de non-conformite RGPD ?", a: "La CNIL peut prononcer des mises en demeure puis des amendes pouvant atteindre 4 % du chiffre d'affaires annuel mondial ou 20 millions d'euros pour les manquements les plus graves. S'ajoute le risque reputationnel : une sanction publique ou une fuite de donnees entame durablement la confiance des clients." },
    ],
  },
  {
    slug: "tracking-e-commerce-roas-guide",
    title: "Tracking e-commerce : mesurer un ROAS fiable en 2026",
    description:
      "Tracker proprement les achats en ligne pour obtenir un ROAS fiable : purchase events, CAPI, déduplication et attribution. Le guide du tracking e-commerce qui pilote vraiment.",
    date: "2026-07-08",
    readingTime: "9 min",
    category: "Tracking & conformité",
    keywords: [
      "tracking e-commerce",
      "mesurer le ROAS",
      "suivi conversions e-commerce",
      "tracking achats en ligne",
    ],
    related: [
      { href: "/services/tracking-conformite", label: "Tracking & Conformité" },
      { href: "/services/marketing-digital", label: "Marketing digital" },
    ],
    content: [
      { type: "p", text: "Sur un e-commerce, tout se decide sur un chiffre : le ROAS, le retour sur les depenses publicitaires. Or ce chiffre ne vaut que ce que vaut votre tracking. Un suivi d'achats bancal — conversions manquantes, doublons, valeurs erronees — produit un ROAS faux, et donc des decisions de budget prises a l'aveugle. A l'inverse, un tracking e-commerce propre transforme la publicite en machine pilotable. Voici comment tracker les achats correctement pour obtenir un ROAS reellement fiable." },
      { type: "h2", text: "Le ROAS ne vaut que ce que vaut le tracking" },
      { type: "p", text: "Le ROAS se calcule en divisant le chiffre d'affaires genere par la depense publicitaire. Le probleme : si votre tracking rate une partie des achats ou en compte certains deux fois, le chiffre d'affaires attribue est faux, et le ROAS avec lui. On voit des annonceurs couper des campagnes rentables parce que leur tracking sous-comptait, ou au contraire surinvestir sur des campagnes qui doublaient les conversions. La fiabilite de la mesure precede toute optimisation." },
      { type: "ul", items: [
        "Un tracking qui rate des achats : ROAS sous-estime, campagnes rentables coupees a tort.",
        "Un tracking qui double les achats : ROAS gonfle, budget gaspille sur des campagnes surevaluees.",
        "Avant d'optimiser, il faut prouver que la mesure est juste — sinon on optimise sur du bruit.",
      ]},
      { type: "h2", text: "Le purchase event : la brique fondamentale" },
      { type: "p", text: "Tout part de l'evenement d'achat (purchase), declenche a la validation de la commande. Mais un purchase event mal renseigne est presque aussi inutile qu'un evenement absent. Il doit porter les bonnes informations pour que les plateformes calculent un ROAS exact." },
      { type: "ul", items: [
        "La valeur reelle de la commande (value) et la devise (currency) — sans elles, aucun ROAS possible.",
        "Un identifiant de transaction unique, indispensable pour la deduplication.",
        "Le contenu de la commande (produits, quantites) pour alimenter le retargeting et le catalogue.",
        "Un declenchement au BON moment : a la confirmation de paiement, pas au clic sur « Payer ».",
      ]},
      { type: "h2", text: "La CAPI et la déduplication : indispensables en e-commerce" },
      { type: "p", text: "Cote client seul, une part croissante des achats echappe au tracking a cause d'iOS, de Safari et des bloqueurs. Sur un e-commerce ou chaque conversion pese lourd, ces pertes faussent directement le ROAS. La Conversions API (CAPI) de Meta, cote serveur, rattrape ces achats — a condition de dedupliquer pour ne pas les compter deux fois." },
      { type: "ul", items: [
        "Envoyer le purchase event a la fois cote client (Pixel) et cote serveur (CAPI) pour maximiser la couverture.",
        "Partager le meme event_id entre Pixel et CAPI pour que Meta fusionne les deux signaux.",
        "Transmettre les donnees de correspondance hashees (email, telephone) pour ameliorer le matching.",
        "Verifier dans le gestionnaire d'evenements que le taux de deduplication est eleve.",
      ]},
      { type: "h2", text: "L'attribution : a qui revient la vente ?" },
      { type: "p", text: "Un ROAS fiable suppose de savoir a quelle source attribuer chaque vente. Le parcours d'achat en ligne est rarement lineaire : un client voit une pub Meta, cherche la marque sur Google, revient plus tard en direct. Le modele d'attribution decide comment repartir le merite entre ces points de contact — et change radicalement la lecture des performances." },
      { type: "ul", items: [
        "Comprendre que chaque plateforme (Meta, Google, GA4) attribue selon sa propre fenetre et son propre modele.",
        "Ne pas additionner naivement les conversions de plusieurs plateformes : elles se chevauchent.",
        "Conserver les parametres UTM et les identifiants de clic (fbclid, gclid) pour tracer l'origine.",
        "Croiser les sources avec la verite comptable (vos ventes reelles) pour recaler le ROAS global.",
      ]},
      { type: "cta", text: "Vous voulez un tracking e-commerce fiable et un ROAS sur lequel vous pouvez decider ?", href: "/services/tracking-conformite", label: "Voir notre offre Tracking & Conformité" },
      { type: "h2", text: "Ne pas oublier la conformite" },
      { type: "p", text: "Tracker les achats reste un traitement de donnees personnelles a des fins marketing : le consentement s'applique, y compris pour la CAPI cote serveur. Un tracking e-commerce performant mais non conforme vous expose a une sanction et rend vos donnees juridiquement fragiles. Le bon reflexe : brancher tout le dispositif derriere une CMP et le Consent Mode, avec la modélisation pour compenser les refus." },
      { type: "p", text: "Un tracking e-commerce fiable repose sur une chaine complete : un purchase event bien renseigne, une CAPI dedupliquee, une attribution comprise et une conformite respectee. Chaque maillon compte, car un seul defaut suffit a fausser le ROAS et donc les decisions de budget. Bien construit, ce dispositif transforme vos depenses publicitaires en investissement pilotable, ou chaque euro se justifie sur des chiffres justes." },
    ],
    faq: [
      { q: "Pourquoi mon ROAS n'est-il pas fiable ?", a: "Presque toujours a cause du tracking. Si votre suivi rate une partie des achats (a cause d'iOS, de Safari, des bloqueurs), le ROAS est sous-estime ; s'il compte certains achats deux fois (Pixel et CAPI sans deduplication), il est gonfle. Dans les deux cas, le chiffre d'affaires attribue est faux, donc le ROAS aussi. La fiabilite de la mesure precede toute optimisation." },
      { q: "Quelles informations doit contenir un purchase event ?", a: "La valeur reelle de la commande et la devise (sans elles, aucun ROAS possible), un identifiant de transaction unique pour la deduplication, et le contenu de la commande pour le retargeting. L'evenement doit aussi se declencher au bon moment : a la confirmation de paiement, pas au clic sur le bouton payer." },
      { q: "La CAPI est-elle indispensable pour un e-commerce ?", a: "Elle l'est des que la publicite payante pese dans vos ventes. Cote client seul, une part croissante des achats echappe au tracking a cause d'iOS et des bloqueurs, ce qui fausse le ROAS. La CAPI cote serveur rattrape ces achats — a condition de partager le meme event_id que le Pixel pour dedupliquer et ne pas compter deux fois." },
      { q: "Comment l'attribution influence-t-elle le ROAS ?", a: "Le parcours d'achat est rarement lineaire : le client voit une pub, cherche la marque, revient plus tard. Le modele d'attribution decide comment repartir le merite entre ces points de contact, et chaque plateforme attribue selon sa propre fenetre. Il ne faut pas additionner naivement les conversions de Meta, Google et GA4, qui se chevauchent, mais les recaler sur vos ventes reelles." },
      { q: "Le tracking e-commerce doit-il respecter le RGPD ?", a: "Oui. Tracker les achats reste un traitement de donnees personnelles a des fins marketing, soumis au consentement, y compris pour la CAPI cote serveur. Le dispositif doit etre branche derriere une CMP et le Consent Mode, avec la modélisation pour compenser les refus. Un tracking performant mais non conforme expose a une sanction." },
    ],
  },
];
