import type { Post } from "./posts";

export const POSTS_LOCAL: Post[] = [
  {
    slug: "referencement-google-maps",
    title: "Référencement Google Maps : comment être bien placé dans le pack local",
    description:
      "Les vrais facteurs de classement sur Google Maps (pertinence, distance, notoriété), comment définir sa zone de chalandise et sortir dans le pack local des trois établissements.",
    date: "2026-05-18",
    readingTime: "9 min",
    category: "SEO local",
    keywords: [
      "référencement Google Maps",
      "apparaître sur Google Maps",
      "être bien placé Google Maps",
      "classement Google Maps",
    ],
    related: [
      { href: "/services/seo", label: "SEO technique" },
      { href: "/blog/optimiser-fiche-google-business-profile", label: "Optimiser sa fiche Google Business Profile" },
    ],
    content: [
      { type: "p", text: "Quand quelqu'un cherche un service près de chez lui, Google affiche d'abord une carte et trois établissements : le pack local. C'est cet encart qui capte l'essentiel des appels et des demandes d'itinéraire, bien avant les résultats classiques. Or le classement sur Google Maps ne suit pas exactement les mêmes règles que le référencement web : il repose sur un trio de facteurs propres au local. Voici comment ils fonctionnent, et comment remonter dans ce pack de trois." },
      { type: "h2", text: "Les trois facteurs de classement de Google Maps" },
      { type: "p", text: "Google est explicite sur ce qui détermine le classement local : trois critères se combinent, et aucun ne suffit seul. Les comprendre évite de perdre du temps sur ce qui ne bouge pas l'aiguille." },
      { type: "ul", items: [
        "La pertinence : à quel point votre établissement correspond à la recherche. C'est là que jouent la catégorie principale, les services renseignés et le contenu de la fiche.",
        "La distance : la proximité entre l'internaute (ou le lieu qu'il précise) et votre établissement. Vous ne pouvez pas la changer, mais elle explique pourquoi votre classement varie selon l'endroit d'où l'on cherche.",
        "La notoriété : à quel point votre établissement est connu et reconnu, mesuré via les avis, les mentions sur le web, les liens et la cohérence de vos informations.",
      ]},
      { type: "h2", text: "Distance : pourquoi votre position change d'un quartier à l'autre" },
      { type: "p", text: "Une erreur fréquente est de vérifier son classement depuis son propre bureau, à deux pas de l'établissement, et d'en conclure qu'on est bien placé. Google personnalise le pack local selon la position de chacun : vous pouvez être premier à 500 mètres et invisible à trois kilomètres. Le bon réflexe est de raisonner en zone de chalandise, pas en position unique. On mesure sa visibilité sur une grille de points autour de l'établissement, ce qui révèle jusqu'où votre notoriété compense la distance." },
      { type: "h2", text: "Travailler la pertinence sans forcer" },
      { type: "p", text: "La pertinence se joue d'abord sur la catégorie principale, le facteur le plus puissant. Choisissez la plus précise qui décrit votre métier, et non une catégorie large. Ajoutez ensuite les services et les descriptifs qui reprennent le vocabulaire réel de vos clients." },
      { type: "ul", items: [
        "Renseignez chaque service proposé avec un intitulé clair, tel que les gens le recherchent.",
        "Décrivez l'activité dans la présentation sans bourrer de mots-clés, ce qui n'aide pas et peut faire suspendre la fiche.",
        "Reliez la fiche à un site cohérent : une page qui parle de la même activité renforce le signal de pertinence.",
      ]},
      { type: "h2", text: "La notoriété : le levier sur lequel vous avez la main" },
      { type: "p", text: "C'est le facteur le plus actionnable. La notoriété locale se construit avec le volume et la récence des avis, la cohérence de vos coordonnées partout sur le web, et les mentions de votre nom sur d'autres sites. Un établissement qui accumule des avis récents, des citations cohérentes et quelques liens locaux remonte progressivement, même face à un concurrent plus proche géographiquement." },
      { type: "cta", text: "Vous voulez apparaître dans le pack local Google Maps sur votre zone ?", href: "/services/seo", label: "Voir notre offre SEO local" },
      { type: "h2", text: "Les signaux d'engagement comptent aussi" },
      { type: "p", text: "Google observe la façon dont les internautes interagissent avec votre fiche : clics vers le site, demandes d'itinéraire, appels, enregistrements. Une fiche complète et vivante génère plus d'actions, et ces actions renforcent en retour sa visibilité. C'est un cercle vertueux : plus la fiche est soignée, plus elle est cliquée, plus elle remonte." },
      { type: "h2", text: "En résumé" },
      { type: "p", text: "Le référencement Google Maps se pilote sur ce que vous contrôlez : une catégorie précise, une fiche complète et cohérente, une notoriété entretenue par les avis et les citations. La distance, elle, ne se corrige pas, mais une notoriété forte permet de gagner du terrain au-delà de votre rue. Pensez toujours en zone de chalandise plutôt qu'en position unique : c'est la seule façon de mesurer, puis d'améliorer, votre présence réelle sur la carte." },
    ],
    faq: [
      { q: "Quels sont les facteurs de classement sur Google Maps ?", a: "Google combine trois facteurs : la pertinence (adéquation de votre fiche à la recherche, via la catégorie et les services), la distance (proximité entre l'internaute et votre établissement) et la notoriété (avis, mentions sur le web, cohérence des informations). Aucun ne suffit seul ; c'est leur combinaison qui détermine votre position." },
      { q: "Pourquoi mon classement Google Maps change selon l'endroit d'où je cherche ?", a: "Parce que la distance est un facteur de classement : Google personnalise le pack local selon la position de chaque internaute. Vous pouvez être premier tout près de votre établissement et absent à quelques kilomètres. Il faut donc mesurer sa visibilité sur une zone, pas depuis un seul point." },
      { q: "Comment apparaître dans le pack local des trois établissements ?", a: "Travaillez les facteurs actionnables : une catégorie principale précise, une fiche complète et cohérente, un volume d'avis récents et des coordonnées identiques partout sur le web. La notoriété ainsi construite permet de remonter dans le pack, même face à un concurrent plus proche géographiquement." },
      { q: "La distance est-elle un frein définitif sur Google Maps ?", a: "Non. Vous ne pouvez pas changer votre adresse, mais une notoriété forte (avis, citations cohérentes, liens locaux) compense en partie la distance et étend votre zone de visibilité. C'est pourquoi un établissement bien noté et bien référencé peut ressortir plus loin que ses concurrents." },
      { q: "Faut-il un site web pour être bien placé sur Google Maps ?", a: "Ce n'est pas obligatoire, mais un site cohérent renforce le signal de pertinence et de notoriété. Une page qui décrit la même activité, avec des coordonnées identiques à la fiche, conforte Google dans l'identité de votre établissement et aide le classement local." },
    ],
  },
  {
    slug: "obtenir-avis-google-clients",
    title: "Obtenir des avis Google : méthode pour en collecter sans les acheter",
    description:
      "Comment demander des avis clients au bon moment, créer un lien direct de dépôt, gérer les avis négatifs et rester conforme aux règles Google sans jamais acheter d'avis.",
    date: "2026-05-17",
    readingTime: "8 min",
    category: "SEO local",
    keywords: [
      "obtenir des avis Google",
      "demander des avis clients",
      "augmenter ses avis Google",
      "gérer les avis négatifs",
    ],
    related: [
      { href: "/services/marketing-digital", label: "Marketing digital" },
      { href: "/blog/preuve-sociale-avis-clients", label: "Preuve sociale et avis clients" },
    ],
    content: [
      { type: "p", text: "Les avis Google pèsent à la fois sur votre classement local et sur la décision du client qui vous découvre. Pourtant la plupart des commerces attendent passivement qu'ils tombent, et se retrouvent avec quelques avis anciens, parfois négatifs, non représentatifs de leur travail. Collecter des avis authentiques, régulièrement, est une mécanique qui s'organise. Voici comment le faire proprement, sans jamais en acheter ni enfreindre les règles de Google." },
      { type: "h2", text: "Pourquoi il ne faut jamais acheter d'avis" },
      { type: "p", text: "L'achat d'avis est tentant mais dangereux à tous les niveaux. Google détecte les schémas anormaux (pics soudains, comptes sans historique, textes génériques) et sanctionne : suppression des avis, voire suspension de la fiche. Au-delà du risque, de faux avis se repèrent souvent par les clients eux-mêmes et détruisent la confiance. La seule stratégie durable est la collecte d'avis réels, et elle donne de meilleurs résultats sur la durée." },
      { type: "h2", text: "Le bon moment pour demander" },
      { type: "p", text: "Un avis se demande quand la satisfaction est à son maximum, pas des semaines plus tard. Le moment idéal dépend de votre activité, mais le principe est le même : capter l'élan positif juste après une expérience réussie." },
      { type: "ul", items: [
        "Juste après la prestation ou la livraison, tant que le client a l'expérience fraîche en tête.",
        "Après un échange positif au comptoir, à la caisse ou en fin de rendez-vous.",
        "En relance douce quelques jours après, par SMS ou email, pour ceux qui n'ont pas répondu sur le moment.",
      ]},
      { type: "h2", text: "Le lien direct : supprimer les frictions" },
      { type: "p", text: "La première cause d'avis non déposés, c'est l'effort. Un client satisfait mais pressé abandonne s'il doit chercher votre fiche, se connecter, faire défiler. La solution est un lien direct qui ouvre le formulaire de dépôt d'avis en un clic, avec la fenêtre d'étoiles déjà prête." },
      { type: "ul", items: [
        "Récupérez le lien court de demande d'avis fourni dans votre espace de gestion de fiche.",
        "Transformez-le en QR code à afficher en boutique, sur le ticket, sur un carton de remerciement.",
        "Intégrez-le dans vos emails de suivi et vos signatures, avec un texte clair d'invitation.",
      ]},
      { type: "h2", text: "Rester dans les clous des règles Google" },
      { type: "p", text: "Solliciter des avis est autorisé, à condition de ne pas fausser le jeu. Deux règles à respecter absolument :" },
      { type: "ul", items: [
        "Ne conditionnez jamais un avis à une remise ou un cadeau : l'incitation est interdite et fausse la note.",
        "Ne filtrez pas les clients pour ne solliciter que les plus satisfaits (le review gating est proscrit) : demandez à tous de la même façon.",
      ]},
      { type: "cta", text: "Vous voulez une mécanique de collecte d'avis qui tourne toute seule ?", href: "/services/marketing-digital", label: "Mettre en place une collecte d'avis" },
      { type: "h2", text: "Gérer les avis négatifs sans paniquer" },
      { type: "p", text: "Un avis négatif n'est pas une catastrophe, c'est une occasion de montrer votre sérieux à tous les futurs lecteurs. Répondez calmement, rapidement et publiquement : reconnaissez ce qui doit l'être, proposez une solution, et invitez à poursuivre en privé. Un professionnel qui répond bien à une critique inspire souvent plus confiance qu'une fiche parfaite. Ne demandez la suppression que pour les avis qui violent réellement les règles (propos injurieux, hors sujet, concurrent malveillant) : les critiques légitimes, elles, se traitent par la réponse." },
      { type: "h2", text: "La régularité prime sur le volume" },
      { type: "p", text: "Google et les clients valorisent la récence autant que la quantité. Cent avis vieux de trois ans pèsent moins qu'un flux régulier d'avis frais. Mieux vaut viser quelques avis chaque semaine, en continu, que des campagnes ponctuelles. C'est cette régularité, entretenue par une mécanique simple, qui construit une réputation solide et un meilleur classement local dans la durée." },
    ],
    faq: [
      { q: "Comment demander un avis Google à un client ?", a: "Demandez au moment où la satisfaction est maximale (juste après la prestation, à la caisse ou en fin de rendez-vous), puis relancez en douceur quelques jours plus tard par SMS ou email. Facilitez le geste avec un lien direct qui ouvre le formulaire de dépôt en un clic, sous forme de QR code ou de bouton." },
      { q: "Est-il interdit d'acheter des avis Google ?", a: "Oui, c'est contraire aux règles de Google et fortement déconseillé. Google détecte les schémas anormaux et sanctionne (suppression des avis, suspension de la fiche). De faux avis sont aussi repérés par les clients et ruinent la confiance. Seule la collecte d'avis authentiques est durable et efficace." },
      { q: "A-t-on le droit d'offrir une remise contre un avis ?", a: "Non. Conditionner un avis à une remise ou un cadeau est une incitation interdite qui fausse la note. De même, le review gating (ne solliciter que les clients les plus satisfaits) est proscrit. Vous pouvez demander des avis, mais à tous les clients et sans contrepartie." },
      { q: "Comment répondre à un avis négatif sur Google ?", a: "Répondez rapidement, calmement et publiquement : reconnaissez ce qui doit l'être, proposez une solution et invitez à poursuivre en privé. Une bonne réponse rassure les futurs lecteurs. Ne demandez la suppression que pour les avis qui violent réellement les règles, pas pour les critiques légitimes." },
      { q: "Vaut-il mieux beaucoup d'avis ou des avis récents ?", a: "Les deux comptent, mais la récence est déterminante : un flux régulier d'avis frais pèse davantage que de nombreux avis anciens. Visez quelques avis par semaine en continu plutôt que des campagnes ponctuelles ; cette régularité soutient mieux le classement local et la réputation." },
    ],
  },
  {
    slug: "referencement-local-par-ville",
    title: "Référencement local par ville : créer des pages locales sans dupliquer",
    description:
      "Comment construire des pages locales par ville qui rankent : contenu réellement local, éviter le doorway et le duplicate content, mailler et structurer un SEO géolocalisé.",
    date: "2026-05-16",
    readingTime: "9 min",
    category: "SEO local",
    keywords: [
      "référencement local par ville",
      "pages locales SEO",
      "être visible dans plusieurs villes",
      "SEO géolocalisé",
    ],
    related: [
      { href: "/services/seo", label: "SEO technique" },
      { href: "/blog/seo-local-attirer-clients-proximite", label: "SEO local" },
    ],
    content: [
      { type: "p", text: "Une entreprise qui intervient dans plusieurs villes veut ressortir dans chacune : « plombier Lyon », « plombier Villeurbanne », « plombier Vénissieux ». La tentation est de créer une page par ville en changeant juste le nom. C'est exactement ce qui ne marche pas, et qui peut vous pénaliser. Faire du référencement local par ville proprement demande de produire des pages réellement locales, pas des clones. Voici la méthode pour être visible dans plusieurs villes sans tomber dans le piège du contenu dupliqué." },
      { type: "h2", text: "Le piège des pages générées en série" },
      { type: "p", text: "Le réflexe classique consiste à dupliquer un modèle de page et à remplacer le nom de la ville par un script. Résultat : cinquante pages quasi identiques, sans valeur propre. Google appelle cela des doorway pages (pages tremplin) et les traite comme du spam. Non seulement elles ne rankent pas, mais elles peuvent dégrader la confiance dans tout le site. Le contenu dupliqué à grande échelle est l'inverse de ce que récompense le référencement local." },
      { type: "h2", text: "Ce qui rend une page locale légitime" },
      { type: "p", text: "Une page ville mérite d'exister quand elle apporte une information réellement spécifique à cette ville. La question à se poser avant d'en créer une : ai-je quelque chose de vrai et d'utile à dire sur mon activité dans cette ville précise ?" },
      { type: "ul", items: [
        "Une présence réelle : une zone d'intervention effective, des chantiers ou des clients dans la ville.",
        "Du contenu propre : réalisations locales, quartiers desservis, délais d'intervention, contraintes spécifiques.",
        "Des preuves : avis de clients de la ville, photos de projets locaux, cas concrets.",
        "Des informations pratiques : temps d'accès, zones couvertes, particularités du secteur.",
      ]},
      { type: "h2", text: "Structurer l'arborescence géolocalisée" },
      { type: "p", text: "Une bonne architecture aide Google à comprendre votre couverture. On distingue la page de service générale des pages locales, reliées entre elles logiquement. L'URL doit rester lisible et cohérente." },
      { type: "ul", items: [
        "Une page pilier par service, qui présente l'offre sur le fond.",
        "Une page par ville où vous avez une présence réelle, en URL claire du type /service/ville.",
        "Un maillage interne qui relie chaque page ville à la page service et aux villes voisines pertinentes.",
        "Des balises title et meta description propres à chaque ville, jamais recopiées à l'identique.",
      ]},
      { type: "h2", text: "Combien de pages ville créer ?" },
      { type: "p", text: "La bonne réponse n'est pas « le plus possible ». Il vaut mieux dix pages solides et distinctes que cent pages creuses. Commencez par les villes où votre présence est la plus forte et le potentiel commercial le plus élevé, puis étendez au rythme où vous pouvez produire du contenu réellement local. Une page ville sans matière propre ne doit pas exister : mieux vaut ne pas la créer que la remplir de texte générique." },
      { type: "cta", text: "Vous voulez ressortir dans plusieurs villes sans risquer une pénalité ?", href: "/services/seo", label: "Construire votre SEO local par ville" },
      { type: "h2", text: "Articuler pages ville et fiche Google" },
      { type: "p", text: "Attention à ne pas confondre deux mécaniques. Les pages ville servent le référencement web classique (les résultats bleus) ; la fiche Google Business Profile, elle, sert le pack local et la carte, et se rattache à une adresse physique. Une entreprise mono-établissement qui vise plusieurs villes s'appuiera surtout sur des pages ville pour élargir sa portée au-delà de la zone de sa fiche. Les deux se complètent : cohérence des coordonnées d'un côté, contenu local propre de l'autre." },
      { type: "h2", text: "En résumé" },
      { type: "p", text: "Le référencement local par ville fonctionne à une condition : chaque page doit être réellement locale, pas un clone. Produisez moins de pages mais plus riches, ancrées dans une présence effective, avec des preuves et des informations propres à chaque ville, et maillez-les proprement. C'est ce travail de fond, à l'opposé de la génération automatique, qui vous rend visible dans plusieurs villes sans jamais vous exposer au risque de duplicate content." },
    ],
    faq: [
      { q: "Peut-on créer une page par ville pour le SEO local ?", a: "Oui, à condition que chaque page soit réellement locale : présence effective dans la ville, contenu propre (réalisations, zones desservies, avis locaux) et balises spécifiques. Dupliquer un modèle en changeant seulement le nom de la ville crée des doorway pages, considérées comme du spam par Google." },
      { q: "Qu'est-ce qu'une doorway page et pourquoi l'éviter ?", a: "Une doorway page est une page tremplin créée en série, quasi identique, dont seul le nom de ville change. Google les traite comme du spam : elles ne rankent pas et peuvent dégrader la confiance dans tout le site. Il faut leur préférer des pages locales à contenu propre et vérifiable." },
      { q: "Combien de pages ville faut-il créer ?", a: "Privilégiez la qualité : mieux vaut dix pages solides et distinctes que cent pages creuses. Commencez par les villes où votre présence est la plus forte et le potentiel commercial le plus élevé, puis étendez au rythme où vous pouvez produire du contenu réellement local pour chacune." },
      { q: "Quelle différence entre une page ville et une fiche Google Business Profile ?", a: "Les pages ville servent le référencement web classique (les résultats bleus) ; la fiche Google Business Profile sert le pack local et la carte, rattachée à une adresse physique. Les deux se complètent : les pages ville élargissent la portée au-delà de la zone de la fiche." },
      { q: "Comment éviter le contenu dupliqué entre pages ville ?", a: "Rédigez pour chaque ville un contenu réellement spécifique (réalisations locales, quartiers, délais, contraintes), des balises title et meta description propres, et évitez tout modèle recopié à l'identique. Ne créez pas de page pour une ville où vous n'avez rien de vrai à dire." },
    ],
  },
  {
    slug: "citations-locales-annuaires-seo",
    title: "Citations locales et annuaires : construire un NAP cohérent",
    description:
      "Ce que sont les citations locales, pourquoi la cohérence NAP compte pour le SEO local, quels annuaires prioriser, comment auditer et nettoyer ses mentions dispersées.",
    date: "2026-05-15",
    readingTime: "8 min",
    category: "SEO local",
    keywords: [
      "citations locales",
      "annuaires SEO local",
      "NAP cohérence",
      "inscription annuaires professionnels",
    ],
    related: [
      { href: "/services/seo", label: "SEO technique" },
      { href: "/blog/netlinking-backlinks-strategie", label: "Netlinking et backlinks" },
    ],
    content: [
      { type: "p", text: "Avant même de penser aux liens, le référencement local repose sur une brique discrète mais décisive : les citations. Une citation, c'est toute mention de votre nom, adresse et téléphone sur le web, avec ou sans lien. Google s'en sert pour confirmer que votre établissement existe vraiment et pour évaluer sa notoriété. Le problème, c'est que ces mentions se dispersent et deviennent vite incohérentes. Voici comment construire un socle de citations propre, et pourquoi la cohérence NAP fait toute la différence." },
      { type: "h2", text: "Qu'est-ce qu'une citation locale ?" },
      { type: "p", text: "Une citation locale est une occurrence de vos coordonnées quelque part sur le web : annuaire professionnel, plateforme sectorielle, site partenaire, presse locale. On distingue les citations structurées (fiches d'annuaires avec champs dédiés) des citations non structurées (mention dans un article, un billet de blog, un communiqué). Les deux comptent : elles forment un faisceau de preuves qui atteste de l'existence et de la constance de votre établissement." },
      { type: "h2", text: "Pourquoi la cohérence NAP est le vrai sujet" },
      { type: "p", text: "NAP signifie Name, Address, Phone. Le facteur qui compte n'est pas seulement d'avoir beaucoup de citations, mais qu'elles disent toutes exactement la même chose. Quand Google trouve trois orthographes d'adresse et deux numéros différents pour un même établissement, il doute, et ce doute affaiblit votre positionnement local." },
      { type: "ul", items: [
        "Un nom écrit exactement de la même façon partout, sans variantes ni mots-clés ajoutés.",
        "Une adresse au format identique au caractère près (abréviations, ordre des éléments, code postal).",
        "Un seul numéro de téléphone de référence, le même sur toutes les fiches.",
        "Une cohérence stricte entre les citations, la fiche Google et le site.",
      ]},
      { type: "h2", text: "Quels annuaires prioriser" },
      { type: "p", text: "Inutile de s'inscrire sur des centaines d'annuaires : la plupart n'apportent rien et certains nuisent. On vise d'abord les sources qui font autorité et celles spécifiques à votre secteur et à votre région." },
      { type: "ul", items: [
        "Les grands agrégateurs de données locales, qui redistribuent l'information à de nombreux services.",
        "Les annuaires généralistes reconnus et bien indexés, à forte notoriété.",
        "Les annuaires sectoriels de votre métier, souvent plus qualifiés pour vos clients.",
        "Les sources locales : chambres, associations professionnelles, presse et sites de votre ville.",
      ]},
      { type: "h2", text: "Auditer l'existant avant d'ajouter" },
      { type: "p", text: "L'erreur la plus courante est de multiplier les nouvelles inscriptions sans nettoyer les anciennes. Or ce sont souvent les vieilles fiches oubliées, avec une ancienne adresse ou un ancien numéro, qui créent l'incohérence. Commencez par cartographier ce qui existe déjà à votre nom avant d'en créer de nouvelles." },
      { type: "ul", items: [
        "Recensez toutes les mentions existantes de votre établissement sur le web.",
        "Repérez les incohérences : anciennes adresses, numéros périmés, doublons, orthographes divergentes.",
        "Corrigez ou faites supprimer les fiches erronées, en priorité les plus visibles.",
        "N'ajoutez de nouvelles citations qu'une fois l'existant assaini.",
      ]},
      { type: "cta", text: "Vous voulez un socle de citations locales propre et cohérent ?", href: "/services/seo", label: "Auditer et construire vos citations locales" },
      { type: "h2", text: "Citations et backlinks : deux rôles distincts" },
      { type: "p", text: "Ne confondez pas les deux. Une citation atteste de l'existence et de la cohérence de votre établissement ; un backlink transmet de l'autorité. Certaines citations d'annuaires apportent un lien, mais leur valeur première est la confirmation NAP, pas le jus de lien. C'est pourquoi une stratégie de citations vise la cohérence et la couverture, là où une stratégie de netlinking vise la qualité et la thématique des liens. Les deux se complètent sans se remplacer." },
      { type: "h2", text: "En résumé" },
      { type: "p", text: "Les citations locales sont le socle silencieux du référencement local : elles prouvent à Google que votre établissement est réel et stable. L'enjeu n'est pas le nombre mais la cohérence NAP, au caractère près, sur des sources qui font autorité. Auditez d'abord l'existant, nettoyez les incohérences, puis complétez avec parcimonie sur des annuaires pertinents. Ce travail de fond, peu spectaculaire, consolide durablement votre visibilité de proximité." },
    ],
    faq: [
      { q: "Qu'est-ce qu'une citation locale en SEO ?", a: "C'est toute mention de vos coordonnées (nom, adresse, téléphone) sur le web, avec ou sans lien : annuaire, plateforme sectorielle, article de presse locale. Google s'en sert pour confirmer l'existence de votre établissement et évaluer sa notoriété. On distingue les citations structurées (fiches d'annuaires) et non structurées (mentions dans un texte)." },
      { q: "Pourquoi la cohérence NAP est-elle si importante ?", a: "NAP signifie Name, Address, Phone. Si Google trouve plusieurs orthographes d'adresse ou plusieurs numéros pour un même établissement, il doute, et ce doute affaiblit votre positionnement local. Ce qui compte n'est pas seulement le nombre de citations, mais qu'elles indiquent toutes exactement la même chose, au caractère près." },
      { q: "Sur combien d'annuaires faut-il s'inscrire ?", a: "Pas des centaines : la plupart n'apportent rien et certains nuisent. Priorisez les grands agrégateurs de données locales, les annuaires généralistes reconnus, les annuaires sectoriels de votre métier et les sources locales (chambres, presse, associations). La pertinence et l'autorité priment sur la quantité." },
      { q: "Faut-il nettoyer ses anciennes fiches avant d'en créer de nouvelles ?", a: "Oui, c'est prioritaire. Ce sont souvent de vieilles fiches oubliées, avec une ancienne adresse ou un ancien numéro, qui créent l'incohérence NAP. Recensez d'abord toutes les mentions existantes, corrigez ou supprimez celles qui sont erronées, puis seulement ajoutez de nouvelles citations." },
      { q: "Quelle différence entre une citation et un backlink ?", a: "Une citation atteste de l'existence et de la cohérence de votre établissement ; un backlink transmet de l'autorité. Certaines citations apportent un lien, mais leur rôle premier est la confirmation NAP, pas le jus de lien. Les deux stratégies se complètent sans se remplacer." },
    ],
  },
  {
    slug: "seo-local-multi-etablissements",
    title: "SEO local multi-établissements : gérer un réseau de points de vente",
    description:
      "Comment référencer plusieurs points de vente : une fiche Google par établissement, pages locales dédiées, gestion en masse, cohérence de marque et pièges des réseaux.",
    date: "2026-05-14",
    readingTime: "9 min",
    category: "SEO local",
    keywords: [
      "SEO local multi-établissements",
      "référencement plusieurs points de vente",
      "fiches Google plusieurs magasins",
      "SEO local réseau",
    ],
    related: [
      { href: "/services/seo", label: "SEO technique" },
      { href: "/services/marketing-digital", label: "Marketing digital" },
    ],
    content: [
      { type: "p", text: "Référencer un commerce isolé est une chose ; piloter la visibilité locale d'un réseau de dix, cinquante ou deux cents points de vente en est une autre. Les règles de base ne changent pas, mais les erreurs se multiplient par le nombre d'établissements, et une mauvaise pratique appliquée à tout un parc peut faire des dégâts à grande échelle. Voici comment structurer un SEO local multi-établissements qui fait ressortir chaque point de vente sur sa zone, sans se cannibaliser ni se noyer dans la gestion." },
      { type: "h2", text: "Une fiche par établissement, sans exception" },
      { type: "p", text: "La règle fondatrice : chaque point de vente qui reçoit du public doit avoir sa propre fiche Google Business Profile, avec sa vraie adresse et son propre numéro. On ne mutualise pas, on ne crée pas une fiche unique pour la marque. Chaque fiche joue sur sa zone de chalandise, avec ses avis, ses horaires et ses photos propres." },
      { type: "ul", items: [
        "Une adresse physique réelle par fiche, où l'établissement reçoit effectivement des clients.",
        "Un numéro de téléphone local par point de vente, plutôt qu'un standard central unique.",
        "Des horaires, photos et posts propres à chaque établissement, pas un contenu de marque recopié partout.",
        "Une catégorie principale identique pour tous les points de vente du même type d'activité.",
      ]},
      { type: "h2", text: "Gérer les fiches en masse sans perdre la main" },
      { type: "p", text: "À partir d'une dizaine d'établissements, la gestion manuelle fiche par fiche devient impraticable. Google propose une gestion groupée qui permet d'administrer un parc de fiches de façon centralisée, avec import en masse et rôles d'accès." },
      { type: "ul", items: [
        "Un compte organisant l'ensemble des établissements sous une même entité, avec des accès délégués.",
        "L'import et la mise à jour en masse des informations, pour propager un changement d'horaires ou de coordonnées sans tout refaire à la main.",
        "Un suivi centralisé des avis et des questions, pour ne rien laisser sans réponse à l'échelle du réseau.",
        "Des droits d'accès par établissement, afin que chaque responsable local gère sa fiche sans toucher aux autres.",
      ]},
      { type: "h2", text: "Le locator : une page par point de vente" },
      { type: "p", text: "Côté site, un réseau performant s'appuie sur un magasin locator : un annuaire interne où chaque établissement dispose de sa propre page. Ces pages locales renforcent chaque fiche et captent les recherches web au-delà du seul pack local." },
      { type: "ul", items: [
        "Une page dédiée par point de vente, avec adresse, horaires, téléphone et itinéraire.",
        "Des données structurées LocalBusiness cohérentes avec la fiche Google correspondante.",
        "Du contenu local propre autant que possible, pour éviter que toutes les pages soient identiques.",
        "Un maillage clair depuis une page annuaire vers chaque établissement.",
      ]},
      { type: "cta", text: "Vous pilotez un réseau de points de vente à référencer localement ?", href: "/services/seo", label: "Structurer votre SEO local multi-sites" },
      { type: "h2", text: "Éviter la cannibalisation entre établissements" },
      { type: "p", text: "Le risque propre aux réseaux est que deux points de vente proches se disputent les mêmes recherches, ou que des pages locales trop semblables se cannibalisent. La distance dans le pack local limite ce problème pour les fiches, mais côté site, il faut veiller à ce que chaque page locale reste distincte. Des pages générées en série, identiques au nom de ville près, retombent dans le piège des doorway pages, cette fois à l'échelle du parc, ce qui peut pénaliser tout le domaine." },
      { type: "h2", text: "Concilier marque et local" },
      { type: "p", text: "Un réseau doit tenir deux exigences en tension : une image de marque homogène et une pertinence locale réelle. La cohérence se joue sur l'identité (nom, catégorie, charte, ton des réponses aux avis) ; la pertinence locale se joue sur ce qui est propre à chaque point de vente (avis, photos, actualités, particularités du secteur). Un réseau qui uniformise tout perd en local ; un réseau qui laisse tout diverger perd en cohérence. Le bon équilibre standardise le cadre et personnalise le contenu." },
      { type: "h2", text: "En résumé" },
      { type: "p", text: "Le SEO local multi-établissements est une affaire d'échelle et de discipline : une fiche propre par point de vente, une gestion groupée pour rester maître d'un grand parc, un locator avec une page par établissement, et une vigilance constante contre la cannibalisation et les pages dupliquées. Standardisez le cadre de marque, personnalisez le contenu local, et chaque point de vente ressortira sur sa zone sans nuire aux autres." },
    ],
    faq: [
      { q: "Faut-il une fiche Google par point de vente ?", a: "Oui, sans exception : chaque établissement qui reçoit du public doit avoir sa propre fiche Google Business Profile, avec sa vraie adresse et son numéro local. On ne crée pas une fiche unique pour la marque. Chaque fiche joue sur sa zone de chalandise avec ses avis, horaires et photos propres." },
      { q: "Comment gérer les fiches Google d'un réseau de magasins ?", a: "Au-delà d'une dizaine d'établissements, la gestion manuelle devient impraticable. Google propose une gestion groupée : un compte organisant tous les points de vente, l'import et la mise à jour en masse des informations, un suivi centralisé des avis et des droits d'accès délégués par établissement." },
      { q: "Qu'est-ce qu'un store locator et pourquoi en avoir un ?", a: "C'est un annuaire interne au site où chaque point de vente dispose de sa propre page locale (adresse, horaires, téléphone, itinéraire, données LocalBusiness). Il renforce chaque fiche Google et capte les recherches web au-delà du pack local. Chaque page doit rester distincte pour éviter la duplication." },
      { q: "Comment éviter que mes points de vente se cannibalisent ?", a: "Pour les fiches, la distance dans le pack local limite naturellement la concurrence. Côté site, veillez à ce que chaque page locale soit réellement distincte : des pages générées en série, identiques au nom de ville près, retombent dans le piège des doorway pages et peuvent pénaliser tout le domaine." },
      { q: "Comment concilier image de marque et référencement local ?", a: "Standardisez le cadre (nom, catégorie, charte, ton des réponses aux avis) et personnalisez le contenu propre à chaque point de vente (avis, photos, actualités, particularités locales). Un réseau qui uniformise tout perd en pertinence locale ; un réseau qui laisse tout diverger perd en cohérence de marque." },
    ],
  },
  {
    slug: "google-business-profile-photos-posts",
    title: "Photos et posts Google Business Profile : animer sa fiche pour convertir",
    description:
      "Quelles photos ajouter à sa fiche Google, à quelle fréquence, comment utiliser les posts Google Business et pourquoi une fiche vivante convertit et remonte dans le pack local.",
    date: "2026-05-13",
    readingTime: "8 min",
    category: "SEO local",
    keywords: [
      "photos Google Business Profile",
      "posts Google Business",
      "optimiser sa fiche avec photos",
      "publications Google Business",
    ],
    related: [
      { href: "/services/seo", label: "SEO technique" },
      { href: "/blog/optimiser-fiche-google-business-profile", label: "Optimiser sa fiche Google Business Profile" },
    ],
    content: [
      { type: "p", text: "Beaucoup d'entreprises créent leur fiche Google Business Profile, la remplissent une fois, puis n'y touchent plus. Or c'est précisément l'animation qui distingue une fiche qui capte des clients d'une fiche qui dort. Deux leviers concrets font ce travail : les photos et les posts. Ils inspirent confiance, augmentent les demandes de contact et signalent à Google une fiche active. Voici comment les exploiter réellement, au-delà d'une photo de façade oubliée depuis deux ans." },
      { type: "h2", text: "Pourquoi les photos changent tout" },
      { type: "p", text: "Les photos sont souvent la première chose que voit un prospect avant même de lire quoi que ce soit. Elles rassurent, donnent envie et projettent le client dans l'expérience. Une fiche riche en visuels réels et récents génère nettement plus de demandes d'itinéraire et d'appels qu'une fiche sans photo ou avec une seule image floue. C'est un levier de conversion gratuit, largement sous-exploité." },
      { type: "h2", text: "Quelles photos ajouter" },
      { type: "p", text: "Toutes les photos ne se valent pas. On cherche à couvrir les différents moments et facettes de l'expérience client, avec des images authentiques plutôt que des banques d'images génériques." },
      { type: "ul", items: [
        "L'extérieur : la façade sous plusieurs angles, pour qu'on vous repère facilement dans la rue.",
        "L'intérieur : l'ambiance, l'espace d'accueil, ce que le client verra en entrant.",
        "L'équipe au travail : des visages rassurent et humanisent l'établissement.",
        "Les produits ou réalisations : ce que vous vendez ou ce que vous faites concrètement.",
        "Des photos récentes et de bonne qualité, prises en lumière correcte, sans surcharge de texte ni logo envahissant.",
      ]},
      { type: "h2", text: "Les posts Google : l'actualité qui maintient la fiche vivante" },
      { type: "p", text: "Les posts Google Business sont des publications courtes qui apparaissent directement sur votre fiche : actualités, offres, événements, nouveautés. Ils ont deux vertus : montrer aux visiteurs que l'établissement est actif, et signaler à Google une fiche régulièrement mise à jour. Une fiche animée par des posts inspire davantage confiance qu'une fiche figée." },
      { type: "ul", items: [
        "Les nouveautés : un nouveau produit, un service, un aménagement, une info pratique.",
        "Les offres : une promotion datée, avec une période de validité claire.",
        "Les événements : une date, un lieu, une raison de venir ou de vous contacter.",
        "Un appel à l'action explicite (appeler, réserver, en savoir plus) sur chaque post.",
      ]},
      { type: "h2", text: "À quelle fréquence publier" },
      { type: "p", text: "La régularité prime sur l'intensité. Un post par semaine, tenu dans la durée, vaut mieux qu'une rafale de publications suivie de six mois de silence. Certains types de posts expirent au bout de quelques jours, ce qui rend d'autant plus utile d'entretenir un rythme régulier pour que la fiche affiche toujours quelque chose de récent. L'idée n'est pas de publier pour publier, mais de garder une fiche visiblement vivante." },
      { type: "cta", text: "Vous voulez une fiche Google animée qui convertit vraiment ?", href: "/services/seo", label: "Faire vivre votre fiche Google Business Profile" },
      { type: "h2", text: "Photos clients et gestion de ce que vous ne contrôlez pas" },
      { type: "p", text: "Les clients aussi ajoutent des photos à votre fiche, et vous ne pouvez pas les supprimer à volonté. C'est une raison de plus de publier régulièrement vos propres visuels de qualité : ils rééquilibrent la galerie et donnent le ton. Surveillez les photos ajoutées par les tiers, signalez celles qui enfreignent réellement les règles, et compensez toujours par un flux régulier de vos propres images soignées." },
      { type: "h2", text: "En résumé" },
      { type: "p", text: "Photos et posts sont le carburant d'une fiche Google Business Profile performante. Les photos rassurent et déclenchent l'action ; les posts montrent une activité continue et alimentent la relation. Le tout tient dans une habitude simple : ajouter des visuels réels et récents, publier régulièrement une actualité, garder la fiche vivante. C'est peu de travail hebdomadaire pour un effet direct sur les contacts entrants et sur votre présence dans le pack local." },
    ],
    faq: [
      { q: "Quelles photos ajouter à sa fiche Google Business Profile ?", a: "Couvrez les différentes facettes de l'expérience : l'extérieur (façade repérable), l'intérieur (ambiance, accueil), l'équipe au travail, les produits ou réalisations. Privilégiez des photos authentiques, récentes et de bonne qualité, en bonne lumière, plutôt que des banques d'images génériques." },
      { q: "Les photos améliorent-elles le classement de ma fiche ?", a: "Elles renforcent surtout la conversion : une fiche riche en visuels réels génère nettement plus de demandes d'itinéraire et d'appels. Ces interactions et une fiche complète et vivante envoient de bons signaux à Google, ce qui soutient indirectement la visibilité dans le pack local." },
      { q: "À quoi servent les posts Google Business ?", a: "Les posts sont des publications courtes (actualités, offres, événements) qui apparaissent sur votre fiche. Ils montrent aux visiteurs que l'établissement est actif et signalent à Google une fiche régulièrement mise à jour. Ajoutez toujours un appel à l'action clair (appeler, réserver, en savoir plus)." },
      { q: "À quelle fréquence faut-il publier des posts Google ?", a: "Visez la régularité plutôt que l'intensité : un post par semaine tenu dans la durée vaut mieux qu'une rafale suivie de longs silences. Certains posts expirent au bout de quelques jours, d'où l'intérêt d'un rythme régulier pour que la fiche affiche toujours quelque chose de récent." },
      { q: "Puis-je supprimer les photos ajoutées par les clients ?", a: "Pas librement : vous ne contrôlez pas les photos déposées par les tiers. Vous pouvez signaler celles qui enfreignent réellement les règles, mais le meilleur réflexe est de publier régulièrement vos propres visuels de qualité pour rééquilibrer la galerie et donner le ton de votre fiche." },
    ],
  },
];
