import type { Post } from "./posts";

export const POSTS_BILLETTERIE: Post[] = [
  {
    slug: "vendre-billets-en-ligne-guide",
    title: "Vendre des billets en ligne : le guide complet (2026)",
    description:
      "Comment vendre ses billets en ligne de bout en bout : paiement, quotas, tarifs multiples, préparation du jour J et pièges à éviter.",
    date: "2026-07-19",
    readingTime: "9 min",
    category: "Événementiel",
    keywords: [
      "vendre des billets en ligne",
      "billetterie en ligne guide",
      "créer une billetterie",
      "vendre billets événement",
    ],
    related: [
      { href: "/services/plateforme-evenementielle", label: "Plateforme événementielle" },
      { href: "/blog/billetterie-qr-code-evenement", label: "Billetterie QR code" },
    ],
    content: [
      { type: "p", text: "Vendre des billets en ligne n'est pas seulement une question de bouton Payer. C'est une chaîne complète : une page qui convertit, un paiement fiable, des quotas maîtrisés, des billets valides et un contrôle d'accès qui tient le jour J. Ce guide déroule chaque étape dans l'ordre, pour que vous encaissiez sans mauvaise surprise, quel que soit votre type d'événement." },
      { type: "h2", text: "Étape 1 : structurer votre offre de billets" },
      { type: "p", text: "Avant de vendre, définissez précisément ce que vous vendez. Un tarif unique convient à un petit concert, mais la plupart des événements ont besoin de plusieurs catégories, avec des règles claires de disponibilité et de dates. C'est cette structure qui déterminera votre chiffre d'affaires et votre trésorerie." },
      { type: "ul", items: [
        "Les catégories de tarifs : plein, réduit, early bird, VIP, gratuit sur invitation.",
        "Les quotas par catégorie, pour ne jamais dépasser la jauge réelle de la salle.",
        "Les dates d'ouverture et de fermeture de chaque tarif (les early bird s'arrêtent seuls).",
        "Les frais : soit inclus dans le prix affiché, soit ajoutés au moment du paiement.",
      ]},
      { type: "h2", text: "Étape 2 : choisir un paiement fiable" },
      { type: "p", text: "Le paiement est le maillon le plus sensible : un tunnel qui plante, c'est une vente perdue et un acheteur méfiant. Stripe est aujourd'hui la référence pour encaisser des cartes européennes, avec des frais de l'ordre de 1,5 % + 0,25 € par transaction. L'essentiel est que l'argent arrive directement sur votre compte, sans intermédiaire qui retienne les fonds pendant des semaines." },
      { type: "p", text: "Pensez aussi aux moyens de paiement attendus par votre public : carte bancaire évidemment, mais aussi Apple Pay et Google Pay qui réduisent l'abandon sur mobile, et le paiement en plusieurs fois pour les billets à panier élevé." },
      { type: "h2", text: "Étape 3 : générer des billets infalsifiables" },
      { type: "p", text: "Un billet vendu en ligne doit être un billet valide et unique. Chaque billet porte un QR code signé, impossible à dupliquer sans être détecté au scan. Le billet est envoyé par email immédiatement après le paiement, et reste disponible dans un espace acheteur ou un wallet mobile." },
      { type: "ul", items: [
        "Un QR code unique et signé par billet, pas un simple numéro.",
        "L'envoi automatique du billet PDF par email dès la confirmation de paiement.",
        "Le nominatif quand c'est utile (nom sur le billet, utile pour les événements sensibles).",
        "Un anti-doublon au scan pour qu'un même billet ne passe pas deux fois.",
      ]},
      { type: "h2", text: "Étape 4 : suivre vos ventes en temps réel" },
      { type: "p", text: "Vendre sans tableau de bord, c'est piloter à l'aveugle. Vous devez voir à tout instant combien de billets sont vendus par catégorie, votre chiffre d'affaires encaissé, et le rythme des ventes pour ajuster votre communication. Un pic après une newsletter ou une publicité vous dit immédiatement ce qui fonctionne." },
      { type: "cta", text: "Vous voulez vendre vos billets en ligne sans commission par billet, avec une plateforme à vous ?", href: "/services/plateforme-evenementielle", label: "Voir notre offre de plateforme événementielle" },
      { type: "h2", text: "Étape 5 : préparer le jour J" },
      { type: "p", text: "La vente ne s'arrête pas au paiement : elle se termine à l'entrée de votre événement. Préparez le contrôle d'accès à l'avance, testez le scan la veille, et prévoyez un mode qui fonctionne même sans réseau, car les lieux d'événement sont souvent mal couverts." },
      { type: "ul", items: [
        "Une application de scan qui fonctionne hors-ligne et se synchronise ensuite.",
        "Plusieurs points de contrôle pour fluidifier les files aux heures de pointe.",
        "Un comptage temps réel des entrées, pour connaître le taux de présence.",
        "Un plan B papier ou une liste exportée en cas de défaillance matérielle.",
      ]},
      { type: "p", text: "Bien organisée, la vente de billets en ligne devient un actif : vous encaissez vite, vous gardez vos données clients pour la prochaine édition, et vous maîtrisez l'expérience de bout en bout. Mal organisée, c'est une succession de petits ratés qui érodent la confiance et le chiffre d'affaires." },
    ],
    faq: [
      { q: "Comment commencer à vendre des billets en ligne ?", a: "Définissez d'abord vos catégories de tarifs et vos quotas, branchez un paiement fiable comme Stripe, puis générez des billets avec QR code envoyés automatiquement par email. Un tableau de bord de suivi et un contrôle d'accès pour le jour J complètent la chaîne." },
      { q: "Quels frais paie-t-on pour vendre des billets en ligne ?", a: "Avec une plateforme à commission, comptez souvent 1 à 5 % par billet, plus les frais bancaires. Avec une solution qui vous appartient, il ne reste que les frais Stripe (environ 1,5 % + 0,25 € par transaction) et l'hébergement, sans commission par billet." },
      { q: "Peut-on vendre plusieurs types de billets sur un même événement ?", a: "Oui. Vous pouvez créer autant de catégories que nécessaire (plein, réduit, early bird, VIP, invitation), chacune avec son propre quota et ses dates d'ouverture et de fermeture, pour ajuster finement votre stratégie de vente." },
      { q: "Comment éviter les billets frauduleux ?", a: "Chaque billet doit porter un QR code unique et signé, contrôlé au scan avec un anti-doublon. Un simple numéro ou un PDF non signé est facilement copié : c'est la signature cryptographique et le contrôle en temps réel qui empêchent la fraude." },
      { q: "Faut-il obligatoirement une connexion internet pour scanner les billets ?", a: "Non, à condition d'utiliser une application de scan qui gère le mode hors-ligne. Elle vérifie les billets localement puis se synchronise dès que le réseau revient, ce qui est indispensable dans les lieux mal couverts." },
    ],
  },
  {
    slug: "billetterie-comparatif-frais-plateformes",
    title: "Frais de billetterie : comparatif des plateformes (2026)",
    description:
      "Comparatif des frais et commissions des plateformes de billetterie, qui paie quoi, impact sur la marge et quand une alternative sur-mesure devient rentable.",
    date: "2026-07-18",
    readingTime: "9 min",
    category: "Événementiel",
    keywords: [
      "frais billetterie en ligne",
      "comparatif plateformes billetterie",
      "commission billetterie",
      "Weezevent Billetweb frais",
    ],
    related: [
      { href: "/services/plateforme-evenementielle", label: "Plateforme événementielle" },
      { href: "/blog/prix-plateforme-billetterie-evenementielle", label: "Prix d'une plateforme de billetterie" },
    ],
    content: [
      { type: "p", text: "Les plateformes de billetterie affichent volontiers une installation gratuite, mais leur modèle repose sur des frais prélevés à chaque billet. Comprendre d'où viennent ces frais, qui les paie et comment ils s'empilent est la seule façon de comparer honnêtement les solutions et de protéger votre marge. Voici comment lire un comparatif sans se faire piéger par le prix affiché." },
      { type: "h2", text: "Les couches de frais à distinguer" },
      { type: "p", text: "Un tarif de billetterie n'est jamais un chiffre unique. Il s'empile en plusieurs couches, et c'est leur addition qui compte, pas la ligne mise en avant sur la page tarifs." },
      { type: "ul", items: [
        "La commission de la plateforme, souvent exprimée en pourcentage du prix du billet.",
        "Un frais fixe par billet qui s'ajoute parfois à ce pourcentage.",
        "Les frais de paiement bancaire (de l'ordre de 1,5 % + 0,25 €), parfois inclus, parfois séparés.",
        "Les options payantes : billets personnalisés, contrôle d'accès, exports, support prioritaire.",
      ]},
      { type: "h2", text: "Qui paie réellement ces frais ?" },
      { type: "p", text: "La question clé est de savoir qui supporte le coût. Deux modèles cohabitent, et ils n'ont pas le même effet sur vos ventes et votre image." },
      { type: "ul", items: [
        "Frais absorbés : vous les payez, ils réduisent votre marge mais le prix affiché reste net pour l'acheteur.",
        "Frais répercutés : l'acheteur voit un prix qui gonfle à l'étape du paiement, ce qui augmente l'abandon.",
      ]},
      { type: "p", text: "Beaucoup d'organisateurs choisissent de répercuter pour préserver leur marge, sans mesurer que des frais de service visibles au dernier moment font chuter la conversion. Le coût caché n'est donc pas seulement la commission, c'est aussi la vente perdue." },
      { type: "h2", text: "Comparer les plateformes grand public" },
      { type: "p", text: "Les acteurs comme Weezevent, Billetweb ou Helloasso pratiquent des grilles proches : une commission souvent située entre 1 et 5 % selon le prix du billet et les options, à laquelle s'ajoutent les frais de paiement. Helloasso, tourné vers les associations, fonctionne sur un pourboire optionnel de l'acheteur plutôt qu'une commission imposée, ce qui change la logique." },
      { type: "p", text: "Pour comparer sérieusement, ne regardez pas la commission unitaire mais le coût total sur votre volume annuel. Un festival qui vend 5 000 billets à 25 € génère 125 000 € de recettes ; à 3 %, cela représente environ 3 750 € de frais pour une seule édition. Multiplié par plusieurs éditions, l'écart devient structurant." },
      { type: "cta", text: "Vous voulez chiffrer ce qu'une billetterie à vous vous ferait économiser sur votre volume ?", href: "/services/plateforme-evenementielle", label: "Voir notre offre de plateforme événementielle" },
      { type: "h2", text: "L'alternative sur-mesure" },
      { type: "p", text: "Une billetterie qui vous appartient supprime la commission par billet : vous ne payez plus que les frais Stripe et l'hébergement. C'est un investissement initial, mais il transforme un coût proportionnel et récurrent en coût fixe. Sur un volume important ou récurrent, la bascule est rapide, et vous récupérez au passage le contrôle de votre marque et de vos données clients." },
      { type: "p", text: "Le bon comparatif n'oppose donc pas des pourcentages, mais deux modèles économiques : payer un peu à chaque succès, indéfiniment, ou payer une fois pour ne plus rien reverser ensuite. Le choix dépend de votre volume et de la récurrence de vos événements." },
    ],
    faq: [
      { q: "Quels sont les frais moyens d'une plateforme de billetterie ?", a: "La commission se situe souvent entre 1 et 5 % du prix du billet selon la plateforme et les options, à laquelle s'ajoutent les frais de paiement bancaire (environ 1,5 % + 0,25 €). Le total réel dépend de votre configuration et du prix de vos billets." },
      { q: "Qui paie les frais de billetterie, l'organisateur ou l'acheteur ?", a: "Cela dépend du réglage choisi. Vous pouvez absorber les frais (ils réduisent votre marge) ou les répercuter sur l'acheteur (le prix gonfle au paiement). Répercuter préserve la marge mais augmente le taux d'abandon au dernier moment." },
      { q: "Weezevent et Billetweb sont-ils moins chers qu'une billetterie sur mesure ?", a: "À faible volume, oui, car il n'y a pas d'investissement initial. À volume élevé ou récurrent, la commission par billet finit par dépasser le coût d'une solution propre : le sur-mesure devient alors plus économique sur un à deux ans." },
      { q: "Comment comparer honnêtement deux plateformes de billetterie ?", a: "Ne comparez pas la commission unitaire mais le coût total sur votre volume annuel réel, frais de paiement inclus. Ajoutez le coût des options payantes que vous utiliserez vraiment, et tenez compte de l'impact des frais répercutés sur votre conversion." },
      { q: "Helloasso est-il vraiment gratuit ?", a: "Helloasso ne prélève pas de commission imposée mais propose un pourboire optionnel à l'acheteur au moment du paiement. Le service est donc financé par ces contributions volontaires, ce qui reste un modèle différent d'une commission fixe." },
    ],
  },
  {
    slug: "reduire-frais-commission-billetterie",
    title: "Réduire les frais de commission de sa billetterie",
    description:
      "D'où viennent les frais de billetterie, faut-il les absorber ou les répercuter, et à partir de quel seuil une solution propre devient rentable.",
    date: "2026-07-17",
    readingTime: "8 min",
    category: "Événementiel",
    keywords: [
      "réduire frais billetterie",
      "commission billetterie trop chère",
      "économiser billetterie en ligne",
      "billetterie sans commission",
    ],
    related: [
      { href: "/services/plateforme-evenementielle", label: "Plateforme événementielle" },
      { href: "/tarifs", label: "Nos tarifs" },
    ],
    content: [
      { type: "p", text: "Une commission de quelques pour cent paraît anodine sur un billet, mais elle se paie à chaque vente et à chaque édition. Sur une saison entière, elle représente parfois plusieurs milliers d'euros qui quittent votre trésorerie sans contrepartie. Réduire ces frais commence par comprendre exactement d'où ils viennent, puis par choisir la bonne stratégie selon votre volume." },
      { type: "h2", text: "D'où viennent réellement les frais" },
      { type: "p", text: "Sur chaque billet vendu, deux prélèvements distincts se cumulent. Les confondre empêche d'agir sur le bon levier." },
      { type: "ul", items: [
        "La commission de la plateforme, qui rémunère le service et n'est pas incompressible.",
        "Les frais de paiement bancaire (de l'ordre de 1,5 % + 0,25 €), techniques et difficilement évitables.",
      ]},
      { type: "p", text: "Les frais bancaires existent quelle que soit la solution : ils rémunèrent le traitement de la carte. La commission de la plateforme, elle, est la partie sur laquelle vous pouvez vraiment agir, car elle disparaît si vous possédez votre propre billetterie." },
      { type: "h2", text: "Absorber ou répercuter : le mauvais dilemme" },
      { type: "p", text: "Face à la commission, beaucoup d'organisateurs hésitent entre l'absorber (au détriment de leur marge) ou la répercuter sur l'acheteur (au détriment de leur conversion). Les deux ont un coût, simplement il change de forme." },
      { type: "ul", items: [
        "Absorber protège le prix affiché mais grignote directement votre marge, billet après billet.",
        "Répercuter préserve la marge mais fait grimper le prix au dernier moment, ce qui augmente l'abandon de panier.",
      ]},
      { type: "p", text: "Ce dilemme est en réalité un faux choix : il consiste à décider qui paie une commission, alors que la vraie économie consiste à la supprimer. Tant qu'elle existe, quelqu'un la finance, vous ou votre public." },
      { type: "h2", text: "Le seuil de rentabilité d'une solution propre" },
      { type: "p", text: "Une billetterie qui vous appartient supprime la commission par billet et ne laisse que les frais Stripe et l'hébergement. Elle demande un investissement initial, mais celui-ci se compare simplement à la commission que vous paieriez autrement." },
      { type: "p", text: "Le calcul est direct : additionnez la commission versée sur votre volume annuel. Dès qu'elle dépasse le coût d'une plateforme sur mesure sur un à deux ans, la solution propre devient rentable. Pour un organisateur qui vend plusieurs milliers de billets par saison, ou qui enchaîne les éditions, le point de bascule arrive vite." },
      { type: "cta", text: "Vous voulez savoir à partir de quel volume une billetterie à vous devient rentable ?", href: "/tarifs", label: "Voir nos tarifs" },
      { type: "h2", text: "Réduire les frais sans changer d'outil" },
      { type: "p", text: "Si le sur-mesure n'est pas encore justifié, quelques réglages limitent la casse en attendant. Ils ne suppriment pas la commission mais en réduisent l'impact." },
      { type: "ul", items: [
        "Négocier le taux dès que votre volume augmente : les grilles sont souvent dégressives.",
        "Regrouper vos événements sur une même plateforme pour peser dans la négociation.",
        "Intégrer les frais dans le prix affiché plutôt que de les révéler au paiement, pour préserver la conversion.",
        "Supprimer les options payantes dont vous ne vous servez pas réellement.",
      ]},
      { type: "p", text: "Réduire ses frais de billetterie, c'est donc d'abord une question d'échelle. À petit volume, on optimise les réglages ; à volume élevé ou récurrent, on supprime la commission en passant à une solution qui vous appartient. Dans les deux cas, l'erreur serait de subir des frais sans jamais les mesurer." },
    ],
    faq: [
      { q: "Peut-on avoir une billetterie sans commission ?", a: "Oui, avec une billetterie qui vous appartient : il ne reste alors que les frais de paiement Stripe (environ 1,5 % + 0,25 €) et l'hébergement, sans commission reversée à un intermédiaire. Les plateformes grand public, elles, prélèvent presque toujours une commission par billet." },
      { q: "Les frais bancaires sont-ils évitables ?", a: "Non, pas vraiment : les frais de paiement rémunèrent le traitement de la carte et existent quelle que soit la solution. C'est la commission de la plateforme, distincte, qui peut être réduite ou supprimée en changeant de modèle." },
      { q: "Vaut-il mieux absorber ou répercuter les frais sur l'acheteur ?", a: "Absorber protège le prix affiché mais réduit votre marge ; répercuter préserve la marge mais fait grimper le prix au paiement et augmente l'abandon. Répercuter les frais dans le prix affiché dès le départ est souvent le meilleur compromis pour la conversion." },
      { q: "À partir de quel volume une billetterie sans commission est-elle rentable ?", a: "Additionnez la commission que vous paieriez sur votre volume annuel. Dès qu'elle dépasse le coût d'une solution propre sur un à deux ans, celle-ci devient rentable. Pour un organisateur récurrent vendant plusieurs milliers de billets, la bascule est rapide." },
      { q: "Comment réduire ses frais sans changer de plateforme ?", a: "Négociez votre taux à mesure que le volume augmente, regroupez vos événements pour peser dans la négociation, intégrez les frais dans le prix affiché plutôt qu'au paiement, et supprimez les options payantes inutiles. Ces leviers limitent l'impact sans supprimer la commission." },
    ],
  },
  {
    slug: "paiement-plusieurs-fois-billetterie",
    title: "Paiement en plusieurs fois pour vos billets : mode d'emploi",
    description:
      "Proposer le paiement en 3x ou 4x sur vos billets : impact sur la conversion et le panier moyen, mécanique Stripe et risques à anticiper.",
    date: "2026-07-16",
    readingTime: "8 min",
    category: "Événementiel",
    keywords: [
      "billet paiement plusieurs fois",
      "paiement 3x billetterie",
      "payer billet en plusieurs fois",
      "Stripe 3x événement",
    ],
    related: [
      { href: "/services/plateforme-evenementielle", label: "Plateforme événementielle" },
      { href: "/services/tracking-conformite", label: "Tracking & Conformité" },
    ],
    content: [
      { type: "p", text: "Sur un billet à 25 €, le paiement en plusieurs fois n'a guère d'intérêt. Mais sur un pass festival, un stand d'exposant ou une place VIP à plusieurs centaines d'euros, la possibilité de payer en 3x ou 4x change tout : elle lève le frein du montant et rend l'achat immédiat au lieu d'être reporté. Voici quand la proposer, comment elle fonctionne techniquement, et les risques à cadrer." },
      { type: "h2", text: "Pourquoi le paiement fractionné convertit" },
      { type: "p", text: "Le montant total est le premier motif d'abandon sur un panier élevé. Fractionner ce montant réduit la friction psychologique et débloque des achats qui, autrement, seraient reportés ou annulés. L'effet joue sur deux leviers à la fois." },
      { type: "ul", items: [
        "Un meilleur taux de conversion sur les billets à panier élevé, car le premier versement paraît accessible.",
        "Un panier moyen plus important, car les acheteurs osent la catégorie supérieure ou ajoutent des places.",
      ]},
      { type: "p", text: "L'effet est surtout marqué au-delà d'une certaine somme. En dessous, le gain de conversion est marginal et ne justifie pas la complexité ajoutée : réservez le fractionné aux billets et pass réellement chers." },
      { type: "h2", text: "La mécanique côté Stripe" },
      { type: "p", text: "Techniquement, deux approches coexistent, et elles ne portent pas le même risque pour vous." },
      { type: "ul", items: [
        "Le paiement fractionné natif de type Klarna : c'est le prestataire qui avance les fonds, vous êtes payé en une fois et il porte le risque d'impayé.",
        "Le prélèvement échelonné sur la carte de l'acheteur : la plateforme rejoue le paiement à échéances fixes, et c'est vous qui portez le risque d'échec.",
      ]},
      { type: "p", text: "Dans le second cas, la carte est enregistrée de façon sécurisée puis débitée automatiquement aux dates prévues. Le tunnel doit gérer proprement l'authentification forte de la première échéance, car en Europe la réglementation impose une validation renforcée du paiement." },
      { type: "cta", text: "Vous voulez proposer le paiement en 3x ou 4x sur vos billets sans galérer avec Stripe ?", href: "/services/plateforme-evenementielle", label: "Voir notre offre de plateforme événementielle" },
      { type: "h2", text: "Les risques à anticiper" },
      { type: "p", text: "Le paiement échelonné n'est pas sans contrepartie. Si vous portez le risque, quelques scénarios doivent être cadrés dès le départ pour ne pas vous retrouver avec un billet valide et une échéance impayée." },
      { type: "ul", items: [
        "L'échéance qui échoue : carte expirée, plafond atteint, provision insuffisante. Prévoyez des relances et une politique claire.",
        "Le billet déjà utilisé alors qu'une échéance reste due : décidez si l'accès dépend du paiement complet.",
        "Le remboursement partiel en cas d'annulation, plus complexe à gérer sur un paiement en cours.",
        "Le coût : certaines solutions de fractionné prélèvent une commission supérieure au paiement classique.",
      ]},
      { type: "p", text: "Bien encadré, le paiement en plusieurs fois est un levier de vente puissant sur les billets chers : il transforme un montant dissuasif en achat accessible. Mal encadré, il crée des impayés et des litiges. La clé est de le réserver aux paniers élevés et de définir à l'avance la règle en cas d'échéance manquée." },
    ],
    faq: [
      { q: "À partir de quel montant proposer le paiement en plusieurs fois ?", a: "Le fractionné est surtout utile sur les billets et pass à panier élevé, typiquement à partir de plusieurs dizaines ou centaines d'euros. En dessous, le gain de conversion est marginal et ne compense pas la complexité ajoutée." },
      { q: "Le paiement en 3x augmente-t-il vraiment les ventes ?", a: "Sur les billets chers, oui : il réduit le frein du montant total et améliore la conversion, tout en poussant le panier moyen vers le haut. Sur les petits montants, l'effet est négligeable, mieux vaut alors ne pas l'activer." },
      { q: "Qui porte le risque d'impayé sur un paiement fractionné ?", a: "Cela dépend de la solution. Avec un prestataire de type Klarna, le prestataire avance les fonds et porte le risque. Avec un prélèvement échelonné sur la carte de l'acheteur, c'est vous qui portez le risque d'échec des échéances suivantes." },
      { q: "Le paiement en plusieurs fois est-il compatible avec Stripe ?", a: "Oui. Stripe permet à la fois d'intégrer des solutions de fractionné et d'enregistrer la carte pour la débiter à échéances fixes. La première échéance doit respecter l'authentification forte imposée en Europe." },
      { q: "Que se passe-t-il si une échéance n'est pas payée ?", a: "Il faut définir la règle à l'avance : relance automatique de l'échéance, conditionnement de l'accès au paiement complet, ou blocage du billet. Sans politique claire, vous risquez de vous retrouver avec un billet valide et une somme impayée." },
    ],
  },
  {
    slug: "billetterie-sur-mesure-vs-solution-saas",
    title: "Billetterie sur mesure ou solution SaaS : comment choisir",
    description:
      "Sur-mesure ou clé-en-main : coût total, contrôle des données et de la marque, et dans quels cas chaque option se justifie vraiment.",
    date: "2026-07-15",
    readingTime: "9 min",
    category: "Événementiel",
    keywords: [
      "billetterie sur mesure",
      "plateforme billetterie SaaS",
      "développer sa billetterie",
      "billetterie personnalisée",
    ],
    related: [
      { href: "/services/plateforme-evenementielle", label: "Plateforme événementielle" },
      { href: "/blog/site-billetterie-association", label: "Site de billetterie pour association" },
    ],
    content: [
      { type: "p", text: "Faut-il développer sa propre billetterie ou s'abonner à une solution clé-en-main ? La réponse honnête est : cela dépend. Un organisateur ponctuel n'a rien à gagner à développer ; un opérateur récurrent qui veut maîtriser sa marque et ses données a tout intérêt à le faire. Comparons les deux modèles sur ce qui compte vraiment : le coût total, le contrôle et le moment où chacun se justifie." },
      { type: "h2", text: "Deux modèles économiques opposés" },
      { type: "p", text: "La différence de fond n'est pas fonctionnelle mais économique. Une solution SaaS transforme la billetterie en coût variable ; le sur-mesure en fait un actif à coût fixe." },
      { type: "ul", items: [
        "SaaS : peu ou pas d'investissement initial, mais une commission prélevée sur chaque billet, à vie.",
        "Sur-mesure : un investissement initial unique, puis seulement les frais Stripe et l'hébergement.",
      ]},
      { type: "p", text: "Le SaaS est indolore au démarrage et coûteux à l'échelle ; le sur-mesure est un effort initial qui s'amortit d'autant plus vite que votre volume est élevé et récurrent. Tout se joue sur votre trajectoire, pas sur un chiffre isolé." },
      { type: "h2", text: "Le coût total sur la durée" },
      { type: "p", text: "Pour comparer, il faut raisonner sur plusieurs années, pas sur une édition. Le SaaS ne facture rien à l'installation, mais additionnez la commission versée saison après saison et le total gonfle. Le sur-mesure demande un budget de départ, souvent à partir de quelques milliers d'euros pour une billetterie essentielle, puis reste quasi stable." },
      { type: "p", text: "Un exemple fixe les idées : un opérateur qui verse 3 000 à 4 000 € de commission par édition dépasse, en deux ou trois éditions, le coût d'une plateforme sur mesure. À partir de là, chaque édition supplémentaire est presque gratuite côté billetterie." },
      { type: "h2", text: "Le contrôle de la marque et des données" },
      { type: "p", text: "Au-delà du prix, le sur-mesure change la nature de la relation avec votre public. C'est souvent ce qui emporte la décision pour un opérateur installé." },
      { type: "ul", items: [
        "Votre marque : URL, design, emails de confirmation à vos couleurs, sans logo d'un tiers.",
        "Vos données clients : elles vous appartiennent et sont réexploitables pour la relance et la fidélisation.",
        "Vos fonctionnalités : réservation exposants, acompte, invitations VIP, tracking publicitaire fin.",
        "Votre indépendance : pas de changement de tarif ou de conditions imposé par un prestataire.",
      ]},
      { type: "cta", text: "Vous hésitez entre une billetterie sur mesure et une solution SaaS pour vos événements ?", href: "/services/plateforme-evenementielle", label: "Voir notre offre de plateforme événementielle" },
      { type: "h2", text: "Quand chaque option se justifie" },
      { type: "p", text: "Il n'y a pas de bonne réponse universelle, seulement une bonne réponse pour votre situation. Le tri est en réalité assez simple." },
      { type: "ul", items: [
        "Le SaaS convient à un événement ponctuel, à faible volume, sans besoin spécifique et sans récurrence.",
        "Le sur-mesure se justifie dès que vous enchaînez les éditions, que le volume grimpe, ou que vous avez des besoins que le clé-en-main couvre mal.",
        "Le sur-mesure s'impose si votre marque et vos données clients sont un enjeu stratégique.",
      ]},
      { type: "p", text: "Le bon choix n'est donc pas idéologique. Un organisateur qui teste un concept a raison de démarrer en SaaS ; un opérateur qui construit une saison année après année a raison d'investir dans une plateforme à lui. L'erreur serait de rester en SaaS par habitude alors que la commission cumulée a depuis longtemps dépassé le coût d'une solution propre." },
    ],
    faq: [
      { q: "Quelle est la différence entre une billetterie sur mesure et une solution SaaS ?", a: "Une solution SaaS est clé-en-main avec peu d'investissement initial mais une commission sur chaque billet, à vie. Une billetterie sur mesure demande un investissement de départ mais supprime la commission : il ne reste que les frais Stripe et l'hébergement." },
      { q: "Le sur-mesure revient-il plus cher qu'une solution SaaS ?", a: "À faible volume et pour un événement ponctuel, oui, car il n'y a pas de commission à comparer. À volume élevé ou récurrent, la commission cumulée du SaaS dépasse rapidement le coût d'une solution propre, souvent en deux ou trois éditions." },
      { q: "Pourquoi le contrôle des données compte-t-il ?", a: "Avec une billetterie qui vous appartient, vos données clients vous restent et sont réexploitables pour la relance et la fidélisation. En SaaS, elles transitent par un tiers et sont plus difficiles à mobiliser librement, ce qui limite votre marketing." },
      { q: "Quand faut-il choisir une solution SaaS ?", a: "Le SaaS est le bon choix pour un événement ponctuel, à faible volume, sans besoin fonctionnel spécifique et sans récurrence. Il permet de démarrer vite et sans investissement, ce qui convient parfaitement pour tester un concept." },
      { q: "Peut-on migrer d'une solution SaaS vers une billetterie sur mesure ?", a: "Oui, c'est fréquent : beaucoup d'organisateurs démarrent en SaaS puis basculent vers le sur-mesure quand le volume et la récurrence rendent la commission trop coûteuse. L'important est de récupérer et structurer ses données clients lors de la transition." },
    ],
  },
  {
    slug: "controle-acces-scan-billets-jour-j",
    title: "Contrôle d'accès le jour J : scanner ses billets sans stress",
    description:
      "Organiser le contrôle d'accès de son événement : scan QR hors-ligne, anti-fraude, gestion des files et rôle du staff pour une entrée fluide.",
    date: "2026-07-14",
    readingTime: "8 min",
    category: "Événementiel",
    keywords: [
      "contrôle accès événement",
      "scanner billets QR code",
      "gestion entrées événement",
      "application scan billets",
    ],
    related: [
      { href: "/services/plateforme-evenementielle", label: "Plateforme événementielle" },
      { href: "/blog/billetterie-qr-code-evenement", label: "Billetterie QR code" },
    ],
    content: [
      { type: "p", text: "Vous avez tout bien vendu, et pourtant l'événement peut se jouer à l'entrée. Une file qui s'allonge, un scan qui plante faute de réseau, un billet dupliqué qui passe deux fois : le contrôle d'accès est le moment où tout se vérifie en conditions réelles. Le préparer sérieusement, c'est garantir une entrée fluide, une sécurité réelle et une image professionnelle dès les premières secondes." },
      { type: "h2", text: "Le scan hors-ligne, non négociable" },
      { type: "p", text: "Les lieux d'événement sont souvent mal couverts : sous-sol, chapiteau, salle des fêtes en zone blanche. Un scan qui dépend du réseau tombe au pire moment, quand la file se forme. L'application de contrôle doit donc fonctionner hors-ligne par conception." },
      { type: "ul", items: [
        "La liste des billets valides est téléchargée à l'avance sur chaque appareil de scan.",
        "La vérification se fait localement, en une fraction de seconde, sans dépendre du réseau.",
        "Les entrées se synchronisent entre appareils dès que la connexion revient.",
        "Un comptage temps réel des présents reste disponible même en mode dégradé.",
      ]},
      { type: "h2", text: "L'anti-fraude au scan" },
      { type: "p", text: "Un billet en ligne n'a de valeur que si son contrôle est fiable. Deux fraudes classiques doivent être bloquées au moment du scan, pas après." },
      { type: "ul", items: [
        "La copie : un QR code signé cryptographiquement ne peut pas être fabriqué ni modifié sans être détecté.",
        "Le doublon : le même billet présenté deux fois est refusé, y compris sur un autre point de contrôle grâce à la synchronisation.",
      ]},
      { type: "p", text: "C'est la combinaison des deux qui protège vraiment. Une signature empêche de créer de faux billets ; l'anti-doublon empêche de réutiliser un vrai billet plusieurs fois. Un simple numéro imprimé, lui, se copie sans difficulté." },
      { type: "h2", text: "Gérer les files aux heures de pointe" },
      { type: "p", text: "Le pire ennemi de l'entrée n'est pas la fraude, c'est l'attente. Un afflux concentré juste avant le début peut créer une file décourageante. Quelques choix d'organisation la font fondre." },
      { type: "ul", items: [
        "Plusieurs points de contrôle en parallèle, dimensionnés sur le pic d'affluence, pas sur la moyenne.",
        "Des files séparées par catégorie (VIP, accès prioritaire) pour éviter les goulots.",
        "Un pré-contrôle visuel pour orienter et préparer les billets avant le scan.",
        "Une signalétique claire pour que chacun sache où se diriger sans hésiter.",
      ]},
      { type: "cta", text: "Vous voulez un contrôle d'accès fiable et hors-ligne pour votre prochain événement ?", href: "/services/plateforme-evenementielle", label: "Voir notre offre de plateforme événementielle" },
      { type: "h2", text: "Préparer et briefer le staff" },
      { type: "p", text: "La technique ne suffit pas : ce sont des personnes qui scannent, orientent et gèrent les cas particuliers. Un staff briefé transforme une entrée tendue en accueil fluide." },
      { type: "ul", items: [
        "Tester le scan et le mode hors-ligne la veille, avec de vrais billets, pas le jour même.",
        "Expliquer la conduite à tenir en cas de billet refusé, de doublon ou de litige.",
        "Prévoir un référent joignable pour trancher rapidement les cas bloquants.",
        "Garder un plan B (liste exportée, batterie de secours) en cas de défaillance matérielle.",
      ]},
      { type: "p", text: "Le contrôle d'accès est la dernière étape de votre billetterie, et la plus visible pour le public. Bien préparé, avec un scan hors-ligne fiable, un anti-fraude solide, des files pensées et un staff briefé, il devient invisible : les gens entrent vite et sereinement. C'est exactement l'effet recherché, car une entrée réussie donne le ton de tout l'événement." },
    ],
    faq: [
      { q: "Faut-il une connexion internet pour scanner les billets ?", a: "Non, à condition d'utiliser une application qui gère le mode hors-ligne. La liste des billets valides est téléchargée à l'avance sur chaque appareil, la vérification se fait localement, puis les entrées se synchronisent dès que le réseau revient." },
      { q: "Comment empêcher qu'un billet soit utilisé deux fois ?", a: "Grâce à l'anti-doublon au scan : un billet déjà validé est refusé s'il est présenté de nouveau, y compris sur un autre point de contrôle grâce à la synchronisation entre appareils. Le QR code signé empêche par ailleurs de fabriquer de faux billets." },
      { q: "Combien de points de contrôle prévoir à l'entrée ?", a: "Dimensionnez-les sur le pic d'affluence, pas sur la moyenne : l'affluence se concentre souvent juste avant le début. Plusieurs points en parallèle, avec des files séparées par catégorie, évitent les files décourageantes aux heures de pointe." },
      { q: "Comment scanner des billets QR code sur un événement ?", a: "Avec une application de scan installée sur smartphone ou tablette, capable de lire le QR code de chaque billet, de le vérifier et de refuser les doublons. Elle doit fonctionner hors-ligne et se synchroniser entre appareils pour un contrôle fiable." },
      { q: "Que faire si le matériel de scan tombe en panne le jour J ?", a: "Prévoyez toujours un plan B : une liste des billets exportée, des batteries de secours et un référent joignable pour trancher. Tester le scan et le mode hors-ligne la veille, avec de vrais billets, réduit fortement le risque de mauvaise surprise." },
    ],
  },
];
